// Geography Quiz Content — Gyaanpravaha
// All 7 chapters, 25 marks each

export type QuestionType = 'mcq' | 'single_word' | 'sentence' | 'long_answer'
export interface MCQOption { label: string; text: string }
export interface Question {
  id: number; type: QuestionType; marks: number; question: string
  options?: MCQOption[]; answer: string; reexplanation: string; hint?: string
}
export interface ChapterQuiz { chapterId: number; title: string; totalMarks: number; questions: Question[] }

const quiz1: ChapterQuiz = {
  chapterId: 1, title: 'Our Earth in the Solar System', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'How long ago did the Big Bang occur, according to most astronomers?', options: [{ label: 'A', text: '4.6 billion years ago' }, { label: 'B', text: '15 billion years ago' }, { label: 'C', text: '5 billion years ago' }, { label: 'D', text: '100 billion years ago' }], answer: 'B', reexplanation: 'According to most astronomers, the universe started with a gigantic explosion — the Big Bang — about 15 billion years ago. Our Sun was born much later, about 4.6 billion years ago, from a fragment of a nebula.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which planet is known as "The Jewel Planet" because of its rings?', options: [{ label: 'A', text: 'Jupiter' }, { label: 'B', text: 'Uranus' }, { label: 'C', text: 'Saturn' }, { label: 'D', text: 'Neptune' }], answer: 'C', reexplanation: 'Saturn is known as "The Jewel Planet" because of its beautiful rings. Jupiter is "The Giant Planet," Uranus is "A Planet on Its Side," and Neptune is "The Last Giant."' },
    { id: 3, type: 'mcq', marks: 1, question: 'Which of the following are called terrestrial (inner) planets?', options: [{ label: 'A', text: 'Jupiter, Saturn, Uranus, Neptune' }, { label: 'B', text: 'Mercury, Venus, Earth, Mars' }, { label: 'C', text: 'Mercury, Venus, Jupiter, Saturn' }, { label: 'D', text: 'Earth, Mars, Jupiter, Saturn' }], answer: 'B', reexplanation: 'Mercury, Venus, Earth and Mars are known as the inner planets or terrestrial planets because they are rocky. Jupiter, Saturn, Uranus and Neptune are the outer planets — called gas giants because they are chiefly made of gases.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Why is Earth called the "Blue Planet"?', options: [{ label: 'A', text: 'Because of its blue sky' }, { label: 'B', text: 'Because about two-thirds of its surface is covered with water' }, { label: 'C', text: 'Because of the blue colour of its atmosphere' }, { label: 'D', text: 'Because it is the coldest planet' }], answer: 'B', reexplanation: 'Earth is called the Blue Planet because about two-thirds of its surface is covered with water — making it appear blue from outer space. The three conditions that make Earth special are moderate temperature, suitable atmosphere, and presence of water.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What is the full Moon called in India?', options: [{ label: 'A', text: 'Amavasya' }, { label: 'B', text: 'Eclipse' }, { label: 'C', text: 'Purnima' }, { label: 'D', text: 'Prabha' }], answer: 'C', reexplanation: 'When the Moon looks like a full disc, it is called full Moon or purnima. When the side of the Moon facing us does not receive sunlight and we cannot see the Moon, this is known as the new Moon or amavasya.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is a giant cloud of gases and dust particles from which stars are born called?', answer: 'Nebula', reexplanation: 'A nebula is a giant cloud of gases and tiny dust particles formed after the Big Bang. Nebulae had their own spinning motion and gravity. Fragments of nebulae were attracted to each other and collided, producing heat — resulting in the birth of glowing stars.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the fixed path along which a planet revolves around the Sun called?', answer: 'Orbit', reexplanation: 'The orbit is the fixed path along which a planet revolves around the Sun. The Sun\'s gravity holds the Earth and other planets in their orbits. The Earth\'s orbit is elliptical — not perfectly circular — which is why its distance from the Sun varies.' },
    { id: 8, type: 'single_word', marks: 1, question: 'Which is the brightest star in the night sky that helps determine north direction?', answer: 'Pole Star / North Star', reexplanation: 'The brightest star in the night sky is the Pole Star or North Star. It appears to remain in the same position in the sky because it is almost directly above the North Pole. Navigators and travellers have used it to determine the north direction at night for thousands of years.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the surface temperature of the Sun approximately?', answer: '6000°C', reexplanation: 'The Sun has a surface temperature of about 6000°C. It is made up of intensely hot, burning gases — primarily hydrogen and helium. It is about 150 million km away from the Earth and light from it takes about 8 minutes to reach us.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What is the new Moon called in India?', answer: 'Amavasya', reexplanation: 'Amavasya is the new Moon — when the side of the Moon facing the Earth does not receive sunlight. We cannot see the Moon on this night. Purnima is the full Moon, when the Moon is visible as a complete disc.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "celestial" in a sentence about what we see in the night sky.', answer: 'All the objects we see in the night sky — stars, planets, satellites, asteroids, meteors and comets — are called celestial bodies.', hint: 'Celestial means relating to the sky or outer space.', reexplanation: 'Celestial bodies are all the natural objects found in space and the sky. The word comes from the Latin word for heaven. Use it in a sentence that names at least two or three types of celestial bodies.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "reflect" in a sentence about how we see planets.', answer: 'Planets do not produce their own light — they reflect the light of the Sun, which is why we can see them in the night sky.', hint: 'Reflect means to throw back light that falls on a surface.', reexplanation: 'Unlike stars which produce their own light, planets shine because they reflect sunlight. The Moon also shines because it reflects sunlight. This is why moonlight is cooler than sunlight.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "atmosphere" in a sentence about why Earth can support life.', answer: 'Earth\'s atmosphere contains nitrogen, oxygen, carbon dioxide and ozone — gases necessary for all life — and also acts as a protective shield against the Sun\'s harmful rays.', hint: 'The atmosphere is the blanket of air surrounding the Earth.', reexplanation: 'The atmosphere is one of the three conditions that makes Earth special. It contains the gases needed for life AND protects life from harmful solar radiation. Without the atmosphere, both conditions would fail simultaneously.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "solar system" in a sentence explaining what it contains.', answer: 'The solar system is the family of the Sun — it includes the Sun at the centre, eight planets, their satellites, asteroids, meteors and comets, all revolving around the Sun.', hint: 'The solar system is everything that orbits the Sun.', reexplanation: 'The word solar comes from the Latin word sol, meaning Sun. The solar system is the entire family of the Sun — everything that is held in orbit by the Sun\'s gravity. List its members: planets, satellites, asteroids, meteors, comets.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "gravity" in a sentence about the Sun\'s role in the solar system.', answer: 'The huge mass of the Sun gives it a very powerful force of gravity that holds all the planets in their fixed orbits.', hint: 'Gravity is the force that attracts objects towards each other.', reexplanation: 'Gravity is what keeps the solar system together. The Sun\'s enormous mass creates a gravitational pull so powerful that it holds all 8 planets — from tiny Mercury to giant Neptune — in their fixed orbits. Without the Sun\'s gravity, the planets would fly off into space.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Describe the three conditions that make Earth a special planet capable of supporting life. Explain why each condition is important and why no other planet in our solar system has all three.', answer: 'Earth is the only known planet capable of supporting life because it has three unique conditions working together. First, moderate temperature: The amount of heat a planet receives depends on its distance from the Sun. Earth is at just the right distance — not too close (which would make it burning hot like Mercury) and not too far (which would make it freezing cold like Neptune). This moderate temperature allows water to exist in liquid form and supports plant and animal life. Second, suitable atmosphere: Earth is surrounded by a blanket of air containing nitrogen, oxygen, carbon dioxide and ozone — all essential for life. Oxygen is needed for respiration, carbon dioxide for plant photosynthesis, and the ozone layer protects all life from the Sun\'s harmful ultraviolet rays. Third, presence of water: Due to the favourable temperature, water exists on Earth in all three forms — solid (ice), liquid (oceans, rivers) and gas (water vapour). Water is essential for all life. About two-thirds of Earth\'s surface is covered with water — which is why it appears blue from space and is called the Blue Planet. No other planet in our solar system has all three conditions together. Venus is too hot (atmosphere of CO₂ traps heat). Mars is too cold and has thin atmosphere. Jupiter and the outer planets are gas giants with no solid surface.', hint: 'Name each of the three conditions, explain what it means, and explain why it is essential for life. Then briefly say why other planets don\'t have all three.', reexplanation: 'Structure your answer around the three conditions: (1) Moderate temperature — right distance from Sun, neither too hot nor too cold; (2) Suitable atmosphere — nitrogen, oxygen, CO₂, ozone — needed for respiration, photosynthesis, and protection from UV; (3) Presence of water — in all three states, essential for life, makes Earth the Blue Planet. Then conclude by noting that no other planet has all three simultaneously.' },
  ],
}

const quiz2: ChapterQuiz = {
  chapterId: 2, title: 'The Earth as a Globe — 1 (Movements)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What is the exact shape of the Earth called?', options: [{ label: 'A', text: 'Perfect sphere' }, { label: 'B', text: 'Oblate spheroid' }, { label: 'C', text: 'Ellipse' }, { label: 'D', text: 'Cylinder' }], answer: 'B', reexplanation: 'The Earth is an oblate spheroid — spherical but slightly flattened at the poles and bulging at the Equator. It is not a perfect sphere. The equatorial diameter (12,756 km) is slightly larger than the polar diameter (12,714 km) because of this bulging at the Equator caused by rotation.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which of the following is NOT a proof of the Earth\'s spherical shape?', options: [{ label: 'A', text: 'The circular shadow during lunar eclipse' }, { label: 'B', text: 'Magellan\'s circumnavigation of the Earth' }, { label: 'C', text: 'The Sun rising in the east every day' }, { label: 'D', text: 'The circular horizon seen from the sea' }], answer: 'C', reexplanation: 'The Sun rising in the east every day is an effect of Earth\'s ROTATION — not proof of its spherical shape. The five proofs of Earth\'s spherical shape are: sighting of a ship, circular horizon, Sunrise and Sunset (places see Sun at different times), circumnavigation (Magellan), and circular shadow during lunar eclipse.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What is the Summer Solstice date and what happens on that day?', options: [{ label: 'A', text: '22nd December — Sun\'s rays fall on Tropic of Capricorn' }, { label: 'B', text: '21st March — equal days and nights everywhere' }, { label: 'C', text: '21st June — Sun\'s rays fall on Tropic of Cancer; longest day in Northern Hemisphere' }, { label: 'D', text: '23rd September — equal days and nights everywhere' }], answer: 'C', reexplanation: '21st June is the Summer Solstice. On this day: the Sun\'s rays fall vertically on the Tropic of Cancer; the North Pole is tilted towards the Sun; it is summer in the Northern Hemisphere; the longest day and shortest night occur in the Northern Hemisphere. The conditions are reversed in the Southern Hemisphere.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What is a leap year?', options: [{ label: 'A', text: 'A year with 365 days, occurring every 4 years' }, { label: 'B', text: 'A year with 366 days, occurring every 4 years, with February having 29 days' }, { label: 'C', text: 'A year with 367 days, occurring every 100 years' }, { label: 'D', text: 'A year that starts on a Monday' }], answer: 'B', reexplanation: 'A leap year has 366 days and occurs every 4 years. The Earth\'s orbital period is 365 days AND 6 hours — not exactly 365. Every 4 years, the extra 6 hours accumulate to make a full day (6 × 4 = 24 hours). This extra day is added to February, which has 29 days in a leap year instead of 28.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What are the two causes of the phenomenon of seasons?', options: [{ label: 'A', text: 'Rotation of Earth and distance from the Sun' }, { label: 'B', text: 'Revolution of Earth and the inclination of Earth\'s axis at 66½° to its orbital plane' }, { label: 'C', text: 'The Moon\'s gravity and Earth\'s rotation' }, { label: 'D', text: 'Rotation of Earth and the Moon\'s phases' }], answer: 'B', reexplanation: 'Seasons are caused by two factors: (1) The revolution of the Earth around the Sun, and (2) The inclination of the Earth\'s axis at 66½° to the plane of its orbit, which constantly points in the same direction. If the axis were not inclined, there would be no seasons — all places would receive the same amount of sunlight throughout the year.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the point in Earth\'s orbit when it is farthest from the Sun called?', answer: 'Aphelion', reexplanation: 'Aphelion is the point when Earth is farthest from the Sun — at 152 million km. The point when Earth is nearest to the Sun is called Perihelion — at 147.3 million km. The Earth\'s orbit is elliptical, not circular, which is why this distance varies throughout the year.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the circle that separates the dark half of the Earth from the lit half called?', answer: 'Circle of illumination', reexplanation: 'The circle of illumination is the imaginary circle that separates the dark half (night) of the Earth from the lit half (day). As the Earth rotates, each place passes through this circle twice — once from day to night (dusk) and once from night to day (dawn).' },
    { id: 8, type: 'single_word', marks: 1, question: 'What is Ferdinand Magellan famous for in the context of proving Earth\'s shape?', answer: 'He was the first to circumnavigate the Earth', reexplanation: 'Ferdinand Magellan was the first person to circumnavigate the Earth — to sail all the way around it in one continuous journey without encountering a sharp edge. This proved that the Earth is round, because a flat Earth would have had an edge that ships would fall off.' },
    { id: 9, type: 'single_word', marks: 1, question: 'On which date is the Autumnal Equinox, when days and nights are equal?', answer: '23rd September', reexplanation: 'The Autumnal Equinox occurs on 23rd September. On this day, the Sun\'s rays fall vertically on the Equator, and all places on Earth have equal days and nights. In the Northern Hemisphere it is autumn; in the Southern Hemisphere it is spring. The Spring Equinox is on 21st March.' },
    { id: 10, type: 'single_word', marks: 1, question: 'In which direction does the Earth rotate on its axis?', answer: 'West to East', reexplanation: 'The Earth rotates from west to east on its axis — which is why the Sun appears to rise in the east and set in the west. This rotation takes 23 hours, 56 minutes and 4 seconds — approximately 24 hours, which gives us the length of one day.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "rotation" in a sentence explaining why we have day and night.', answer: 'The Earth\'s rotation on its axis means half of the Earth faces the Sun (experiencing day) while the other half is in darkness (experiencing night) at any given time.', hint: 'Rotation is the spinning of the Earth on its own axis, completing one full spin in 24 hours.', reexplanation: 'Rotation is the spinning of the Earth on its own axis from west to east. Because of rotation, half the Earth faces the Sun (day) and half faces away (night). As the Earth rotates, day and night alternate for every place on Earth approximately every 12 hours.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "revolution" in a sentence about seasons.', answer: 'The Earth\'s revolution around the Sun, combined with the tilt of its axis, causes the change of seasons — summer, autumn, winter and spring.', hint: 'Revolution is the Earth\'s motion around the Sun, completed in 365 days 6 hours.', reexplanation: 'Revolution is the Earth moving in its orbit around the Sun. One revolution takes 365 days and 6 hours. Combined with the inclination of Earth\'s axis at 66½°, it creates the four seasons — as different parts of Earth receive more or less direct sunlight at different points in the orbit.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "inclined" in a sentence about the Earth\'s axis and seasons.', answer: 'The Earth\'s axis is inclined at 66½° to the plane of its orbit, and this tilt — which always points in the same direction — is what causes the seasons.', hint: 'Inclined means tilted at an angle, not straight up and down.', reexplanation: 'The Earth\'s axis is not straight up — it is inclined (tilted) at 66½° to its orbital plane. This tilt means that as the Earth orbits the Sun, different hemispheres receive different amounts of sunlight at different times of year — creating the seasons. If the axis were not inclined, there would be no seasons.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "solstice" in a sentence about the longest day.', answer: 'The Summer Solstice on 21st June is the day with the longest day and shortest night in the Northern Hemisphere, when the Sun\'s rays fall directly on the Tropic of Cancer.', hint: 'A solstice is when the Sun reaches its northernmost or southernmost point — causing the longest or shortest day of the year.', reexplanation: 'Solstice means when the Sun appears to be at its extreme north or south position. Summer Solstice (21 June) gives the Northern Hemisphere its longest day and shortest night. Winter Solstice (22 December) gives the Northern Hemisphere its shortest day and longest night.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "equinox" in a sentence about when days and nights are equal.', answer: 'On the equinoxes — 21st March (Spring) and 23rd September (Autumn) — the Sun\'s rays fall on the Equator and every place on Earth has equal days and nights of 12 hours each.', hint: 'Equinox literally means "equal night" — when day and night are the same length everywhere.', reexplanation: 'Equinox occurs twice a year — on 21 March (Spring/Vernal Equinox) and 23 September (Autumnal Equinox). On these days, the Sun\'s rays fall perpendicularly on the Equator, so both hemispheres receive equal amounts of sunlight. Every place on Earth has 12 hours of day and 12 hours of night.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Explain the difference between rotation and revolution. What causes each movement, how long does each take, and what are the effects of each? Give at least two effects for each.', answer: 'The Earth has two main movements — rotation and revolution. Rotation is the spinning of the Earth on its own axis from west to east. It is completed in one day — approximately 24 hours (more precisely 23 hours, 56 minutes and 4 seconds). The effects of rotation are: (1) Day and Night — half the Earth faces the Sun (day) while the other half is in darkness (night), separated by the circle of illumination; (2) The apparent movement of the Sun, Moon and stars from east to west; (3) The concept of direction based on sunrise (east) and sunset (west); (4) The bulging of the Earth at the Equator and flattening at the poles; (5) Tides twice a day. Revolution is the movement of the Earth in its orbit around the Sun. It is completed in one year — 365 days 6 hours. The Earth\'s orbit is elliptical. The effects of revolution are: (1) Change of seasons — summer, autumn, winter, spring — caused by revolution combined with the 66½° inclination of Earth\'s axis; (2) Variation in the length of days and nights — on 21 June the Northern Hemisphere has its longest day; on 22 December its shortest day; (3) Apparent migration of the Sun between the Tropics. The key difference: Rotation → Day and Night. Revolution → Seasons.', hint: 'Cover each movement: what it is, how long it takes, and at least two effects. Use specific dates and facts.', reexplanation: 'Structure clearly: Rotation (spinning on axis, west to east, 24 hours) → effects: day/night, apparent E-W movement of Sun/stars, direction, tidal effects, equatorial bulge. Revolution (orbiting Sun, elliptical path, 365d 6h) → effects: seasons (combined with axial tilt), variation in day/night length, apparent migration of Sun between Tropics. Key distinction: rotation = daily cycle; revolution = annual cycle.' },
  ],
}

const quiz3: ChapterQuiz = {
  chapterId: 3, title: 'The Earth as a Globe — 2 (Imaginary Lines)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'How many parallels of latitude are there including the Equator?', options: [{ label: 'A', text: '90' }, { label: 'B', text: '180' }, { label: 'C', text: '181' }, { label: 'D', text: '360' }], answer: 'C', reexplanation: 'There are 181 parallels of latitude including the Equator. These go from 90°N (North Pole) to 90°S (South Pole) — that is 90 north + 90 south + 1 Equator = 181. There are 360 meridians of longitude, not 360 latitudes.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What is the Indian Standard Meridian and through which city does it pass?', options: [{ label: 'A', text: '82.5°E through New Delhi' }, { label: 'B', text: '77°E through Mumbai' }, { label: 'C', text: '82.5°E through Prayagraj (Allahabad)' }, { label: 'D', text: '90°E through Kolkata' }], answer: 'C', reexplanation: 'In India, 82.5°E passing through Prayagraj (Allahabad) is considered the Standard Meridian. When it is noon on this longitude, the time is taken as noon for the whole country — this is Indian Standard Time (IST). Bangladesh is half an hour ahead of IST; Pakistan is half an hour behind.' },
    { id: 3, type: 'mcq', marks: 1, question: 'If 1° longitude = 4 minutes, what is the time difference for a place at 75°E when it is noon at Greenwich (0°)?', options: [{ label: 'A', text: '4 hours 50 minutes ahead' }, { label: 'B', text: '5 hours ahead' }, { label: 'C', text: '5 hours behind' }, { label: 'D', text: '4 hours behind' }], answer: 'B', reexplanation: '75 × 4 = 300 minutes = 5 hours. Since 75°E is east of Greenwich, the time is 5 hours AHEAD. So if it is noon (12:00) at Greenwich, the time at 75°E is 12:00 + 5:00 = 17:00 (5 pm). East = ahead; West = behind.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What is the International Date Line?', options: [{ label: 'A', text: 'The Equator, at 0° latitude' }, { label: 'B', text: 'The Prime Meridian at 0° longitude' }, { label: 'C', text: 'The line at 180° longitude where a day is gained or lost' }, { label: 'D', text: 'The Tropic of Cancer at 23.5°N' }], answer: 'C', reexplanation: 'The International Date Line (IDL) coincides with the 180° longitude. It is the line at which a day is gained or lost when crossing it. It follows a zig-zag course to avoid splitting countries. Cross eastward → gain a day; cross westward → lose a day.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Each meridian of longitude is described as a:', options: [{ label: 'A', text: 'Full circle' }, { label: 'B', text: 'Semicircle' }, { label: 'C', text: 'Quarter circle' }, { label: 'D', text: 'Straight line' }], answer: 'B', reexplanation: 'Each meridian of longitude is a semicircle — it runs from the North Pole to the South Pole. All meridians are of equal length. In contrast, each parallel of latitude is a full circle, and they decrease in size from the Equator to the poles.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the latitude of the Tropic of Cancer?', answer: '23.5°N', reexplanation: 'The Tropic of Cancer is at 23.5°N. It is the northernmost point where the Sun shines directly overhead — on 21st June (Summer Solstice). Its southern counterpart is the Tropic of Capricorn at 23.5°S, where the Sun shines directly overhead on 22nd December.' },
    { id: 7, type: 'single_word', marks: 1, question: 'How many meridians of longitude are there?', answer: '360', reexplanation: 'There are 360 meridians of longitude. They range from 0° (Prime Meridian at Greenwich) to 180° east and west. All meridians are semicircles of equal length running from the North Pole to the South Pole.' },
    { id: 8, type: 'single_word', marks: 1, question: 'If it is noon at 0° (Greenwich), what is the time at a place on the 15°E longitude?', answer: '1:00 pm (13:00)', reexplanation: '1° longitude = 4 minutes. 15° × 4 = 60 minutes = 1 hour. Since 15°E is east of Greenwich, the time is 1 hour ahead of Greenwich. So if it is noon (12:00) at Greenwich, the time at 15°E is 1:00 pm.' },
    { id: 9, type: 'single_word', marks: 1, question: 'How many time zones does the world have?', answer: '24', reexplanation: 'The world is divided into 24 time zones of one hour each. Each time zone corresponds to 15° of longitude. This is because the Earth rotates 360° in 24 hours, so 360 ÷ 24 = 15° per hour.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What is the network of latitude and longitude lines on a map or globe called?', answer: 'Grid system / Geographic grid / Geographical grid', reexplanation: 'A network of horizontal and vertical lines of latitude and longitude drawn on a map or globe is known as the grid system or geographical grid. It is used to find out the exact location of places on the Earth by giving every place a unique pair of coordinates.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "meridian" in a sentence explaining what it is.', answer: 'A meridian is a semicircle of longitude running from the North Pole to the South Pole — all meridians are of equal length and meet at both poles.', hint: 'A meridian is each line of longitude — a semicircle from pole to pole.', reexplanation: 'A meridian is a line of longitude — each one is a semicircle from the North Pole to the South Pole. All meridians are of equal length. They are not parallel — they converge at the poles and are widest apart at the Equator (111 km per degree).' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the phrase "local time" in a sentence about time differences.', answer: 'Every place has its own local time based on the position of the Sun overhead — which is why places on different meridians have different local times.', hint: 'Local time is the time calculated based on the Sun\'s position at a specific meridian.', reexplanation: 'Local time is the time of a place calculated based on the mid-day Sun at that meridian. All places on the same meridian have the same local time. But places on different meridians have different local times — which is why Standard Time was introduced to avoid confusion within countries.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "converge" in a sentence about meridians of longitude.', answer: 'Meridians of longitude converge — come closer together — as they approach the poles, which is why the distance between them is widest at the Equator and almost zero at the poles.', hint: 'Converge means to come closer together towards a point.', reexplanation: 'Unlike parallels of latitude which are always the same distance apart, meridians of longitude converge at the poles. At the Equator, a giraffe must walk 111 km to cross one degree of longitude. Near the poles, a penguin need only jump!' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "zig-zag" in a sentence about the International Date Line.', answer: 'The International Date Line follows a zig-zag course instead of a straight line, to avoid splitting countries that span the 180° longitude into different dates.', hint: 'The IDL follows a zig-zag path because a straight line would cut through some island countries.', reexplanation: 'The IDL is at 180° longitude but does not follow this line exactly. It bends around island nations in the Pacific so that the same country does not have two different dates. A straight IDL would split some island groups in the Pacific Ocean.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "calculate" in a sentence about how longitude helps us find time.', answer: 'By knowing that 1° of longitude equals 4 minutes of time, we can calculate the local time of any place on Earth if we know its longitude and the time at Greenwich.', hint: 'Longitude helps calculate time differences because the Earth rotates 1° every 4 minutes.', reexplanation: 'The relationship between longitude and time: the Earth rotates 360° in 24 hours → 1 hour = 15° → 4 minutes = 1°. If you know the longitude of a place and the time at Greenwich, you can calculate its local time precisely. East of Greenwich = add time; West = subtract time.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Explain the difference between latitudes and longitudes. What are their key characteristics? What are the five important lines of latitude and what is the significance of each?', answer: 'Latitudes and longitudes are two sets of imaginary lines that form the geographical grid — used to locate any point on Earth precisely. Latitudes are horizontal lines that measure the angular distance of a place north or south of the Equator. There are 181 parallels of latitude. Each parallel is a full circle. The circles become smaller towards the poles. The distance between any two parallels is always equal. The most important latitude is the Equator (0°), which divides the Earth into the Northern and Southern Hemispheres. The five important lines of latitude are: (1) Equator (0°) — divides Earth into Northern and Southern Hemispheres — the longest and most important latitude; (2) Tropic of Cancer (23.5°N) — northernmost point where Sun shines directly overhead on 21 June; (3) Tropic of Capricorn (23.5°S) — southernmost point where Sun shines directly overhead on 22 December; (4) Arctic Circle (66.5°N) — northern boundary of the Frigid Zone; (5) Antarctic Circle (66.5°S) — southern boundary of the Frigid Zone. Longitudes are vertical semicircles measuring the angular distance east or west of the Prime Meridian. There are 360 meridians of longitude. All meridians are equal in length. Meridians converge at the poles. They are widest apart at the Equator (111 km). The key difference: latitude lines are parallel circles getting smaller toward poles; longitude lines are semicircles meeting at the poles.', hint: 'Compare latitudes and longitudes (circles vs semicircles, 181 vs 360). Then name and explain each of the five important latitudes with their degree value and significance.', reexplanation: 'Cover: Latitudes (181 parallels, full circles, parallel, equal spacing, decrease in size toward poles). Longitudes (360 meridians, semicircles, converge at poles, equal length, not equal spacing). Five important latitudes: Equator (0°, divides hemispheres), Tropic of Cancer (23.5°N, Sun overhead June 21), Tropic of Capricorn (23.5°S, Sun overhead Dec 22), Arctic Circle (66.5°N), Antarctic Circle (66.5°S).' },
  ],
}

const quiz4: ChapterQuiz = {
  chapterId: 4, title: 'Landforms', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Which type of mountain is formed by compression of the Earth\'s crust?', options: [{ label: 'A', text: 'Block mountain' }, { label: 'B', text: 'Volcanic mountain' }, { label: 'C', text: 'Fold mountain' }, { label: 'D', text: 'Residual mountain' }], answer: 'C', reexplanation: 'Fold mountains are formed when layers of the Earth\'s crust are folded by compression — like pushing two sides of a tablecloth together to create folds. Examples include young fold mountains (Himalayas, Andes, Alps, Rockies) and old fold mountains (Aravallis, Appalachians, Urals).' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which of the following is an example of a Block Mountain?', options: [{ label: 'A', text: 'Himalayas' }, { label: 'B', text: 'Nilgiri Hills' }, { label: 'C', text: 'Satpura and Vindhya mountains' }, { label: 'D', text: 'Mt. Fuji' }], answer: 'C', reexplanation: 'The Satpura and Vindhya mountains in central-western India are examples of block mountains — formed by faulting. The Rhine Valley and Vosges Mountains in Europe are also block mountains. Himalayas are fold mountains; Nilgiri Hills are residual mountains; Mt. Fuji is volcanic.' },
    { id: 3, type: 'mcq', marks: 1, question: 'Which type of plateau is described as the "Roof of the World"?', options: [{ label: 'A', text: 'Dissected plateau' }, { label: 'B', text: 'Piedmont plateau' }, { label: 'C', text: 'Continental plateau' }, { label: 'D', text: 'Intermontane plateau — Plateau of Tibet' }], answer: 'D', reexplanation: 'The Plateau of Tibet is an intermontane plateau — enclosed by mountains (the Himalayas and the Kunlun mountains). It is called the "Roof of the World" because it is the highest and largest plateau in the world. It is an example of an intermontane plateau.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Which type of plain is the Gangetic Plain of India?', options: [{ label: 'A', text: 'Coastal plain' }, { label: 'B', text: 'Glacial plain' }, { label: 'C', text: 'Lacustrine or lake plain' }, { label: 'D', text: 'Alluvial plain' }], answer: 'D', reexplanation: 'The Gangetic Plains of India are alluvial plains — formed by the deposition of alluvium (sand, silt and clay) by rivers. Most plains are formed by rivers. The deposit comprising sand, silt and clay is called alluvium. These plains are among the most fertile and densely populated in the world.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What is the study of the Earth\'s relief features called?', options: [{ label: 'A', text: 'Geology' }, { label: 'B', text: 'Geomorphology' }, { label: 'C', text: 'Geography' }, { label: 'D', text: 'Meteorology' }], answer: 'B', reexplanation: 'Geomorphology is the study of the Earth\'s relief features. The word comes from Greek: geo (Earth) + morphe (shape) + logos (study). Geology is the study of rocks and Earth\'s structure; Meteorology is the study of weather and climate.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the raised block of land between two fault lines in a block mountain called?', answer: 'Horst', reexplanation: 'A horst is the raised block of land between two fault lines that forms a block mountain. The sunken land on either side is called a graben. When tectonic plates move apart, cracks (faults) form, and land between faults can be pushed up (horst) while surrounding land sinks (graben).' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the deposit of sand, silt and clay left by rivers on plains called?', answer: 'Alluvium', reexplanation: 'Alluvium is the deposit comprising sand, silt and clay that rivers leave behind when they slow down and drop their load of sediment. Plains formed by this process are called alluvial plains. The Gangetic Plains in India are formed from alluvium deposited by the Ganga and its tributaries.' },
    { id: 8, type: 'single_word', marks: 1, question: 'Name India\'s only active volcano, located in the Andaman and Nicobar Islands.', answer: 'Barren Island', reexplanation: 'Barren Island in the Andaman and Nicobar Islands is India\'s only active volcano — a volcanic mountain. Other examples of volcanic mountains include Mt. Fuji in Japan and Mt. Mayo in the Philippines. Volcanic mountains are formed by lava, ash, cinder and dust accumulating around a vent.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What type of plateau is the Peninsular Plateau of India, divided by rivers like Godavari and Krishna?', answer: 'Dissected plateau', reexplanation: 'The Peninsular Plateau of India is a dissected plateau — a large plateau divided into smaller units by deep cut valleys formed by rivers flowing through it. Major rivers like Godavari, Krishna and Kaveri have dissected it into a hills-and-valley landscape. Meseta Central in Spain is another example.' },
    { id: 10, type: 'single_word', marks: 1, question: 'How much of the Earth\'s surface do plateaus cover?', answer: '33%', reexplanation: 'Plateaus cover about 33% of the Earth\'s surface but support only 9% of the world\'s population. Despite covering a third of Earth\'s surface, plateaus are less densely populated than plains because they can be rugged, rocky, and difficult to farm — though they are rich in minerals.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "erosion" in a sentence about residual mountains.', answer: 'Residual mountains are formed when erosion by rivers and natural agents wears away the surrounding land, leaving isolated highlands standing above the general level.', hint: 'Erosion is the wearing away of land by natural forces like rivers, wind and glaciers.', reexplanation: 'Erosion is the process by which natural forces (rivers, wind, glaciers) wear away rock and soil. Residual mountains are what is left behind when erosion removes the surrounding land — the harder rock remains as a residual mountain. Examples: Nilgiri Hills, Aravallis.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "compression" in a sentence about how fold mountains form.', answer: 'Fold mountains are formed when two tectonic plates collide and the compression between them pushes up the layers of rock into folds — creating mountain ranges like the Himalayas.', hint: 'Compression means being pressed or squeezed from both sides.', reexplanation: 'Compression is the force of being pushed from two sides. In geology, when two tectonic plates collide, the crust between them is compressed — and rather than breaking, it folds upward into mountain ranges. This is how fold mountains like the Himalayas, Alps, and Andes formed.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "tableland" in a sentence about plateaus.', answer: 'A plateau is also called a tableland because, like a table, it has a flat top surface that rises sharply above the surrounding lowlands.', hint: 'Tableland is another name for plateau — think of a table with a flat top and steep sides.', reexplanation: 'Tableland is another word for plateau. The analogy to a table is perfect — a table has a flat top supported by legs that drop steeply to the ground. Similarly, a plateau has a broad, flat top that rises sharply above the surrounding lower land.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the word "fertile" in a sentence about why plains are densely populated.', answer: 'Plains are the most densely populated regions on Earth because their flat land and fertile soil make them ideal for farming, building roads, and developing cities.', hint: 'Fertile means capable of producing abundant crops — rich in nutrients.', reexplanation: 'Fertile soil is soil that is rich in nutrients and capable of producing abundant crops. Plains — especially alluvial plains formed by river deposits — have very fertile soil. This is why most of the world\'s great civilisations developed on plains: the Gangetic Plain, the Nile Valley, the Mississippi lowlands.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the phrase "endogenic forces" in a sentence about how mountains form.', answer: 'Endogenic forces — internal forces originating deep inside the Earth — slowly build mountains and continents over millions of years or cause sudden events like earthquakes and volcanic eruptions.', hint: 'Endogenic means originating from inside the Earth.', reexplanation: 'Endogenic forces come from inside the Earth. They can be slow (building mountains and continents over millions of years) or sudden (earthquakes, volcanic eruptions, landslides). The word comes from the Greek: endo (within) + genesis (origin). Contrast with exogenic forces which come from outside.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Describe the four types of mountains. For each type, explain how it is formed and give at least two examples.', answer: 'There are four types of mountains according to their mode of formation. First, Fold Mountains: these are formed when the layers of the Earth\'s crust are compressed and folded. Old fold mountains (250 million years old) have rounded peaks, gentle slopes and lower heights — examples are the Aravallis in India, Appalachians in North America, and the Urals in Russia. Young fold mountains (30-50 million years old) have pointed peaks, steep slopes and greater heights — examples are the Himalayas in Asia, Andes in South America, Rockies in North America, and Alps in Europe. Second, Block Mountains: these are formed when tectonic plates move apart, causing faults in the Earth\'s surface. The land between two faults is pushed up (called a horst) while the land on either side sinks (called a graben). They are often steep-sided and flat-topped. Examples: Rhine Valley and Vosges mountains in Europe; Satpura and Vindhya mountains in India. Third, Residual Mountains: these are formed when rivers and natural agents erode the surrounding land, leaving isolated areas of harder rock standing above the general level. Examples: Nilgiri and Rajmahal Hills in India; Half Dome at Yosemite, USA; Aravallis in Rajasthan. Fourth, Volcanic Mountains: these are formed when molten lava, ash, cinder and dust from deep inside the Earth come out through cracks called vents and accumulate around them, building up a mountain. Examples: Mt. Fuji in Japan; Mt. Mayo in the Philippines; Barren Island in India (India\'s only active volcano).', hint: 'Go through each type: Fold (compression, old/young examples), Block (faulting, horst/graben, examples), Residual (erosion, examples), Volcanic (lava/ash/vent, examples).', reexplanation: 'Cover all four types clearly: Fold (compression, anticlines and synclines, old: Aravallis/Urals, young: Himalayas/Alps/Andes/Rockies), Block (faulting, horst pushed up between grabens, Rhine Valley, Satpura-Vindhya), Residual (erosion leaves hard rock behind, Nilgiri, Aravallis, Half Dome), Volcanic (lava and ash build up around vent, Mt. Fuji, Barren Island).' },
  ],
}

const quiz5: ChapterQuiz = {
  chapterId: 5, title: 'Representation of Geographical Features', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Which of the following is the correct definition of a map?', options: [{ label: 'A', text: 'A three-dimensional model of the Earth' }, { label: 'B', text: 'A rough drawing not drawn to scale' }, { label: 'C', text: 'A visual representation of the Earth or part of it, drawn to a scale on a flat surface' }, { label: 'D', text: 'A drawing showing the top view of a building' }], answer: 'C', reexplanation: 'A map is a visual representation of the Earth or a part of the Earth, drawn to a scale, on a flat surface. A globe is the 3D model. A sketch is a rough drawing not to scale. A plan is a to-scale top view of a structure like a building.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which type of map shows details of properties, buildings, and is useful for land ownership records?', options: [{ label: 'A', text: 'Topographical map' }, { label: 'B', text: 'Cadastral map' }, { label: 'C', text: 'Political map' }, { label: 'D', text: 'Wall map' }], answer: 'B', reexplanation: 'Cadastral maps are large scale maps that give details of properties and buildings. They are useful for city survey, local administration, recording land ownership and city plans. Topographical maps show both natural and man-made features of a landscape and are used for military purposes.' },
    { id: 3, type: 'mcq', marks: 1, question: 'In a physical map, what colour is used to show mountains?', options: [{ label: 'A', text: 'Green' }, { label: 'B', text: 'Blue' }, { label: 'C', text: 'Yellow' }, { label: 'D', text: 'Brown' }], answer: 'D', reexplanation: 'On physical maps: mountains are shown in brown, deserts in yellow, plains in green, and water bodies in blue. These colour conventions are used universally so that map readers anywhere in the world can understand them.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What does a Representative Fraction of 1:10,000 mean?', options: [{ label: 'A', text: '10,000 cm on the map = 1 cm on the ground' }, { label: 'B', text: '1 cm on the map = 10,000 cm on the ground' }, { label: 'C', text: '1 km on the map = 10,000 km on the ground' }, { label: 'D', text: 'The map is 10,000 times smaller than the ground' }], answer: 'B', reexplanation: 'A Representative Fraction (RF) of 1:10,000 means 1 unit on the map corresponds to 10,000 units on the ground. The numerator is always 1. So if the units are centimetres, 1 cm on the map = 10,000 cm (100 metres) on the ground.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Which of the following is an advantage of a Globe over a Map?', options: [{ label: 'A', text: 'A globe can show large amounts of detail' }, { label: 'B', text: 'A globe can show the movements of the Earth' }, { label: 'C', text: 'A globe has a legend or key' }, { label: 'D', text: 'A globe is easier to carry around' }], answer: 'B', reexplanation: 'A globe can demonstrate the movements of the Earth — rotation and revolution — because it is 3D and spherical. A map cannot show Earth\'s movements. However, a globe cannot show much detail and cannot have a legend. A map can show a lot of detail of a small area and always has a legend/key.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the science of map making called?', answer: 'Cartography', reexplanation: 'Cartography is the science of map making. The person who makes maps is called a cartographer. The art of making maps is very old — Claudius Ptolemy, the famous Roman Geographer, drew the map of the world in 150 CE.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What are the five elements of a map?', answer: 'Title, Direction, Scale, Legend/Key, Grid System', reexplanation: 'The five basic elements of every map are: (1) Title — introduces the topic; (2) Direction — shows North/South/East/West; (3) Scale — helps measure distances; (4) Legend or Key — explains the symbols; (5) Grid System — helps locate places.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What degree does East correspond to on a compass?', answer: '90°', reexplanation: 'On a compass, the four cardinal directions correspond to: North = 0°, East = 90°, South = 180°, West = 270°. These are the four main cardinal directions from which intermediate directions (NE, SE, SW, NW) are derived.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What is a collection of maps in book form called?', answer: 'Atlas', reexplanation: 'A collection of maps is called an Atlas. Atlas maps are drawn to a smaller scale than wall maps and are very convenient to carry in book form. They are considered suitable for educational purposes — which is why you find them in schools and libraries.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What type of map deals with specific topics like population distribution or annual rainfall?', answer: 'Thematic map / Subject Specific map', reexplanation: 'Thematic maps (also called subject specific maps) deal with a specific topic or theme: distribution of population, crops, minerals, industries, tourist destinations, weather conditions, annual rainfall, etc. They are different from physical maps (showing landforms) and political maps (showing boundaries).' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "scale" in a sentence explaining why maps need a scale.', answer: 'Every map needs a scale because without it you cannot calculate the actual distance between two places from the distance shown on the map.', hint: 'Scale is the ratio of the distance on the map to the actual distance on the ground.', reexplanation: 'Map scale is the ratio of map distance to actual ground distance. Without a scale, a map would just be a picture — you could not measure or calculate real distances from it. The three types of scale are: statement (verbal), graphical (linear), and representative fraction.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "conventional" in a sentence about map symbols.', answer: 'Maps use conventional signs and symbols — like a temple icon for a temple or a blue wavy line for a river — so that anyone who reads maps can understand them without needing a different explanation in every language.', hint: 'Conventional means agreed upon and standardised — understood by everyone who uses maps.', reexplanation: 'Conventional signs are standard symbols agreed upon by cartographers globally. They show features on a map (roads, rivers, temples, settlements) using standardised symbols that are understood everywhere. Without conventional signs, a map would need to draw actual shapes of all features — which would be impossible at map scale.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "distortion" in a sentence about maps compared to globes.', answer: 'Unlike a globe which shows the true shapes and sizes of continents, a map can have distortion because it flattens the curved surface of the Earth onto a flat sheet of paper.', hint: 'Distortion means a change in the true shape or size of something.', reexplanation: 'When you flatten a curved surface (like a globe) onto a flat surface (like a map), something always has to be distorted. Continents may appear larger or smaller, shapes may be stretched. Greenland appears enormous on some world maps but is much smaller in reality. Globes have no such distortion.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "large scale map" in a sentence about topographical maps.', answer: 'A topographical map is a large scale map — it shows a smaller area in much greater detail, including both natural features like hills and rivers and man-made features like roads and settlements.', hint: 'A large scale map shows a small area with a lot of detail.', reexplanation: 'Large scale maps show small areas in great detail. Topographical maps are large scale and show both natural features (hills, valleys, rivers) and man-made features (roads, settlements, wells). They are prepared after careful surveys of land and are used for military purposes. In India, Survey of India prepares topographical maps.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "intermediate" in a sentence about compass directions.', answer: 'Besides the four cardinal directions, there are four intermediate directions — Northeast, Southeast, Southwest and Northwest — which are found between the main directions.', hint: 'Intermediate means between two things — the intermediate directions are between the four main cardinal directions.', reexplanation: 'The four intermediate directions are: NE (between North and East), SE (between South and East), SW (between South and West), NW (between North and West). Together with the four cardinal directions (N, S, E, W), they give us the eight cardinal points of a compass.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Explain the differences between a Map and a Globe. Why are both useful? What are the five elements of a map and why is each element important?', answer: 'A map and a globe are both ways of representing the Earth, but they have important differences. A map is flat and can have distortions, but it can show a lot of detail of a small area and always has a key or legend. It is portable, can be printed, and is easy to use for navigation and measurement. A globe is three-dimensional and is more realistic — it shows the correct shapes and sizes of continents and oceans without distortion. It can represent the actual shape of the Earth and can even demonstrate the Earth\'s movements. However, a globe cannot show much detail and does not have a key or legend. Both are useful: maps for detailed local navigation and reference, globes for understanding the Earth\'s true shape and position in space. The five elements of a map are: (1) Title — introduces the topic of the map, so the reader knows what area and subject is being shown; (2) Direction — usually shown as an arrow pointing North — helps the reader find their way and understand spatial relationships; (3) Scale — the ratio of map distance to actual ground distance — essential for measuring real distances from the map; (4) Legend or Key — explains what each symbol and colour on the map represents — without this, the map\'s symbols would be meaningless; (5) Grid System — the network of lines that helps locate places precisely using coordinates.', hint: 'Compare map vs globe (flat vs 3D, distortion vs accurate, detail vs shape). Then explain each of the five elements and why each matters.', reexplanation: 'Map vs Globe: Map (flat, distortion, lots of detail, portable, has legend) vs Globe (3D, accurate, limited detail, can show Earth movements, no legend). Five elements — for each explain: Title (tells topic), Direction (N arrow helps orientation), Scale (converts map distance to real distance), Legend/Key (decodes symbols), Grid (precise location through coordinates).' },
  ],
}

const quiz6: ChapterQuiz = {
  chapterId: 6, title: 'Agriculture in India and World', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Which of the following is a cash crop?', options: [{ label: 'A', text: 'Rice' }, { label: 'B', text: 'Wheat' }, { label: 'C', text: 'Sugarcane' }, { label: 'D', text: 'Maize' }], answer: 'C', reexplanation: 'Sugarcane is a cash crop — grown by farmers only to sell and used as a raw material for the sugar industry. Rice, wheat and maize are food crops — they form a part of the diet of farmers and other people. Tea, cotton and rubber are other examples of cash crops.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What is shifting agriculture also known as?', options: [{ label: 'A', text: 'Commercial farming' }, { label: 'B', text: 'Slash and burn method' }, { label: 'C', text: 'Intensive farming' }, { label: 'D', text: 'Organic farming' }], answer: 'B', reexplanation: 'Shifting agriculture is also known as the slash and burn method — a farmer clears a patch of forest by cutting and burning trees, farms it for a few years until soil fertility drops, then moves to a new patch. It is known as Jhum in Assam, Ponam in Kerala, and Podu in Andhra Pradesh.' },
    { id: 3, type: 'mcq', marks: 1, question: 'Which type of farming involves the cultivation of a single crop on large tracts of land for export?', options: [{ label: 'A', text: 'Subsistence farming' }, { label: 'B', text: 'Organic farming' }, { label: 'C', text: 'Mixed farming' }, { label: 'D', text: 'Plantation farming' }], answer: 'D', reexplanation: 'Plantation farming involves large tracts of land (estates) used for cultivation of a single crop like tea, coffee, cocoa, jute, rubber or spices. It is labour intensive with huge capital investment. It caters to the export market and helps earn foreign exchange. In India it is practised in the hills of South and North-East India.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What was the main achievement of the Green Revolution in India?', options: [{ label: 'A', text: 'Turning India from food self-sufficiency to food exports' }, { label: 'B', text: 'Transforming India from food scarcity to food self-sufficiency' }, { label: 'C', text: 'Introducing organic farming to India' }, { label: 'D', text: 'Reducing agricultural employment' }], answer: 'B', reexplanation: 'The Green Revolution transformed India from food scarcity to food self-sufficiency. It involved the use of High Yielding Variety (HYV) seeds, mechanization, chemical fertilizers, pesticides, and large scale irrigation — particularly for wheat. It also created more employment in the agricultural sector and increased rural prosperity.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Which type of farming simultaneously raises crops AND animals?', options: [{ label: 'A', text: 'Extensive farming' }, { label: 'B', text: 'Monoculture' }, { label: 'C', text: 'Mixed farming' }, { label: 'D', text: 'Plantation farming' }], answer: 'C', reexplanation: 'Mixed farming involves the cultivation of crops and raising of animals simultaneously. Multiple crops with varying maturity periods are sown at the same time. If agriculture fails due to climate, farmers can rely on livestock for income. The two most extensive regions of mixed farming are Eurasia and the United States.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What are the three cropping seasons of India?', answer: 'Kharif, Rabi and Zaid', reexplanation: 'India has three cropping seasons: Kharif (monsoon season, June to September), Rabi (winter season, October to March), and Zaid (summer season, March to June). Different crops are grown in each season depending on temperature, rainfall, and soil conditions.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the name for shifting agriculture as practised in Assam?', answer: 'Jhum', reexplanation: 'Shifting agriculture is called Jhum in Assam. It is known by different names across India: Ponam in Kerala, Podu in Andhra Pradesh, Koman in Odisha, Khil in the Himalayan region, and Masha, Bewar or Hera in Madhya Pradesh.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What does the word "agriculture" mean — give the Latin root words?', answer: 'Ager (land) and culture (cultivation)', reexplanation: 'Agriculture comes from two Latin words: ager meaning land and culture meaning cultivation. So agriculture literally means "cultivation of land." People first began to farm about 10,000 years before the present in South-West Asia.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What are High Yielding Variety seeds used in commercial farming called?', answer: 'HYV seeds', reexplanation: 'HYV stands for High Yielding Variety seeds — seeds specially bred to produce much larger quantities of crop per plant than traditional varieties. They are a key feature of commercial farming and were central to the Green Revolution in India. They are typically used with chemical fertilizers and irrigation.' },
    { id: 10, type: 'single_word', marks: 1, question: 'Name the world\'s most expensive spice, produced in Kashmir.', answer: 'Saffron', reexplanation: 'One of Kashmir\'s key industries is the production of saffron — the world\'s most expensive spice. It is used as a dye as well as food flavouring. It is harvested from the Crocus sativus flower and only a tiny amount can be harvested from each flower, making it extremely valuable.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "subsistence" in a sentence about farming in tribal areas of India.', answer: 'In the tribal areas of Assam and the hilly states of north-eastern India, subsistence farming is practised — where families grow just enough food for themselves with little surplus to sell.', hint: 'Subsistence means meeting only basic needs without surplus.', reexplanation: 'Subsistence farming is practised where the farmer owns a small piece of land, farms it with family help, and consumes almost all the produce. There is little or no surplus to sell in the market. It is practised in China, Vietnam, Cambodia, Mexico, Peru, and in tribal areas of India.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "mechanized" in a sentence about commercial farming.', answer: 'Commercial farming requires large farms and mechanized equipment like tractors and combine harvesters to cultivate vast areas efficiently and produce enough crops for sale in the market.', hint: 'Mechanized means using machines instead of manual labour.', reexplanation: 'Commercial farming uses mechanized equipment — tractors, combine harvesters, sprayers — to farm large areas efficiently. It is practised in regions with low population density and large land holdings like Central United States, Canadian prairies, and the Terai region of India.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "monoculture" in a sentence about its disadvantage.', answer: 'Monoculture — growing only one crop year after year on the same land — can lead to a rapid build-up of pests and diseases because there is only one type of plant for them to attack.', hint: 'Monoculture means growing only one type of crop continuously.', reexplanation: 'Monoculture is the agricultural practice of growing only one crop or raising only one type of livestock. The disadvantage is that it leads to rapid build-up of pests and diseases specific to that crop, depletes soil of specific nutrients, and can create an imbalance in the food supply chain.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "organic farming" in a sentence about how it keeps soil healthy.', answer: 'Organic farming keeps soil alive and healthy by using only natural inputs like organic waste, crop residues, and bio-fertilizers — avoiding the harsh chemical fertilizers and pesticides that can damage soil over time.', hint: 'Organic farming uses natural inputs instead of chemicals to maintain soil health.', reexplanation: 'Organic farming aims to keep the soil alive and productive by using: organic wastes (crop, animal and farm wastes), biological materials with beneficial microbes (bio-fertilizers), and legumes for nitrogen self-sufficiency. It avoids synthetic chemicals and tries to work with natural ecosystem processes.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "export" in a sentence about plantation farming.', answer: 'Plantation farming is export-oriented — the tea, coffee, rubber and cocoa grown on large estates are processed and packaged, then sold in international markets to earn foreign exchange for the country.', hint: 'Export means selling goods to other countries.', reexplanation: 'Plantation farming typically caters to the export market. The crops (tea, coffee, rubber, cocoa, spices) are grown on a large scale, processed to high quality standards, and exported to earn foreign exchange. India\'s tea from Assam and Darjeeling, and rubber from Kerala, are important plantation crops that are exported.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Compare and contrast Intensive Farming and Extensive Farming. What are the key characteristics of each, where is each type practised, and what crops are grown? Which type would be more suitable for a densely populated country like India? Explain your answer.', answer: 'Intensive farming and extensive farming are two contrasting types of commercial agriculture, suited to very different conditions. Intensive farming is practised in areas with high population density and limited arable farmland. The farmer tries to get the maximum possible output from a small piece of land. It uses high-yielding variety seeds, green manures, chemical fertilizers, insecticides and pesticides. Water is supplied through irrigation. The farmer raises more than one crop per year. It is widely practised in the irrigated areas of northern plains and coastal plains of India. Extensive farming, on the other hand, is practised in areas with low population density and huge cultivable farmlands. It uses the latest advanced technology and machinery — tractors, combine harvesters — to produce crops in surplus for sale. Farmers specialise in a couple of major commercial crops like rice, wheat or sugarcane. It is practised in the Terai region of sub-Himalayas and north-western India, and in large-scale in the USA, Canada, Argentina and Peru. For a densely populated country like India, Intensive farming is more suitable. India has over 1.4 billion people but limited land — it cannot afford to spread farming thinly over large areas. Every piece of farmland must produce as much as possible. The Green Revolution used the principles of intensive farming (HYV seeds, fertilizers, irrigation) to make India food self-sufficient. Extensive farming requires vast areas of land with few people — which is the opposite of India\'s situation.', hint: 'Compare the two: population density, land area, technology used, crops, regions. Then give a clear answer about which suits India more and why.', reexplanation: 'Intensive farming: high population density, small/limited land, multiple crops per year, HYV seeds, irrigation, fertilizers, northern plains and coastal plains of India. Extensive farming: low population density, vast farmland, machinery, 1-2 major crops, Terai/NW India, USA, Canada, Argentina. For India → intensive is more suitable because: high population density, limited land, need maximum output per unit area, Green Revolution used these principles.' },
  ],
}

const quiz7: ChapterQuiz = {
  chapterId: 7, title: 'North America', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What is North America joined to South America by?', options: [{ label: 'A', text: 'Bering Strait' }, { label: 'B', text: 'Isthmus of Panama' }, { label: 'C', text: 'Gulf of Mexico' }, { label: 'D', text: 'Hudson Bay' }], answer: 'B', reexplanation: 'North America and South America are joined to each other by the Isthmus of Panama — a narrow strip of land. The Bering Strait separates North America from Asia in the northwest. The Pacific Ocean lies to the west, the Atlantic to the east, and the Arctic Ocean to the north of North America.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which is the highest mountain peak in North America?', options: [{ label: 'A', text: 'Mount Elbert' }, { label: 'B', text: 'Mount McKinley (Denali) at 6,190 m' }, { label: 'C', text: 'Death Valley' }, { label: 'D', text: 'Grand Canyon' }], answer: 'B', reexplanation: 'Denali, also known as Mount McKinley, is the highest mountain peak in North America with a summit elevation of 6,190 m above sea level. It is located in Alaska. Mount Elbert is the highest summit of the Rocky Mountains, but is not as high as Denali. Death Valley is the lowest point (86 m below sea level).' },
    { id: 3, type: 'mcq', marks: 1, question: 'Which is the largest freshwater lake in the world, located in North America?', options: [{ label: 'A', text: 'Lake Ontario' }, { label: 'B', text: 'Lake Huron' }, { label: 'C', text: 'Lake Superior' }, { label: 'D', text: 'Lake Michigan' }], answer: 'C', reexplanation: 'Lake Superior is the largest freshwater lake in the world. It is one of the Five Great Lakes of North America — along with Lake Michigan, Lake Huron, Lake Erie, and Lake Ontario. These lakes were formed in the Canadian Shield by glaciers during the Ice Age.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Why is lumbering done in winter in Canada?', options: [{ label: 'A', text: 'Trees grow faster in winter' }, { label: 'B', text: 'The sap stops flowing and frozen ground helps transport logs' }, { label: 'C', text: 'There is more sunlight in winter' }, { label: 'D', text: 'Demand for wood is highest in winter' }], answer: 'B', reexplanation: 'Winter is the ideal season for lumbering in Canada because: the sap of the trees stops flowing (making it easier to cut), and the frozen ground helps in transportation of logs. Another advantage is that farmers are available in winter since farming stops. Swift flowing streams provide cheap hydro-electric power to saw mills.' },
    { id: 5, type: 'mcq', marks: 1, question: 'On which side of a mountain does relief rainfall occur most heavily?', options: [{ label: 'A', text: 'The leeward side' }, { label: 'B', text: 'The windward side' }, { label: 'C', text: 'The top of the mountain' }, { label: 'D', text: 'The rain shadow area' }], answer: 'B', reexplanation: 'In relief rainfall, the windward side — the side facing the moist wind — gets the maximum rainfall. Moist air is forced up the mountain, cools, and condenses into rain. The leeward side receives hardly any rainfall and is called the rain shadow area, because it is in the "shadow" of the mountain.' },
    { id: 6, type: 'single_word', marks: 1, question: 'After whom was the continent of America named in 1507?', answer: 'Amerigo Vespucci', reexplanation: 'The continent of America was named in 1507 after Amerigo Vespucci — an Italian explorer who landed on the mainland of the continent. Christopher Columbus had earlier discovered the Caribbean islands but believed he had reached India — calling the inhabitants "Indians."' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the area of North America approximately?', answer: '24 million sq. km', reexplanation: 'North America has an area of approximately 24 million square kilometres, making it the third largest continent in the world after Asia and Africa. Its greatest length is 7,200 km from Panama to the Arctic Islands, and its greatest width is 4,800 km between British Columbia and Newfoundland.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What is the deepest canyon in North America, carved by the Colorado River?', answer: 'Grand Canyon', reexplanation: 'The Grand Canyon of the Colorado River is above 1,857 m deep and 446 km long, and is famous worldwide for its beauty and majesty. It is located in the Western Cordilleras. The plateaus of the Western Cordilleras are crossed by rivers which have carved out deep valleys with almost vertical sides called gorges or canyons.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What are the seven countries of Central America collectively called?', answer: 'Seven Sisters', reexplanation: 'To the south of Mexico there are 7 countries forming Central America known as the "Seven Sisters": Guatemala, Belize, El Salvador, Honduras, Nicaragua, Costa Rica, and Panama. These countries form the narrow land bridge connecting North and South America.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What is the area along the Appalachian Mountains where rivers fall creating waterfalls ideal for hydro-electricity called?', answer: 'Fall Line', reexplanation: 'The Fall Line is the area along the eastern slopes of the Appalachian Mountains where rivers fall from the highlands to the coastal lowlands, creating rapids and waterfalls. This makes it ideal for generating hydro-electricity. One of the world\'s most productive coal fields also lies in the central part of this region.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the phrase "windward side" in a sentence about relief rainfall.', answer: 'The windward side of a mountain — the side facing the moist wind — receives the heaviest rainfall because moist air is forced up, cools, and the moisture condenses and falls as rain.', hint: 'Windward side is the mountain slope that faces the incoming moist wind.', reexplanation: 'The windward side faces the oncoming moist wind. As warm, moist air from the ocean hits the mountain, it is forced upward. As it rises, it cools (temperature at 2000m is about -7°C). Cooling causes condensation and rainfall. This is why the windward side is always wetter.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "circumnavigate" in a sentence about the size of North America.', answer: 'North America has a coastline of 14,830 km — circumnavigating it entirely by sea would be an extraordinary journey through the Pacific, Arctic and Atlantic Oceans.', hint: 'Circumnavigate means to travel all the way around something.', reexplanation: 'To circumnavigate means to travel completely around something. North America has a coastline of 14,830 km and is bounded by three oceans: the Pacific to the west, the Atlantic to the east, and the Arctic to the north. A full coastal journey would be an immense voyage.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "ecological" in a sentence about the importance of forests in lumbering regions.', answer: 'For the ecological stability of a region, the forest cover should be at least 60% of the total area — which is why lumbering must always be accompanied by the planting of new saplings.', hint: 'Ecological means related to the relationship between living things and their environment.', reexplanation: 'Ecological stability refers to the balance of nature — where forests, animals, soil, water and air work together in a sustainable system. The chapter states that the vital forest cover should be at least 60% of total area for ecological stability. Lumbering that destroys more forest than is replaced threatens this stability.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the word "confluence" in a sentence about North America\'s river systems.', answer: 'The Mississippi and Missouri rivers form a great confluence system that drains the vast Central Lowlands of North America, providing water for irrigation, hydro-electricity and transportation.', hint: 'Confluence is where two rivers meet and join together.', reexplanation: 'A confluence is where two rivers join together. The Mississippi-Missouri river system represents one of the world\'s greatest river systems. The Missouri is the longest river; together they drain the Central Lowlands and their basin is one of the most agriculturally productive regions in the world.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "lumberjack" in a sentence about the challenges of their work.', answer: 'A lumberjack\'s life was once full of extreme hardships — long hours in freezing temperatures, dangerous log jams on frozen rivers, and the constant risk of being crushed by falling trees.', hint: 'A lumberjack is a person who cuts down trees as part of the lumbering industry.', reexplanation: 'Lumberjacks face extreme physical danger and hardship. The felling process requires climbing tall trees and ensuring they fall without crushing other trees. During transportation, log jams form on frozen rivers and lumberjacks must jump from pile to pile setting logs free — loose logs can be fatal and can crush them.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Describe the four physical divisions of North America. For each division, name it, describe its key features, and name at least two important rivers, mountains, lakes or other geographical features found there.', answer: 'North America is divided into four physical divisions. First, the Canadian Shield or Laurentian Shield — located in the northern part near Hudson Bay. It is made up of some of the oldest rocks in the world, covered by thick ice sheets during the Ice Age. Glaciers carved out great hollows that became lakes. The Five Great Lakes are here: Lake Superior (the largest freshwater lake in the world), Michigan, Huron, Erie and Ontario. Important rivers include the Mackenzie (flows north to Arctic Ocean) and the Yukon (flows through Canada and Alaska to the Bering Sea). The lowlands south of the Great Lakes are drained by the Mississippi and its tributaries; in the north they are called the Prairies. Second, the Western Cordilleras — a chain of young fold mountains stretching from Alaska to Panama. Maximum width is 1500 km. Denali (Mt. McKinley) at 6,190 m is the highest peak. The Grand Canyon of the Colorado River (1857 m deep, 446 km long) is found here. The Cascade Range, Coastal Range, Sierra Nevada and Sierra Madre are all part of the Cordilleras. Third, the Eastern Highlands or Appalachian Mountains — old fold mountains stretching from the St. Lawrence Valley to Southern USA. Below 2000 metres. The Fall Line along their eastern slope creates waterfalls ideal for hydro-electricity. Rich coal fields, iron ore, zinc and mica are found here. Fourth, the Great Central Plains or Central Lowlands — lying between the Cordilleras and the Appalachians. Vast and fertile lowlands extending from the Mackenzie delta in the north to the Gulf of Mexico. The Mississippi-Missouri river system runs through here — one of the world\'s most agriculturally productive regions. Niagara Falls (between Lake Erie and Ontario) are here — a major tourist attraction and source of hydro-power.', hint: 'Cover all four: Canadian Shield (oldest rocks, Great Lakes, Mackenzie/Yukon rivers), Western Cordilleras (Denali, Grand Canyon, young fold mountains), Appalachians (old fold mountains, Fall Line, coal), Central Lowlands (Mississippi-Missouri, Niagara Falls, fertile farmland).', reexplanation: 'Canadian Shield: oldest rocks, glaciers, Great Lakes (Superior=largest freshwater), Mackenzie to Arctic, Yukon to Bering Sea, Prairies. Western Cordilleras: young fold, Denali 6190m, Grand Canyon 1857m/446km, Cascade/Coastal/Sierra Nevada. Appalachians: old fold, below 2000m, Fall Line (hydro-electricity), coal fields. Central Lowlands: between Cordilleras and Appalachians, Mississippi-Missouri (irrigation/transport), Niagara Falls (Lake Erie/Ontario), most productive farmland.' },
  ],
}

export const ALL_GEO_QUIZZES: ChapterQuiz[] = [quiz1, quiz2, quiz3, quiz4, quiz5, quiz6, quiz7]

export function getGeoQuiz(chapterId: number): ChapterQuiz | undefined {
  return ALL_GEO_QUIZZES.find(q => q.chapterId === chapterId)
}
