// ICT Quiz Content — Gyaanpravaha
// All 5 chapters, 25 marks each

export type QuestionType = 'mcq' | 'single_word' | 'sentence' | 'long_answer'
export interface MCQOption { label: string; text: string }
export interface Question {
  id: number; type: QuestionType; marks: number; question: string
  options?: MCQOption[]; answer: string; reexplanation: string; hint?: string; sectionId?: number
}
export interface ChapterQuiz { chapterId: number; title: string; totalMarks: number; questions: Question[] }

// ─── CHAPTER 1 ───────────────────────────────────────────────────────────────

const quiz1: ChapterQuiz = {
  chapterId: 1, title: 'File Management — Organization of Data', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What is a file in a computer?',
      options: [{ label: 'A', text: 'A physical folder on your desk' }, { label: 'B', text: 'A collection of data stored permanently on a computer' }, { label: 'C', text: 'A software application' }, { label: 'D', text: 'A type of hardware' }],
      answer: 'B', reexplanation: 'A file is defined as a collection of data stored permanently on a computer. Files can contain any type of information — text, images, pictures, or any other data in any format.' },
    { id: 2, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which file extension is used for Microsoft PowerPoint files?',
      options: [{ label: 'A', text: '.docx' }, { label: 'B', text: '.xlsx' }, { label: 'C', text: '.pptx' }, { label: 'D', text: '.pdf' }],
      answer: 'C', reexplanation: '.pptx is the file extension for Microsoft PowerPoint files. .docx is Word, .xlsx is Excel, and .pdf is Portable Document Format. Each application has its own extension so the computer knows which app to use to open the file.' },
    { id: 3, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of the following is an Audio file extension?',
      options: [{ label: 'A', text: '.jpg' }, { label: 'B', text: '.mp4' }, { label: 'C', text: '.mp3' }, { label: 'D', text: '.pdf' }],
      answer: 'C', reexplanation: '.mp3 is the most popular audio format. .jpg is an image format, .mp4 is a video format, and .pdf is a document format. Knowing the difference between these extensions is essential for working with different types of files.' },
    { id: 4, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What is the purpose of a file extension?',
      options: [{ label: 'A', text: 'To make the file name longer' }, { label: 'B', text: 'To tell the computer what type of file it is and which application to use' }, { label: 'C', text: 'To protect the file with a password' }, { label: 'D', text: 'To compress the file size' }],
      answer: 'B', reexplanation: 'File extensions are used so that the computer can recognise the file type. When your computer sees a file with a .xlsx extension, it knows this file was created using Microsoft Excel and automatically opens it in Excel when you double-click it.' },
    { id: 5, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which image format supports transparent backgrounds and is used for logos on websites?',
      options: [{ label: 'A', text: '.bmp' }, { label: 'B', text: '.jpg' }, { label: 'C', text: '.gif' }, { label: 'D', text: '.png' }],
      answer: 'D', reexplanation: '.png (Portable Network Graphics) supports transparent backgrounds, which is why it is used for logos and graphics on websites. .bmp is a basic bitmap format, .jpg is for photographs, and .gif supports animation.' },
    { id: 6, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does PDF stand for?',
      answer: 'Portable Document Format',
      reexplanation: 'PDF stands for Portable Document Format. It was developed by Adobe Systems. A PDF file is like an electronic image of a document that can be printed or forwarded to others, and it looks the same on any device or operating system.' },
    { id: 7, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What file extension is used for video files in the MPEG4 format?',
      answer: '.mp4',
      reexplanation: '.mp4 stands for MPEG4 (Moving Picture Experts Group). It is the most popular video format today, used on YouTube, phones, and streaming platforms. It provides good quality with a relatively small file size.' },
    { id: 8, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does GIF stand for?',
      answer: 'Graphics Interchange Format',
      reexplanation: 'GIF stands for Graphics Interchange Format. It is an image format that supports animation — which is why GIFs are used for animated stickers and short looping images on social media.' },
    { id: 9, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'Which audio format produces high quality uncompressed audio and is used in professional music production?',
      answer: '.wav',
      reexplanation: '.wav (Waveform Audio) is a high quality, uncompressed audio format. It has a larger file size than .mp3 but better sound quality, which is why it is used in professional music production and sound editing.' },
    { id: 10, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'On the basis of what are files classified?',
      answer: 'Their application',
      reexplanation: 'Files are classified on the basis of their application — meaning, what they are used for. This gives us the four main categories: Image files, Audio files, Video files, and Application-based files.' },
    { id: 11, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "extension" in a sentence explaining what a file extension does.',
      answer: 'A file extension like .jpg tells the computer that the file is an image, so it automatically opens it in an image viewer when you double-click it.',
      hint: 'A file extension is the code after the dot in a file name that identifies its type.',
      reexplanation: 'A file extension is the three or four character code after the dot in a file name. It tells the computer what type of file it is and which application should open it. Write a sentence that connects the extension to its purpose.' },
    { id: 12, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "format" in a sentence about saving a document.',
      answer: 'When you save a school report in .docx format, the computer knows to open it with Microsoft Word.',
      hint: 'Format refers to the type or structure of a file, indicated by its extension.',
      reexplanation: 'Format refers to the specific structure and encoding of a file. Different formats serve different purposes. A .docx is a Word document format; a .pdf is a portable document format. Each format is suited to specific uses.' },
    { id: 13, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "compressed" in a sentence about the .mp3 format.',
      answer: 'The .mp3 format is compressed — it reduces the file size while keeping the sound quality good enough for everyday listening.',
      hint: 'Compressed means reduced in size while keeping the essential information.',
      reexplanation: '.mp3 files are compressed audio files. Compression reduces file size by removing data the human ear cannot easily detect. This makes .mp3 files much smaller than .wav files while still sounding good for everyday listening.' },
    { id: 14, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the phrase "application-based file" in a sentence.',
      answer: 'A .xlsx file is an application-based file — it was created by Microsoft Excel and can only be fully opened and edited using Excel.',
      hint: 'Application-based files are created by specific software and need that software to open correctly.',
      reexplanation: 'Application-based files are files created by specific software applications. They are designed to be opened by the application that created them — .docx by Word, .xlsx by Excel, .pptx by PowerPoint. Other programs may not open them correctly.' },
    { id: 15, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "permanently" in a sentence about how computers store data.',
      answer: 'Unlike RAM which loses data when the computer is switched off, files are stored permanently on the hard drive so you can access them again later.',
      hint: 'Permanently means lasting forever or for a very long time, even when the power is off.',
      reexplanation: 'Computers store information permanently in files on the hard drive or storage device. This means the data is preserved even when the computer is switched off — unlike RAM which loses all data when power is cut.' },
    { id: 16, type: 'long_answer', marks: 5,
      sectionId: 7,
      question: 'Describe the four common file formats used in computers. For each format, name it, give at least two file extensions that belong to it, and explain what each extension is used for.',
      answer: 'Computers use four main file formats. First, Image files — these store pictures and photographs. Common extensions include .jpg (the most popular photo format, compressed for small size), .png (supports transparent backgrounds, used for logos), .gif (supports animation), and .bmp (basic bitmap image). Second, Audio files — these store sound and music. Common extensions include .mp3 (the most popular compressed music format), .wav (high quality uncompressed audio used professionally), and .wma (Windows Media Audio). Third, Video files — these store moving images with sound. Common extensions include .mp4 (the most popular video format today), .avi (older high quality format), and .wmv (Windows Media Video). Fourth, Application-based files — created by specific software. Examples include .docx (Microsoft Word for documents), .xlsx (Microsoft Excel for spreadsheets), .pptx (Microsoft PowerPoint for presentations), .txt (simple text), and .pdf (Portable Document Format — looks the same on every device, used for official documents and worksheets).',
      hint: 'Go through each of the four categories: Image, Audio, Video, Application-based. For each one name it, give 2 extensions, and explain what they are used for.',
      reexplanation: 'Structure your answer around the four categories. Image: .jpg (photos), .png (logos/transparent), .gif (animation), .bmp (basic). Audio: .mp3 (popular music), .wav (professional), .wma (Windows). Video: .mp4 (most popular), .avi (older), .wmv (Windows). Application-based: .docx (Word), .xlsx (Excel), .pptx (PowerPoint), .txt (simple text), .pdf (portable document).' },
  ],
}

// ─── CHAPTER 2 ───────────────────────────────────────────────────────────────

const quiz2: ChapterQuiz = {
  chapterId: 2, title: 'Artificial Intelligence', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of the following best defines Artificial Intelligence?',
      options: [{ label: 'A', text: 'Software that only follows fixed instructions' }, { label: 'B', text: 'A branch of computer science that enables machines to think, learn and act like humans' }, { label: 'C', text: 'A type of internet connection' }, { label: 'D', text: 'A hardware component of a computer' }],
      answer: 'B', reexplanation: 'Artificial Intelligence (AI) is a branch of computer science that enables machines to think, learn, and act like humans. Unlike traditional programs that follow fixed instructions, AI can learn from data and improve over time — performing tasks without being explicitly programmed.' },
    { id: 2, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which AI application converts spoken words into text?',
      options: [{ label: 'A', text: 'Image Recognition' }, { label: 'B', text: 'Natural Language Processing' }, { label: 'C', text: 'Speech Recognition' }, { label: 'D', text: 'Ride-Sharing Services' }],
      answer: 'C', reexplanation: 'Speech Recognition is the AI application that converts spoken words into text. Examples include voice assistants like Siri, Google Assistant, and Alexa, as well as GPS navigation systems and dictation software.' },
    { id: 3, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of these is an example of Natural Language Processing (NLP)?',
      options: [{ label: 'A', text: 'Roomba vacuum cleaner' }, { label: 'B', text: 'Face ID on a phone' }, { label: 'C', text: 'Siri or Alexa understanding your question' }, { label: 'D', text: 'Uber matching driver and passenger' }],
      answer: 'C', reexplanation: 'Natural Language Processing (NLP) is AI that understands and generates human language. Siri and Alexa use NLP to understand your questions and generate spoken responses. Chatbots and Google Translate also use NLP.' },
    { id: 4, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Deep Learning is a subset of:',
      options: [{ label: 'A', text: 'Image Recognition' }, { label: 'B', text: 'Machine Learning' }, { label: 'C', text: 'Speech Recognition' }, { label: 'D', text: 'Robotics' }],
      answer: 'B', reexplanation: 'Deep Learning is a subset (type) of Machine Learning, which itself is a subset of AI. The relationship is: AI > Machine Learning > Deep Learning. Deep Learning uses multiple layers of artificial neurons to learn very complex patterns, and is used in self-driving cars.' },
    { id: 5, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of the following is a CON (disadvantage) of Artificial Intelligence?',
      options: [{ label: 'A', text: '24/7 availability' }, { label: 'B', text: 'Error-free performance' }, { label: 'C', text: 'No creativity — cannot think innovatively' }, { label: 'D', text: 'Fast decisions' }],
      answer: 'C', reexplanation: 'One major disadvantage of AI is that it has no creativity — it cannot think innovatively. AI can only work within the patterns it has learned from data. It cannot truly invent something completely new or feel inspiration the way humans can.' },
    { id: 6, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does NLP stand for in the context of Artificial Intelligence?',
      answer: 'Natural Language Processing',
      reexplanation: 'NLP stands for Natural Language Processing. It is the AI capability that allows machines to understand and generate human language. It is used in chatbots, voice assistants, translation tools, and any application that involves understanding human speech or text.' },
    { id: 7, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What type of AI learning uses multiple layers of artificial neurons to learn complex patterns?',
      answer: 'Deep Learning',
      reexplanation: 'Deep Learning uses multiple layers of artificial neurons — inspired by the structure of the human brain — to learn very complex patterns. Self-driving cars are the most famous example of Deep Learning in action.' },
    { id: 8, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'Name one household robot mentioned in the chapter as an example of AI.',
      answer: 'Roomba vacuum cleaner',
      reexplanation: 'The Roomba vacuum cleaner is an example of an AI-powered household robot. It uses sensors and AI to navigate rooms, avoid obstacles, and clean floors without human guidance. It is an example of AI performing tasks intelligently in a home environment.' },
    { id: 9, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does Machine Learning enable machines to do?',
      answer: 'Learn from data and improve automatically',
      reexplanation: 'Machine Learning enables machines to learn from data and improve automatically — without being manually programmed with rules. Instead of telling the machine what to do, you give it data and it figures out the rules on its own.' },
    { id: 10, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'Name one of the three responsible use principles of AI mentioned in the chapter.',
      answer: 'Do not share personal information unnecessarily / Use AI as a support tool not a replacement / Report harmful content to elders',
      reexplanation: 'The three responsible use principles are: (1) Do not share personal information unnecessarily — AI systems collect data, so be careful. (2) Use AI as a support tool, not a replacement — apply your own judgment. (3) Report harmful or inappropriate AI content to elders.' },
    { id: 11, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "automation" in a sentence about AI.',
      answer: 'AI enables automation of repetitive tasks — like sorting thousands of emails or scanning hundreds of X-rays — which would take humans hours to do manually.',
      hint: 'Automation means using machines to perform tasks that would otherwise be done by humans.',
      reexplanation: 'Automation is one of the biggest benefits of AI. Tasks that are repetitive and time-consuming — like data entry, email sorting, or quality checks on a production line — can be automated using AI, saving time and reducing human error.' },
    { id: 12, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "simulate" in a sentence about what AI does.',
      answer: 'AI simulates human intelligence — it can understand speech, recognise faces, and solve problems in a way that makes the machine appear as intelligent as a human.',
      hint: 'To simulate means to imitate or copy the behaviour of something.',
      reexplanation: 'AI simulates human intelligence — meaning the machine behaves AS IF it is intelligent. It does not truly "think" the way humans do, but it can perform tasks — like speech recognition or decision-making — that previously required human intelligence.' },
    { id: 13, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the phrase "responsible AI" in a sentence.',
      answer: 'Responsible AI means using artificial intelligence in a way that is safe, fair, and transparent — without causing harm to people or their privacy.',
      hint: 'Responsible AI means using AI ethically and safely.',
      reexplanation: 'Responsible AI refers to the principles and practices that ensure AI is used in a way that is safe, fair, transparent, and beneficial to society. It covers privacy protection, fairness, reliability, security, and human oversight.' },
    { id: 14, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "rational" in a sentence about AI decision-making.',
      answer: 'Unlike humans who can be influenced by emotions, AI makes rational decisions based purely on data and logic.',
      hint: 'Rational means based on reason and logic rather than emotions.',
      reexplanation: 'Rational thinking is one of the three key capabilities of AI. AI makes decisions based on logic and data — not emotions, tiredness, or personal bias. This is both a strength (accuracy) and a limitation (no empathy or creativity).' },
    { id: 15, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "privacy" in a sentence about a concern related to AI.',
      answer: 'One concern about AI is privacy — these systems collect and analyse massive amounts of personal data, raising questions about who has access to our information.',
      hint: 'Privacy means the right to keep personal information to yourself.',
      reexplanation: 'Privacy is one of the major concerns related to AI. AI systems — from voice assistants to recommendation algorithms — collect enormous amounts of personal data: location, habits, conversations, and more. This raises serious questions about data security and who can access this information.' },
    { id: 16, type: 'long_answer', marks: 5,
      sectionId: 7,
      question: 'Explain the relationship between Artificial Intelligence, Machine Learning, and Deep Learning. Use examples for each and explain how they are connected to each other.',
      answer: 'Artificial Intelligence, Machine Learning, and Deep Learning are three related concepts where each is a subset of the previous one. Artificial Intelligence (AI) is the broadest concept — it refers to any technique that makes machines intelligent, enabling them to think, learn, and act like humans. An example is a smart speaker that answers questions. Machine Learning is a specific method of achieving AI. Instead of programming rules manually, the machine is given data and learns the rules on its own. An example is image recognition — you show the system thousands of photos of cats and dogs and it learns to tell them apart. Deep Learning is a more advanced type of Machine Learning. It uses multiple layers of artificial neurons — inspired by the human brain — to learn very complex patterns. An example is self-driving cars, which must process road conditions, traffic signs, pedestrians, and other vehicles all at the same time. The relationship is like three concentric circles: AI is the largest circle containing all approaches to machine intelligence. Machine Learning is inside AI — a specific approach using data. Deep Learning is inside Machine Learning — using neural networks for the most complex tasks.',
      hint: 'Think of AI, ML, and DL as circles inside each other. AI is the biggest. ML is inside AI. DL is inside ML. Explain each one with an example, then describe how they are connected.',
      reexplanation: 'Use the nested circles analogy: AI is the broadest concept (smart speakers, chess computers). Machine Learning is inside AI — machines learning from data (image recognition, spam filters). Deep Learning is inside ML — multiple neural layers for complex patterns (self-driving cars, advanced speech). Explain that ML is a way of achieving AI, and DL is an advanced way of doing ML.' },
  ],
}

// ─── CHAPTER 3 ───────────────────────────────────────────────────────────────

const quiz3: ChapterQuiz = {
  chapterId: 3, title: 'Introduction to HTML', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What does HTML stand for?',
      options: [{ label: 'A', text: 'High Text Markup Language' }, { label: 'B', text: 'Hyper Text Markup Language' }, { label: 'C', text: 'Hyper Transfer Markup Language' }, { label: 'D', text: 'Home Tool Markup Language' }],
      answer: 'B', reexplanation: 'HTML stands for Hyper Text Markup Language. Hyper Text refers to text with hyperlinks, Markup refers to the system of tags used to structure content, and Language refers to the rules for writing. HTML was created by Tim Berners-Lee in 1991.' },
    { id: 2, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of the following is a closing HTML tag?',
      options: [{ label: 'A', text: '<body>' }, { label: 'B', text: '<br>' }, { label: 'C', text: '</body>' }, { label: 'D', text: '<img>' }],
      answer: 'C', reexplanation: '</body> is a closing tag — it has a forward slash before the keyword. <body> is the opening tag. <br> and <img> are empty tags — they have no closing tags. In HTML, most tags come in pairs: an opening tag and a closing tag.' },
    { id: 3, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which tag gives the web page its title — shown on the browser tab?',
      options: [{ label: 'A', text: '<html>' }, { label: 'B', text: '<head>' }, { label: 'C', text: '<body>' }, { label: 'D', text: '<title>' }],
      answer: 'D', reexplanation: 'The <title> tag gives the web page its title. It is placed inside the <head> section. The title appears on the browser tab at the top of the browser window — not on the page itself. For example, <title>My Page</title> will display "My Page" on the tab.' },
    { id: 4, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which heading tag produces the LARGEST text?',
      options: [{ label: 'A', text: '<h6>' }, { label: 'B', text: '<h3>' }, { label: 'C', text: '<h1>' }, { label: 'D', text: '<h4>' }],
      answer: 'C', reexplanation: '<h1> produces the largest heading text. HTML supports six heading levels from h1 (biggest) to h6 (smallest). All headings appear in bold. Think of h1 as the main newspaper headline and h6 as the smallest caption.' },
    { id: 5, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which of the following is an example of an Empty Tag?',
      options: [{ label: 'A', text: '<body>...</body>' }, { label: 'B', text: '<b>...</b>' }, { label: 'C', text: '<title>...</title>' }, { label: 'D', text: '<br>' }],
      answer: 'D', reexplanation: '<br> is an empty tag — it has only an opening tag and no closing tag because it performs an action (line break) on its own without wrapping any content. <body>, <b>, and <title> are all container tags — they have both an opening and a closing tag.' },
    { id: 6, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What is the simple text editor used for writing HTML on Windows called?',
      answer: 'Notepad',
      reexplanation: 'Notepad is a very basic text editing program on Windows which is excellent for coding HTML because it does not interfere with what you are typing — it saves exactly what you type with no hidden formatting. It can be found in Start > All Programs > Accessories.' },
    { id: 7, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What file extension must an HTML file be saved with so the browser recognises it?',
      answer: '.html or .htm',
      reexplanation: 'An HTML file must be saved with either the .html or .htm extension so the browser recognises it as a web page. If saved as .txt, the browser will display the raw code instead of rendering it as a web page.' },
    { id: 8, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does the <body> tag contain?',
      answer: 'All visible content of the web page',
      reexplanation: 'The <body> tag contains the main part of the HTML page — all the content that is visible on screen. Everything that appears in the browser window — text, images, links, tables, headings — is placed inside the <body> tags.' },
    { id: 9, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What tag is the most important tag of an HTML web page that tells the browser the document is HTML?',
      answer: '<html>',
      reexplanation: 'The <html> tag is the most important tag of the web page. It tells the browser that everything inside it is HTML content. The entire web page is enclosed within <html>...</html> tags. Without it, the browser may not correctly interpret the document.' },
    { id: 10, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'How many levels of heading tags does HTML support?',
      answer: 'Six',
      reexplanation: 'HTML supports six different levels of headings — from <h1> (the biggest) to <h6> (the smallest). All heading styles appear in Bold. Heading tags must be used in pairs — an opening and a closing tag.' },
    { id: 11, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "markup" in a sentence explaining what HTML is.',
      answer: 'HTML is a markup language — it uses special tags to mark up content and tell the browser how each part of the page should look and be structured.',
      hint: 'Markup means tagging content with special codes to give it structure and meaning.',
      reexplanation: 'A markup language uses tags to describe the structure and appearance of content. HTML marks up text by wrapping it in tags like <b> for bold or <h1> for headings. The browser reads these tags and displays the content accordingly.' },
    { id: 12, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "browser" in a sentence explaining what it does.',
      answer: 'A browser like Google Chrome reads the HTML file you have saved and displays it as a formatted web page on your screen.',
      hint: 'A browser is the program that reads HTML and shows you the finished web page.',
      reexplanation: 'A web browser (Chrome, Firefox, Edge, Opera) is the software that reads HTML files and displays them as web pages. When you open an .html file in a browser, it interprets all the tags and renders the content exactly as the HTML specifies.' },
    { id: 13, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the phrase "container tag" in a sentence with an example.',
      answer: 'The <b> tag is a container tag — it has an opening tag <b> and a closing tag </b>, and any text placed between them appears in bold.',
      hint: 'A container tag has both an opening and closing tag — content goes between them.',
      reexplanation: 'Container tags wrap around content — they have a beginning tag and an end tag, and the tag applies its effect to everything in between. Examples: <b>text</b>, <i>text</i>, <body>content</body>. The closing tag has a forward slash.' },
    { id: 14, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "structure" in a sentence about an HTML page.',
      answer: 'Every HTML page follows a fixed structure — the html tag wraps everything, the head contains the title, and the body holds all visible content.',
      hint: 'Structure means the organised arrangement of parts in a whole.',
      reexplanation: 'HTML has a rigid (fixed) structure. Every HTML page must have: <html> wrapping everything, <head> for the header information (including <title>), and <body> for all visible content. This structure ensures the browser can correctly read and display the page.' },
    { id: 15, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "render" in a sentence about what a web browser does with HTML.',
      answer: 'When you open an HTML file in Chrome, the browser renders it — turning the code and tags into a formatted, visual web page that you can read.',
      hint: 'To render means to process and display something — the browser renders HTML as a visual page.',
      reexplanation: 'Rendering is the process by which a browser takes HTML code and converts it into the visual web page you see on screen. The browser reads the tags, applies their effects (bold, heading, colour), and displays the finished result.' },
    { id: 16, type: 'long_answer', marks: 5,
      sectionId: 7,
      question: 'Explain the four basic HTML structure tags — html, head, title, and body. What does each tag do, and why is each one important? Write a simple HTML page using all four tags.',
      answer: 'Every HTML page has four essential structure tags. First, the <html> tag — this is the most important tag. It wraps around the entire web page and tells the browser that everything inside it is HTML. Without it, the browser may not correctly read the document. Second, the <head> tag — this defines the header section of the page. Information in the head section is not displayed on screen — it contains information about the document, like the title and links to stylesheets. Third, the <title> tag — placed inside the head section, it gives the web page its title. This title appears on the browser tab at the top of the window. Fourth, the <body> tag — this is the main part of the HTML page. Everything that appears on the browser screen — all the text, images, links, tables — is placed inside the body tags. Here is a simple HTML page using all four: <html><head><title>My First Page</title></head><body>Welcome to the world of HTML. This is my first web page.</body></html>',
      hint: 'Explain each tag in order: html (wraps everything), head (header info, not shown), title (browser tab title, inside head), body (all visible content). Then write a simple working HTML page with all four.',
      reexplanation: 'Cover each tag: html (tells browser it\'s HTML, wraps everything), head (header section, not shown on page), title (inside head, shown on browser tab), body (contains all visible content). Then write the code: start with <html>, then <head><title>Page Title</title></head>, then <body>content here</body>, then close </html>.' },
  ],
}

// ─── CHAPTER 4 ───────────────────────────────────────────────────────────────

const quiz4: ChapterQuiz = {
  chapterId: 4, title: 'HTML — Formatting a Web Page', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which HTML tag is used to make text appear in bold?',
      options: [{ label: 'A', text: '<i>' }, { label: 'B', text: '<u>' }, { label: 'C', text: '<b>' }, { label: 'D', text: '<center>' }],
      answer: 'C', reexplanation: '<b> is the tag that defines bold text — making text appear thicker and heavier. <i> is for italic, <u> is for underline, and <center> centres content horizontally on the page.' },
    { id: 2, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which tag is used to write chemical formulas like H₂O where the "2" appears below the normal line?',
      options: [{ label: 'A', text: '<sup>' }, { label: 'B', text: '<sub>' }, { label: 'C', text: '<b>' }, { label: 'D', text: '<s>' }],
      answer: 'B', reexplanation: '<sub> is the subscript tag — it makes text appear half a character BELOW the normal line. It is used for chemical formulas like H₂O and CO₂. <sup> is the superscript tag which places text ABOVE the normal line, used for mathematical powers like x².' },
    { id: 3, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which tag makes text scroll from right to left across the screen?',
      options: [{ label: 'A', text: '<br>' }, { label: 'B', text: '<font>' }, { label: 'C', text: '<marquee>' }, { label: 'D', text: '<center>' }],
      answer: 'C', reexplanation: 'The <marquee> tag creates scrolling text that moves from right to left across the screen — like a news ticker at the bottom of a TV channel. The <br> tag creates a line break, <font> changes text appearance, and <center> centres content.' },
    { id: 4, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What is the range of values for the size attribute in the <font> tag?',
      options: [{ label: 'A', text: '1 to 10' }, { label: 'B', text: '1 to 7' }, { label: 'C', text: '1 to 100' }, { label: 'D', text: '8 to 72' }],
      answer: 'B', reexplanation: 'The size attribute in the <font> tag can be specified in absolute values ranging from 1 to 7. The default size is 3. Size 1 is the smallest and size 7 is the largest.' },
    { id: 5, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which HTML tag creates an ordered list?',
      options: [{ label: 'A', text: '<ul>' }, { label: 'B', text: '<li>' }, { label: 'C', text: '<ol>' }, { label: 'D', text: '<list>' }],
      answer: 'C', reexplanation: '<ol> creates an ordered list — items appear in numbered or lettered sequence. <ul> creates an unordered list with bullets. <li> defines each item within either type of list. There is no <list> tag in HTML.' },
    { id: 6, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What attribute of the <body> tag is used to change the background colour of a web page?',
      answer: 'BGCOLOR',
      reexplanation: 'BGCOLOR is an attribute of the <body> tag that changes the default white background colour to a specified colour. It can be set using a colour name (like BLUE) or a hexadecimal value (like #0000FF). Example: <body bgcolor=BLUE>.' },
    { id: 7, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What tag inserts a line break in HTML?',
      answer: '<br>',
      reexplanation: 'The <br> tag inserts a line break — it moves the next content to a new line. It is an empty tag with no closing tag. Without <br>, all text would appear on the same line regardless of how you type it in the code.' },
    { id: 8, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What are the three attributes of the <font> tag?',
      answer: 'size, face, color',
      reexplanation: 'The three attributes of the <font> tag are: size (controls the size from 1–7), face (changes the typeface/font style, e.g. "verdana"), and color (sets the text colour using a colour name or hex value). Example: <font size=3 face="verdana" color=red>.' },
    { id: 9, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What is the hexadecimal colour code for the colour red?',
      answer: '#ff0000',
      reexplanation: 'The hexadecimal colour code for red is #ff0000. In hex colour codes, the first two digits represent red, the middle two represent green, and the last two represent blue. #ff0000 means maximum red, no green, no blue.' },
    { id: 10, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What type attribute would you use in <ul> to display square bullets?',
      answer: 'type=square',
      reexplanation: 'To display square bullets in an unordered list, use <ul type=square>. The default is disc (filled circle). You can also use type=circle for an open circle bullet. Example: <ul type=square><li>Item 1</ul>' },
    { id: 11, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "attribute" in a sentence about HTML tags.',
      answer: 'Attributes like color and size give additional information to HTML tags — for example, <font size=5 color=red> uses two attributes to make the text large and red.',
      hint: 'An attribute provides extra information or settings for an HTML tag.',
      reexplanation: 'Attributes are keywords placed inside HTML tags to provide additional information. They follow the format attribute="value". Multiple attributes can be placed in the same tag, separated by spaces. Examples: bgcolor, size, face, color, border, align.' },
    { id: 12, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "subscript" in a sentence with a chemistry example.',
      answer: 'In HTML, we use the subscript tag to write chemical formulas — for example, H₂O is written as H<sub>2</sub>O with the 2 appearing below the normal line.',
      hint: 'Subscript text appears below the normal text line. It is used in chemical formulas.',
      reexplanation: 'Subscript (<sub>) makes text appear half a character below the normal text line. It is commonly used for chemical formulas where numbers indicate the quantity of atoms — like H₂O (two hydrogen atoms), CO₂ (two oxygen atoms).' },
    { id: 13, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "strikethrough" in a sentence about online shopping.',
      answer: 'Online shopping sites use the strikethrough tag to show the original price crossed out — like ~~₹500~~ ₹250 — so you can clearly see the discount.',
      hint: 'Strikethrough draws a horizontal line through text, showing it is cancelled or replaced.',
      reexplanation: 'The <s> tag creates strikethrough text — a horizontal line drawn through the middle of the text. It is widely used in e-commerce to show original prices that have been discounted, making it immediately clear what the saving is.' },
    { id: 14, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the phrase "ordered list" in a sentence about when it should be used.',
      answer: 'An ordered list is the right choice when the sequence matters — like the steps in a recipe or the ranking of a top ten list — because each item is automatically numbered.',
      hint: 'An ordered list numbers items in sequence. Use it when the order of items matters.',
      reexplanation: 'An ordered list (<ol>) numbers items in sequence and is used when the order matters. For example: steps in a process (1. Open Notepad. 2. Type HTML. 3. Save as .html), rankings, or any list where items must be in a specific sequence.' },
    { id: 15, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "hexadecimal" in a sentence about colours in HTML.',
      answer: 'In HTML, colours can be specified using a hexadecimal code — for example, #ff0000 represents red and #0000ff represents blue.',
      hint: 'Hexadecimal colour codes are six-digit codes starting with # that represent colours on a computer screen.',
      reexplanation: 'Hexadecimal (hex) colour codes represent colours using a six-digit code starting with #. Each colour (red, green, blue) gets two digits in the range 00 to ff. #000000 is black (no colour), #ffffff is white (all colours), #ff0000 is pure red.' },
    { id: 16, type: 'long_answer', marks: 5,
      sectionId: 7,
      question: 'Write a complete HTML page that includes: a background colour, a heading (h1), bold text, italic text, underlined text, a line break, and an unordered list of at least three items. Explain what each tag in your code does.',
      answer: 'Here is a complete HTML page with all the required elements: <html><head><title>My Formatted Page</title></head><body bgcolor=lightblue><h1>Welcome to My Page</h1><br><b>This text is bold</b><br><i>This text is italic</i><br><u>This text is underlined</u><br>My favourite subjects:<ul type=disc><li>Science<li>Mathematics<li>ICT</ul></body></html>. Explanation: <html> starts the HTML document. <head> contains the title section. <title> shows "My Formatted Page" on the browser tab. </head> closes the head section. <body bgcolor=lightblue> starts the visible page with a light blue background. <h1> creates the largest heading — "Welcome to My Page" in bold large text. <br> creates a line break. <b> makes text appear bold. <i> makes text appear italic (slanted). <u> underlines the text. <ul type=disc> starts an unordered list with disc bullets. Each <li> defines one list item. </ul> closes the list. </body> closes the body section. </html> ends the document.',
      hint: 'Write the full HTML code first, then explain each tag. Include: body bgcolor, h1, b, i, u, br, ul/li.',
      reexplanation: 'A complete answer shows working HTML code AND explains each tag. Make sure you have: <body bgcolor=colour> for background, <h1> for heading, <b> for bold, <i> for italic, <u> for underline, <br> for line break, <ul> with at least three <li> items.' },
  ],
}

// ─── CHAPTER 5 ───────────────────────────────────────────────────────────────

const quiz5: ChapterQuiz = {
  chapterId: 5, title: 'Creating Tables in HTML', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which HTML tag is used to define a table row?',
      options: [{ label: 'A', text: '<table>' }, { label: 'B', text: '<td>' }, { label: 'C', text: '<tr>' }, { label: 'D', text: '<th>' }],
      answer: 'C', reexplanation: '<tr> stands for Table Row and is used to define a horizontal row inside a table. <table> defines the entire table, <td> defines a cell (column) inside a row. <tr> and <td> together create the rows and columns of the table.' },
    { id: 2, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What does the border attribute in the <table> tag control?',
      options: [{ label: 'A', text: 'The background colour of the table' }, { label: 'B', text: 'The thickness of the border around the table in pixels' }, { label: 'C', text: 'The number of rows in the table' }, { label: 'D', text: 'The alignment of text inside cells' }],
      answer: 'B', reexplanation: 'The border attribute in the <table> tag controls the border placed around the table and its cells. The value is the thickness in pixels. border=1 gives a thin border, border=5 gives a thicker border. Without the border attribute, the table has no visible borders.' },
    { id: 3, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'What does Cell Padding control in an HTML table?',
      options: [{ label: 'A', text: 'The space between the table and the browser edge' }, { label: 'B', text: 'The space between adjacent cells' }, { label: 'C', text: 'The distance between the content inside a cell and the cell\'s border' }, { label: 'D', text: 'The height of each row' }],
      answer: 'C', reexplanation: 'Cell Padding controls the distance between the data inside a cell and the boundaries (walls) of the cell — the space between the text and the cell border. Cell Spacing (not Cell Padding) controls the space between adjacent cells. Think: Padding = inside the cell, Spacing = between cells.' },
    { id: 4, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'Which attribute of the <img> tag specifies the file path of the image to be displayed?',
      options: [{ label: 'A', text: 'height' }, { label: 'B', text: 'width' }, { label: 'C', text: 'alt' }, { label: 'D', text: 'src' }],
      answer: 'D', reexplanation: 'The src (source) attribute specifies the file path or URL of the image to be displayed. Without src, the browser does not know which image to show. height and width set the image dimensions in pixels. Example: <img src=rose.jpg height=400 width=400>.' },
    { id: 5, type: 'mcq', marks: 1,
      sectionId: 3,
      question: 'The <img> tag in HTML is an example of:',
      options: [{ label: 'A', text: 'A container tag' }, { label: 'B', text: 'An empty tag' }, { label: 'C', text: 'A heading tag' }, { label: 'D', text: 'A list tag' }],
      answer: 'B', reexplanation: 'The <img> tag is an empty tag — it has only an opening tag and no closing tag. This is because it does not wrap around any text content — it simply inserts an image at the location where it appears. Other empty tags include <br> and <li>.' },
    { id: 6, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What does <td> stand for in HTML?',
      answer: 'Table Data',
      reexplanation: '<td> stands for Table Data. It defines a single cell inside a table row. The content of each cell goes between <td> and </td>. A row (<tr>) can contain multiple <td> cells, each representing one column in that row.' },
    { id: 7, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What attribute controls the space BETWEEN adjacent cells in an HTML table?',
      answer: 'cellspacing',
      reexplanation: 'Cell Spacing (cellspacing) controls the spacing between adjacent cells — the gap between the borders of neighbouring cells. Cell Padding (cellpadding) controls the space inside the cell between the content and the cell wall. Example: <table border=1 cellspacing=5 cellpadding=10>.' },
    { id: 8, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What values can the ALIGN attribute be set to in a table tag?',
      answer: 'LEFT, RIGHT or CENTER',
      reexplanation: 'The ALIGN attribute controls the horizontal positioning of the table on the page. It can be set to LEFT (table aligns to the left edge), RIGHT (table aligns to the right edge), or CENTER (table is centred on the page). Example: <table border=1 align=CENTER>.' },
    { id: 9, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What are the three attributes used with the <img> tag to specify an image?',
      answer: 'src, height, width',
      reexplanation: 'The three key attributes of the <img> tag are: src (specifies the file path or URL of the image), height (specifies the height in pixels), and width (specifies the width in pixels). Example: <img src=photo.jpg height=300 width=400>.' },
    { id: 10, type: 'single_word', marks: 1,
      sectionId: 4,
      question: 'What type of data does the table tag represent in HTML?',
      answer: 'Tabular data (data in rows and columns)',
      reexplanation: 'The table tag is used in HTML to represent data in tabular form — meaning data organised in rows and columns. Examples of tabular data include timetables, event schedules, price lists, and scorecards.' },
    { id: 11, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "tabular" in a sentence about HTML tables.',
      answer: 'HTML tables allow us to display tabular data — like a school timetable or a price list — in a clear grid of rows and columns that is easy to read.',
      hint: 'Tabular means organised in a table format with rows and columns.',
      reexplanation: 'Tabular means arranged in a table with rows and columns. HTML tables are ideal for displaying tabular data — any information that makes sense in a grid format, such as timetables, schedules, spreadsheet data, or comparison charts.' },
    { id: 12, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the phrase "cell padding" in a sentence explaining what it does.',
      answer: 'Cell padding adds space between the text inside a table cell and the cell\'s border, making the table easier to read by preventing text from touching the edges.',
      hint: 'Cell padding is the internal spacing inside a table cell.',
      reexplanation: 'Cell padding (cellpadding) is the space between the content inside a cell and the cell\'s border walls. Without padding, text would appear right against the cell borders, making the table hard to read. A value of 5–10 pixels usually makes tables look clean and professional.' },
    { id: 13, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "border" in a sentence about an HTML table.',
      answer: 'By writing <table border=3>, you add a border of 3 pixels thickness around the entire table and all its cells, making the grid clearly visible.',
      hint: 'The border attribute in a table tag controls the visible line around the table and cells.',
      reexplanation: 'The border attribute is added to the <table> tag and places a visible line around the table and all its cells. The value is the thickness in pixels. border=1 is thin; border=10 is thick. Without border or with border=0, the table has no visible lines.' },
    { id: 14, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "source" in a sentence about the src attribute of the <img> tag.',
      answer: 'The src attribute in the <img> tag specifies the source — the file path of the image — so the browser knows which image file to load and display.',
      hint: 'src stands for source — it tells the browser where to find the image file.',
      reexplanation: 'The src attribute specifies the source — the file path or URL of the image. The browser uses this to find and load the image file. If the image is in the same folder as the HTML file, just the file name is needed (e.g. src=rose.jpg). If it is elsewhere, the full path must be given.' },
    { id: 15, type: 'sentence', marks: 2,
      sectionId: 5,
      question: 'Use the word "dimensions" in a sentence about the <img> tag.',
      answer: 'The height and width attributes of the <img> tag set the dimensions of the image in pixels — you can make it larger or smaller than its original size.',
      hint: 'Dimensions refer to the size of something — height and width.',
      reexplanation: 'Dimensions means the measurements of size — in this case height and width in pixels. The <img> tag uses height and width attributes to specify exactly how large the image should appear on the page, regardless of its original file size.' },
    { id: 16, type: 'long_answer', marks: 5,
      sectionId: 7,
      question: 'Write a complete HTML page that creates a table showing a class timetable for Monday to Wednesday, with at least 3 subjects. Include a border, cell padding, and a heading for the page. Explain what each table-related tag and attribute in your code does.',
      answer: 'Here is a complete HTML page with a class timetable: <html><head><title>Class Timetable</title></head><body bgcolor=lightyellow><h1>Class 6 Timetable</h1><table border=2 cellpadding=8 cellspacing=3 align=CENTER><tr><td>Day</td><td>Period 1</td><td>Period 2</td><td>Period 3</td></tr><tr><td>Monday</td><td>Mathematics</td><td>Science</td><td>English</td></tr><tr><td>Tuesday</td><td>History</td><td>ICT</td><td>Mathematics</td></tr><tr><td>Wednesday</td><td>English</td><td>Mathematics</td><td>Science</td></tr></table></body></html>. Tag explanations: <table> — defines the start and end of the table. border=2 — adds a 2-pixel border around the table and all cells. cellpadding=8 — adds 8 pixels of space between the text in each cell and the cell wall. cellspacing=3 — adds 3 pixels of space between adjacent cells. align=CENTER — centres the table horizontally on the page. <tr> — defines each horizontal row. <td> — defines each cell (column) within the row. Content goes between <td> and </td>.',
      hint: 'Write a table with at least 4 rows (header + 3 days) and 4 columns (Day + 3 subjects). Add border, cellpadding, and align attributes. Then explain each table tag and attribute.',
      reexplanation: 'A strong answer shows: (1) complete working HTML with <table border=X cellpadding=X align=CENTER>, (2) a header row with day and subject labels, (3) three data rows for Monday/Tuesday/Wednesday, (4) explanation of <table>, <tr>, <td>, border, cellpadding, cellspacing, and align attributes.' },
  ],
}

export const ALL_ICT_QUIZZES: ChapterQuiz[] = [quiz1, quiz2, quiz3, quiz4, quiz5]

export function getICTQuiz(chapterId: number): ChapterQuiz | undefined {
  return ALL_ICT_QUIZZES.find(q => q.chapterId === chapterId)
}
