// Mathematics Tooltip Words — Gyaanpravaha
// Maths Connexion Class 6 — All 11 chapters

export interface TooltipWord { word: string; meaning: string }
export type WordMap = Record<string, TooltipWord>

export const MTH_TOOLTIP_WORDS: Record<number, TooltipWord[]> = {
  1: [
    { word: 'whole numbers', meaning: 'The set {0, 1, 2, 3, ...} — natural numbers plus zero. The smallest whole number is 0.' },
    { word: 'natural numbers', meaning: 'Counting numbers starting from 1: {1, 2, 3, ...}. Every natural number is a whole number, but 0 is not a natural number.' },
    { word: 'closure', meaning: 'A set is closed under an operation if the result always stays in the same set. Whole numbers are closed under addition and multiplication, but NOT subtraction or division.' },
    { word: 'commutative', meaning: 'The order of numbers can be swapped without changing the result. a + b = b + a and a × b = b × a. Works for addition and multiplication of whole numbers only.' },
    { word: 'associative', meaning: 'The grouping of numbers can be changed without changing the result. (a+b)+c = a+(b+c). Works for addition and multiplication only.' },
    { word: 'distributive', meaning: 'Multiplication distributes over addition and subtraction: a × (b + c) = a×b + a×c. Very useful for mental calculation.' },
    { word: 'successor', meaning: 'The whole number immediately after a given number. Successor of n = n + 1. Every whole number has a successor.' },
    { word: 'predecessor', meaning: 'The whole number immediately before a given number. Predecessor of n = n − 1. Zero has no predecessor in whole numbers.' },
    { word: 'additive identity', meaning: 'The number that leaves any whole number unchanged when added. That number is 0: a + 0 = a.' },
    { word: 'multiplicative identity', meaning: 'The number that leaves any whole number unchanged when multiplied. That number is 1: a × 1 = a.' },
    { word: 'number ray', meaning: 'A half-line starting at 0 extending to the right, showing whole numbers at equal intervals. Numbers increase from left to right.' },
    { word: 'digit', meaning: 'Any of the ten symbols 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 used to write numbers in the decimal system.' },
  ],
  2: [
    { word: 'factor', meaning: 'A number that divides another number exactly (with zero remainder). Factors of 12: 1, 2, 3, 4, 6, 12.' },
    { word: 'multiple', meaning: 'The result of multiplying a number by a whole number. Multiples of 5: 5, 10, 15, 20, 25 ...' },
    { word: 'prime number', meaning: 'A number with exactly two factors: 1 and itself. Examples: 2, 3, 5, 7, 11, 13. Note: 1 is neither prime nor composite.' },
    { word: 'composite number', meaning: 'A number with more than two factors. Examples: 4, 6, 8, 9, 10, 12. The opposite of prime.' },
    { word: 'prime factorisation', meaning: 'Expressing a number as a product of its prime factors only. Example: 36 = 2 × 2 × 3 × 3. Every composite number has exactly one prime factorisation.' },
    { word: 'HCF', meaning: 'Highest Common Factor — the greatest number that divides all given numbers exactly. Also called GCD or GCM. HCF × LCM = product of two numbers.' },
    { word: 'LCM', meaning: 'Lowest Common Multiple — the smallest number that is a multiple of all given numbers. Used to find when repeating events next coincide.' },
    { word: 'co-prime', meaning: 'Two numbers whose HCF = 1. They share no common factor other than 1. Example: 8 and 9. LCM of co-prime numbers = their product.' },
    { word: 'twin primes', meaning: 'Pairs of prime numbers that differ by exactly 2. Examples: (3,5), (5,7), (11,13), (17,19).' },
    { word: 'divisibility', meaning: 'A number a is divisible by b if a ÷ b gives remainder 0. Divisibility rules allow quick checks without actual division.' },
    { word: 'continued division', meaning: 'A method to find HCF: divide larger by smaller, replace larger with remainder, repeat until remainder = 0. The last divisor is the HCF.' },
    { word: 'common multiple', meaning: 'A number that is a multiple of two or more given numbers. The smallest common multiple is the LCM.' },
  ],
  3: [
    { word: 'perimeter', meaning: 'The total length of the boundary (edge) of a closed figure. Rectangle: P = 2(l+b). Square: P = 4s. Measured in units of length (m, cm).' },
    { word: 'area', meaning: 'The amount of surface enclosed by a closed figure. Rectangle: A = l×b. Square: A = s². Measured in square units (m², cm²).' },
    { word: 'rectangle', meaning: 'A four-sided figure with opposite sides equal and all angles 90°. Perimeter = 2(l+b); Area = l×b. A square is a special rectangle.' },
    { word: 'square', meaning: 'A rectangle with all four sides equal. Perimeter = 4s; Area = s².' },
    { word: 'hectare', meaning: 'A unit of area used for land: 1 hectare = 10,000 m². Also: 100 m² = 1 are; 100 ares = 1 hectare.' },
    { word: 'boundary', meaning: 'The edge of a closed figure that separates interior from exterior. The length of the boundary = perimeter.' },
    { word: 'interior', meaning: 'The region inside a closed figure. The area of the interior is what we measure as the area of the figure.' },
    { word: 'are', meaning: 'A unit of area: 1 are = 100 m². Used for measuring land. 100 ares = 1 hectare.' },
    { word: 'irregular figure', meaning: 'A figure whose area cannot be found by one formula. Strategy: divide into rectangles, find each area, add them.' },
    { word: 'breadth', meaning: 'The shorter dimension of a rectangle (also called width). Breadth = Area ÷ Length.' },
    { word: 'length', meaning: 'The longer dimension of a rectangle. Length = Area ÷ Breadth.' },
    { word: 'region', meaning: 'The part of a plane enclosed by a closed figure, including its boundary and interior.' },
  ],
  4: [
    { word: 'volume', meaning: 'The amount of 3D space occupied by a solid. Formula: V = l×b×h for cuboid; V = side³ for cube. Measured in cubic units (cm³, m³).' },
    { word: 'capacity', meaning: 'The inner space of a hollow solid — how much it can hold. Example: the volume of water a glass holds is its capacity.' },
    { word: 'cuboid', meaning: 'A 3D solid with 6 rectangular faces, 12 edges, 8 vertices. Length, breadth, and height may all differ. V = l × b × h.' },
    { word: 'cube', meaning: 'A special cuboid where all edges are equal (all 6 faces are identical squares). V = side × side × side = side³.' },
    { word: 'unit cube', meaning: 'A cube with each edge = 1 unit (1 mm, 1 cm, or 1 m). The standard unit for measuring volume by counting.' },
    { word: 'base area', meaning: 'The area of the bottom face of a 3D solid. For a cuboid, base area = l × b. Volume = base area × height.' },
    { word: 'cubic centimetre', meaning: 'The volume of a cube with each edge = 1 cm. Written as cm³ or cu.cm. Also called cc.' },
    { word: 'cubic metre', meaning: 'The volume of a cube with each edge = 1 m. Written as m³. The SI unit of volume.' },
    { word: 'edges', meaning: 'The line segments where two faces of a 3D solid meet. A cuboid has 12 edges; a cube also has 12 edges.' },
    { word: 'faces', meaning: 'The flat surfaces of a 3D solid. A cuboid has 6 rectangular faces; a cube has 6 square faces.' },
    { word: 'vertices', meaning: 'The corner points where edges meet. A cuboid has 8 vertices. Singular: vertex.' },
    { word: 'layer', meaning: 'One horizontal level of unit cubes in a solid. Volume = cubes per layer × number of layers = l×b × h.' },
  ],
  5: [
    { word: 'fraction', meaning: 'A number of the form a/b (b ≠ 0) representing a part of a whole. Numerator (a) = parts we have; denominator (b) = total equal parts.' },
    { word: 'numerator', meaning: 'The top number of a fraction. Tells how many parts we have.' },
    { word: 'denominator', meaning: 'The bottom number of a fraction. Tells how many equal parts the whole is divided into.' },
    { word: 'proper fraction', meaning: 'A fraction where numerator < denominator. Its value is less than 1. Examples: 3/4, 2/7, 5/9.' },
    { word: 'improper fraction', meaning: 'A fraction where numerator > denominator. Its value is greater than 1. Examples: 7/4, 15/3.' },
    { word: 'mixed fraction', meaning: 'A combination of a whole number and a proper fraction. Example: 1¾. Can be converted to an improper fraction: 1¾ = 7/4.' },
    { word: 'equivalent fractions', meaning: 'Fractions with the same value but different numerators and denominators. Example: 1/2 = 2/4 = 3/6. Found by multiplying/dividing both parts by the same number.' },
    { word: 'lowest terms', meaning: 'A fraction is in lowest terms when the HCF of numerator and denominator is 1. To reduce: divide both by their HCF.' },
    { word: 'reciprocal', meaning: 'The reciprocal of a/b is b/a. Their product is always 1: a/b × b/a = 1. Used in division of fractions.' },
    { word: 'unlike fractions', meaning: 'Fractions with different denominators. Must be converted to like fractions (using LCM) before adding or subtracting.' },
    { word: 'like fractions', meaning: 'Fractions with the same denominator. They can be added or subtracted directly by operating on the numerators.' },
    { word: 'common denominator', meaning: 'A shared denominator for two or more fractions. Usually the LCM of the individual denominators. Required for adding/subtracting unlike fractions.' },
  ],
  6: [
    { word: 'percentage', meaning: 'A ratio or rate expressed as a fraction of 100. Symbol: %. Comes from Latin "per centum" meaning per hundred.' },
    { word: 'percent', meaning: 'Per hundred. 25% means 25 out of every 100.' },
    { word: 'convert', meaning: 'To change from one form to another. % → fraction: divide by 100. % → decimal: shift decimal 2 left. Fraction → %: multiply by 100.' },
    { word: 'decimal', meaning: 'A number written with a decimal point. 0.25 = 25/100 = 25%. To convert decimal to %: shift decimal 2 places right.' },
    { word: 'fraction to percent', meaning: 'Multiply the fraction by 100 and add % symbol. Example: 3/4 × 100 = 75%.' },
    { word: 'percent to decimal', meaning: 'Drop the % sign and shift the decimal point 2 places to the left. Example: 35% = 0.35.' },
    { word: 'percent to fraction', meaning: 'Drop the % sign and divide by 100. Then simplify. Example: 75% = 75/100 = 3/4.' },
    { word: 'percentage of a quantity', meaning: 'To find x% of a quantity: (x/100) × quantity. Example: 10% of 500 = (10/100) × 500 = 50.' },
    { word: 'discount', meaning: 'A percentage reduction in the original price. Discount amount = discount% × original price ÷ 100.' },
    { word: 'pass percentage', meaning: 'The minimum percentage of marks required to pass an examination.' },
    { word: 'per centum', meaning: 'Latin phrase meaning "per hundred." The origin of the word "percent" and the symbol %.' },
    { word: 'comparison', meaning: 'Percentage makes comparison fair by expressing different quantities on the same scale of 100. Example: 70/80 = 87.5% vs 80/100 = 80%.' },
  ],
  7: [
    { word: 'ratio', meaning: 'Comparison of two quantities of the same kind and same units by division. Written as a:b. Has no units. Order matters: 3:2 ≠ 2:3.' },
    { word: 'antecedent', meaning: 'The first (left) term of a ratio. In a:b, "a" is the antecedent.' },
    { word: 'consequent', meaning: 'The second (right) term of a ratio. In a:b, "b" is the consequent.' },
    { word: 'simplest form', meaning: 'A ratio is in simplest form when the HCF of its two terms is 1. Divide both terms by their HCF to simplify.' },
    { word: 'proportion', meaning: 'An equality of two ratios: a:b :: c:d means a:b = c:d. Proportion property: product of extremes = product of means (a×d = b×c).' },
    { word: 'extremes', meaning: 'The outer (first and last) terms of a proportion. In a:b :: c:d, the extremes are a and d. Product of extremes = product of means.' },
    { word: 'means', meaning: 'The inner (middle) terms of a proportion. In a:b :: c:d, the means are b and c.' },
    { word: 'equivalent ratios', meaning: 'Ratios with the same value. Found by multiplying or dividing both terms by the same non-zero number. Example: 2:3 = 4:6 = 6:9.' },
    { word: 'cross multiplication', meaning: 'A method to compare two ratios: a:b vs c:d — compute a×d and b×c. The larger product indicates the larger ratio.' },
    { word: 'co-prime', meaning: 'Two numbers whose HCF is 1. A ratio in simplest form has co-prime terms.' },
    { word: 'point of concurrence', meaning: 'Not a ratio term — this belongs to geometry. In ratio context: the "point" where all equivalent ratios converge is the simplest form.' },
    { word: 'unitary method', meaning: 'Finding the value for one unit first, then scaling. Related to proportion: if a:b :: c:d, find d by d = b×c/a.' },
  ],
  8: [
    { word: 'point', meaning: 'A precise location in space with no dimensions (no length, breadth, or thickness). Represented by a dot. Named by a capital letter.' },
    { word: 'line', meaning: 'A straight path extending infinitely in both directions. Has no endpoints and no thickness.' },
    { word: 'line segment', meaning: 'A finite part of a line between two definite endpoints. Has a measurable length.' },
    { word: 'ray', meaning: 'A part of a line with one endpoint, extending infinitely in one direction only.' },
    { word: 'plane', meaning: 'A flat surface extending indefinitely in all directions. Has no thickness. Examples: floor, table top, blackboard.' },
    { word: 'parallel lines', meaning: 'Lines in the same plane that never meet however far extended. Constant distance apart. Symbol: ||. Examples: railway tracks.' },
    { word: 'intersecting lines', meaning: 'Lines that meet at exactly one point called the point of intersection. Examples: diagonals of a rectangle, crossroads.' },
    { word: 'perpendicular lines', meaning: 'Lines that intersect at exactly 90°. Symbol: ⊥. Examples: adjacent sides of a square, room corners.' },
    { word: 'concurrent lines', meaning: 'Three or more lines that all pass through the same single point called the point of concurrence. Example: spokes of a wheel.' },
    { word: 'point of intersection', meaning: 'The single point where two intersecting lines meet.' },
    { word: 'compass', meaning: 'A geometric instrument used to draw circles and arcs, and to copy lengths of line segments in construction.' },
    { word: 'construction', meaning: 'Making an accurate geometric drawing using only a ruler (for measuring) and a pair of compasses (for copying lengths and drawing arcs).' },
  ],
  9: [
    { word: 'angle', meaning: 'A figure formed by two rays (arms) originating from the same point (vertex). Measured in degrees (°). A complete rotation = 360°.' },
    { word: 'vertex', meaning: 'The common endpoint of the two arms (rays) of an angle.' },
    { word: 'acute angle', meaning: 'An angle between 0° and 90° (exclusive). Examples: 30°, 45°, 60°, 89°.' },
    { word: 'right angle', meaning: 'An angle of exactly 90°. Formed by perpendicular lines.' },
    { word: 'obtuse angle', meaning: 'An angle between 90° and 180° (exclusive). Examples: 91°, 120°, 144°, 179°.' },
    { word: 'reflex angle', meaning: 'An angle between 180° and 360° (exclusive). Examples: 181°, 258°, 300°.' },
    { word: 'straight angle', meaning: 'An angle of exactly 180°. Looks like a straight line.' },
    { word: 'bisector', meaning: 'A ray that divides an angle into two equal parts. If BD bisects ∠ABC, then ∠ABD = ∠DBC.' },
    { word: 'linear pair', meaning: 'Two adjacent angles whose non-common arms are opposite rays. Their sum is always 180°.' },
    { word: 'vertically opposite', meaning: 'Angles formed on opposite sides when two lines intersect. They are always equal in measure.' },
    { word: 'complementary', meaning: 'Two angles whose sum = 90°. Each is the complement of the other. Complement of A = 90° − A.' },
    { word: 'supplementary', meaning: 'Two angles whose sum = 180°. Each is the supplement of the other. Supplement of A = 180° − A.' },
  ],
  10: [
    { word: 'circle', meaning: 'A closed curve where all boundary points are equidistant from the fixed centre O.' },
    { word: 'centre', meaning: 'The fixed interior point O of a circle. All boundary points are at equal distance (radius) from the centre.' },
    { word: 'radius', meaning: 'Distance from the centre to any point on the circumference. All radii of a circle are equal. r = diameter ÷ 2.' },
    { word: 'diameter', meaning: 'A chord that passes through the centre. The longest chord. d = 2r. All diameters of a circle are equal.' },
    { word: 'circumference', meaning: 'The perimeter (boundary length) of a circle. C = 2πr = πd. π ≈ 22/7 ≈ 3.14.' },
    { word: 'chord', meaning: 'A line segment with both endpoints on the circle. May or may not pass through the centre. Diameter is the longest chord.' },
    { word: 'arc', meaning: 'Any curved part of the circumference. Minor arc = smaller part. Major arc = larger part. Semicircle = exactly half the circumference.' },
    { word: 'sector', meaning: 'The "pie slice" region enclosed by two radii and an arc. Minor sector (angle < 180°); major sector (angle > 180°). Quadrant = 90° sector.' },
    { word: 'segment', meaning: 'The region between a chord and an arc. Major segment (larger, contains centre); minor segment (smaller, does not contain centre).' },
    { word: 'secant', meaning: 'A straight line that intersects a circle at two points. Different from a chord: a secant is an infinite line.' },
    { word: 'tangent', meaning: 'A straight line that touches a circle at exactly one point (the point of tangency).' },
    { word: 'pi', meaning: 'π (pi) = ratio of circumference to diameter ≈ 22/7 ≈ 3.14. An irrational number that appears in all circle calculations.' },
  ],
  11: [
    { word: 'vedic mathematics', meaning: 'An ancient Hindu system of mental calculation based on Sanskrit Sutras. Revived by Swami Shri Bharti Krishna Tirthaji (1884–1960) from Vedic texts.' },
    { word: 'sutra', meaning: 'Sanskrit word meaning "thread" or "formula." In Vedic Mathematics, a brief mathematical rule or principle used for mental calculation.' },
    { word: 'ekadhikena purvena', meaning: 'Sanskrit: "One more than the previous." Vedic sutra used to square numbers ending in 5, and to multiply numbers with same tens digit and units summing to 10.' },
    { word: 'nikhilam', meaning: 'A Vedic sutra for dividing by 9 mentally. Use running digit sums for the quotient; sum of all digits = remainder.' },
    { word: 'mental arithmetic', meaning: 'Performing calculations entirely in the mind, without written intermediate steps. Vedic techniques enable fast mental arithmetic.' },
    { word: 'multiplicand', meaning: 'The number being multiplied. In 21 × 22, the multiplicand is 21.' },
    { word: 'tens digit', meaning: 'The digit in the tens place of a number. In 75, the tens digit is 7. Important for Vedic squaring and multiplication techniques.' },
    { word: 'units digit', meaning: 'The digit in the ones (units) place. In 75, the units digit is 5. Numbers ending in 5 use Ekadhikena Purvena for squaring.' },
    { word: 'square', meaning: 'A number multiplied by itself. 75² = 75 × 75 = 5625. Using Ekadhikena Purvena: right=25, left=7×8=56 → 5625.' },
    { word: 'quotient', meaning: 'The result of division. In Nikhilam (divide by 9): the quotient is found from running digit sums.' },
    { word: 'remainder', meaning: 'What is left after division. In Nikhilam for dividing by 9: remainder = sum of all digits of the dividend.' },
    { word: 'vedas', meaning: 'India\'s most ancient scriptures (Rigveda, Samaveda, Yajurveda, Atharvaveda), written in Sanskrit. Mathematical knowledge from these texts forms the basis of Vedic Mathematics.' },
  ],
}

export function getMthWordMap(chapterId: number): WordMap {
  const words = MTH_TOOLTIP_WORDS[chapterId] || []
  const map: WordMap = {}
  for (const w of words) {
    map[w.word.toLowerCase()] = w
  }
  return map
}
