// Mathematics Quiz Content — Gyaanpravaha — 11 chapters, 25 marks each

export type QuestionType = 'mcq' | 'single_word' | 'sentence' | 'long_answer'
export interface MCQOption { label: string; text: string }
export interface Question { id: number; type: QuestionType; marks: number; question: string; options?: MCQOption[]; answer: string; reexplanation: string; hint?: string; sectionId?: number }
export interface ChapterQuiz { chapterId: number; title: string; totalMarks: number; questions: Question[] }

// ── CH 1: WHOLE NUMBERS ───────────────────────────────────────────────────────
const q1: ChapterQuiz = {
  chapterId: 1, title: 'Whole Numbers', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What is the smallest whole number?', options: [{ label: 'A', text: '1' }, { label: 'B', text: '0' }, { label: 'C', text: '-1' }, { label: 'D', text: 'There is no smallest' }], answer: 'B', reexplanation: 'The smallest whole number is 0. W = {0,1,2,3,...}. The smallest natural number is 1. Zero is a whole number but NOT a natural number.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Which operation is NOT closed on whole numbers?', options: [{ label: 'A', text: 'Addition' }, { label: 'B', text: 'Multiplication' }, { label: 'C', text: 'Subtraction' }, { label: 'D', text: 'Both A and B' }], answer: 'C', reexplanation: 'Subtraction is NOT closed. For example, 5 − 8 = −3, which is not a whole number. Addition and multiplication are closed; their results are always whole numbers.' },
    { id: 3, type: 'mcq', marks: 1, question: '483 × 8 + 483 × 2 = ? (Use distributive property)', options: [{ label: 'A', text: '4340' }, { label: 'B', text: '4830' }, { label: 'C', text: '5313' }, { label: 'D', text: '3864' }], answer: 'B', reexplanation: '483 × 8 + 483 × 2 = 483 × (8+2) = 483 × 10 = 4830. Distributive property: a×b + a×c = a×(b+c).' },
    { id: 4, type: 'mcq', marks: 1, question: 'a + b = b + a represents which property?', options: [{ label: 'A', text: 'Associative' }, { label: 'B', text: 'Closure' }, { label: 'C', text: 'Distributive' }, { label: 'D', text: 'Commutative' }], answer: 'D', reexplanation: 'a + b = b + a is the Commutative property of addition. The numbers can swap positions without changing the result. Works for + and × but NOT for − or ÷.' },
    { id: 5, type: 'mcq', marks: 1, question: 'The multiplicative identity in whole numbers is:', options: [{ label: 'A', text: '0' }, { label: 'B', text: '10' }, { label: 'C', text: '1' }, { label: 'D', text: 'The number itself' }], answer: 'C', reexplanation: '1 is the multiplicative identity: a × 1 = a for any whole number a. Zero is the additive identity (a + 0 = a).' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the successor of 9999?', answer: '10000', reexplanation: 'Successor of any whole number n = n + 1. So successor of 9999 = 9999 + 1 = 10000. Every whole number has a successor, which is why there is no largest whole number.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'State the Associative Property of multiplication as a formula.', answer: '(a × b) × c = a × (b × c)', reexplanation: 'The Associative Property of multiplication: (a × b) × c = a × (b × c). You can regroup the factors without changing the product. Very useful for mental calculation.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'Is subtraction commutative for whole numbers? Give one example.', answer: 'No. Example: 7 − 3 = 4 but 3 − 7 is not a whole number, so 7−3 ≠ 3−7.', reexplanation: 'Subtraction is NOT commutative. In general, a − b ≠ b − a. Also, subtraction is not closed (3−7 is not a whole number).', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'Find: 43 + 162 + 257 + 3138 (use suitable rearrangement).', answer: '3600 (pair 43+257=300 and 162+3138=3300; 300+3300=3600)', reexplanation: 'Using commutative and associative properties: (43+257) + (162+3138) = 300 + 3300 = 3600. Choose pairs that give convenient round numbers.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'What is the additive identity in whole numbers, and why is it called so?', answer: '0, because a + 0 = a = 0 + a — adding zero leaves any number unchanged (same identity).', reexplanation: '0 is the additive identity. "Identity" means unchanged. Adding 0 to any whole number gives that same number back. Similarly, 1 is the multiplicative identity.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the phrase "distributive property" in a sentence to calculate 99 × 8 mentally.', answer: 'Using the distributive property, 99 × 8 = (100 − 1) × 8 = (100 × 8) − (1 × 8) = 800 − 8 = 792, which is much easier to work out mentally than multiplying 99 × 8 directly.', hint: 'Write 99 as (100−1). Use a×(b−c) = a×b − a×c.', reexplanation: '99 × 8 = (100−1) × 8 = 800 − 8 = 792. This is a standard trick: write a near-round number as (round ± small) and use distributivity.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "closure" in a sentence explaining why 5 − 8 shows whole numbers are not closed under subtraction.', answer: 'The closure property requires that operating on two whole numbers always gives a whole number, but 5 − 8 = −3 is not a whole number, which proves that whole numbers are not closed under subtraction.', hint: 'Closure: result must stay in the same set. 5−8=−3 is not in W = {0,1,2,...}.', reexplanation: 'Closure means the set is "sealed" — you never leave it. Whole numbers are closed under + and × but not − or ÷.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the phrase "number ray" in a sentence about where whole numbers begin and how they extend.', answer: 'On the number ray, whole numbers begin at 0 — which has no predecessor in whole numbers — and extend indefinitely to the right, with every number being the successor of the one before it.', hint: 'Number ray starts at 0, extends right. Each number is the successor of the previous. No whole number to the left of 0.', reexplanation: 'The number ray shows W = {0,1,2,...}. Starts at 0 (no predecessor). Extends infinitely right. Each number is greater than all numbers to its left.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "associative property" in a sentence showing how to find 8 × 125 × 40 × 25 quickly.', answer: 'Using the associative property, we can regroup 8 × 125 × 40 × 25 as (8 × 125) × (40 × 25) = 1000 × 1000 = 10,00,000, which is far easier than multiplying left to right.', hint: 'Regroup: (8×125) = 1000, (40×25) = 1000. Then 1000×1000 = 10,00,000.', reexplanation: 'Associativity lets us regroup: (8×125)×(40×25) = 1000×1000 = 10,00,000. Choosing clever groupings creates round numbers and makes computation trivial.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the phrase "multiplicative identity" in a sentence explaining why any number × 1 = that number.', answer: '1 is called the multiplicative identity because multiplying any whole number by 1 always returns that same number unchanged — for example, 537 × 1 = 537 — so 1 preserves every number\'s identity under multiplication.', hint: 'Multiplicative identity = 1. a × 1 = a for all whole numbers a.', reexplanation: '1 is the identity element for multiplication. It is the unique number that leaves every other number unchanged when multiplied. Similarly 0 is the identity for addition.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'State all four properties of whole numbers (Closure, Commutative, Associative, Distributive). For each, state which operations they apply to, and give one example.', answer: '1. Closure Property — Whole numbers are CLOSED under addition (5+3=8 ✓) and multiplication (4×7=28 ✓). NOT closed under subtraction (3−7=−4 ✗) or division (5÷3 is not whole ✗).\n2. Commutative Property — Addition: a+b=b+a ✓ (7+3=3+7=10). Multiplication: a×b=b×a ✓ (5×6=6×5=30). Subtraction: NOT ✗ (7−3≠3−7). Division: NOT ✗ (12÷4≠4÷12).\n3. Associative Property — Addition: (a+b)+c=a+(b+c) ✓ ((2+3)+4=2+(3+4)=9). Multiplication: (a×b)×c=a×(b×c) ✓ ((2×3)×4=2×(3×4)=24). Subtraction: NOT ✗. Division: NOT ✗.\n4. Distributive Property — Multiplication distributes over addition AND subtraction: a×(b+c)=a×b+a×c (e.g., 5×(3+2)=5×3+5×2=25 ✓). Also a×(b−c)=a×b−a×c.', hint: 'Closure, Commutative, Associative: all apply to + and ×; NOT − or ÷. Distributive: × over + and −. One example each.', reexplanation: 'Summary: + and × obey all four properties. − and ÷ obey none of the first three. Distributive only applies to × over + or −.', sectionId: 7 },
  ],
}

// ── CH 2: HCF AND LCM ─────────────────────────────────────────────────────────
const q2: ChapterQuiz = {
  chapterId: 2, title: 'H.C.F. and L.C.M.', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'A number is divisible by 11 if:', options: [{ label: 'A', text: 'Its last two digits are divisible by 11' }, { label: 'B', text: 'The sum of all digits is divisible by 11' }, { label: 'C', text: '|Sum of even-position digits − Sum of odd-position digits| = 0 or divisible by 11' }, { label: 'D', text: 'It ends in 0 or 5' }], answer: 'C', reexplanation: 'Divisibility by 11: find the difference between the sum of digits at even positions and the sum of digits at odd positions. If this difference is 0 or divisible by 11, the number is divisible by 11. Example: 2728 → even positions sum (7+8)=15, odd positions sum (2+2)=4, difference 11 → divisible by 11.' },
    { id: 2, type: 'mcq', marks: 1, question: 'HCF of 72, 120, and 192 is:', options: [{ label: 'A', text: '12' }, { label: 'B', text: '24' }, { label: 'C', text: '48' }, { label: 'D', text: '8' }], answer: 'B', reexplanation: 'Prime factorisation: 72=2³×3², 120=2³×3×5, 192=2⁶×3. Common factors: 2³ and 3¹. HCF = 2³ × 3 = 8 × 3 = 24.' },
    { id: 3, type: 'mcq', marks: 1, question: 'The key relationship between HCF and LCM of two numbers is:', options: [{ label: 'A', text: 'HCF + LCM = Product' }, { label: 'B', text: 'HCF × LCM = Product' }, { label: 'C', text: 'HCF − LCM = Product' }, { label: 'D', text: 'LCM ÷ HCF = Product' }], answer: 'B', reexplanation: 'HCF × LCM = Product of the two numbers. Example: HCF(40,60)=20, LCM(40,60)=120 → 20×120=2400=40×60 ✓. This lets you find one when you know the other: LCM = Product ÷ HCF.' },
    { id: 4, type: 'mcq', marks: 1, question: 'LCM of 8, 24, 36 is:', options: [{ label: 'A', text: '48' }, { label: 'B', text: '72' }, { label: 'C', text: '144' }, { label: 'D', text: '288' }], answer: 'B', reexplanation: 'Prime factorisation: 8=2³; 24=2³×3; 36=2²×3². LCM = product of all primes at highest power = 2³ × 3² = 8 × 9 = 72.' },
    { id: 5, type: 'mcq', marks: 1, question: 'The HCF of two co-prime numbers is:', options: [{ label: 'A', text: 'Their product' }, { label: 'B', text: 'The larger number' }, { label: 'C', text: '1' }, { label: 'D', text: 'The smaller number' }], answer: 'C', reexplanation: 'Co-prime numbers share no common factor except 1, so their HCF = 1. Their LCM = their product. Example: 8 and 9 are co-prime → HCF=1, LCM=72.' },
    { id: 6, type: 'single_word', marks: 1, question: 'State the divisibility rule for 9.', answer: 'A number is divisible by 9 if the sum of all its digits is divisible by 9.', reexplanation: 'Divisibility by 9: sum all digits; if divisible by 9, the number is. Example: 729 → 7+2+9=18, 18÷9=2 ✓. Note: same type of rule applies for 3 (sum divisible by 3).', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find HCF of 105 and 230 by continued division method.', answer: 'HCF = 5 (230÷105 rem 20; 105÷20 rem 5; 20÷5 rem 0; last divisor = 5)', reexplanation: 'Continued division: 230÷105=2 r20; 105÷20=5 r5; 20÷5=4 r0. Last divisor before remainder 0 = HCF = 5.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'What is the difference between a prime number and a composite number?', answer: 'Prime: exactly 2 factors (1 and itself, e.g., 7). Composite: more than 2 factors (e.g., 6 has factors 1,2,3,6). Note: 1 is neither.', reexplanation: 'Prime has exactly 2 factors. Composite has more than 2. 1 is neither. 2 is the smallest prime and the only even prime.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'Three bells ring every 24, 6, and 10 minutes. They ring together at 9 am. When do they next ring together?', answer: 'LCM(24,6,10) = 120 minutes = 2 hours later → 11 am', reexplanation: 'LCM(24,6,10): 24=2³×3; 6=2×3; 10=2×5. LCM=2³×3×5=120 min=2 hrs. They next ring together at 9am + 2hrs = 11am.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'HCF of two numbers is 12, LCM is 180. One number is 36. Find the other.', answer: 'Other number = (HCF × LCM) ÷ 36 = (12 × 180) ÷ 36 = 2160 ÷ 36 = 60', reexplanation: 'Using: Product of two numbers = HCF × LCM = 12 × 180 = 2160. Other number = 2160 ÷ 36 = 60.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the phrase "prime factorisation" in a sentence explaining how to find HCF of 48 and 72.', answer: 'Using prime factorisation, 48 = 2⁴ × 3 and 72 = 2³ × 3², so the HCF is the product of the common prime factors at their lowest power = 2³ × 3¹ = 8 × 3 = 24.', hint: 'HCF = product of COMMON prime factors at LOWEST power.', reexplanation: '48=2⁴×3; 72=2³×3². Common: 2 (min power 3) and 3 (min power 1). HCF=2³×3=24. Verify: 48÷24=2 ✓, 72÷24=3 ✓.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "Lowest Common Multiple" in a sentence about a real-life situation involving buses.', answer: 'If two buses arrive at a stop every 6 and 8 minutes respectively, the Lowest Common Multiple of 6 and 8 is 24, meaning both buses will next arrive together after 24 minutes.', hint: 'LCM tells you when repeating events next coincide.', reexplanation: 'LCM(6,8): 6=2×3; 8=2³. LCM=2³×3=24 minutes.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "Highest Common Factor" in a sentence about finding the largest container that measures rice bags of 150 kg, 180 kg, and 270 kg exactly.', answer: 'The Highest Common Factor of 150, 180, and 270 is 30 kg, which is the largest container that can measure each bag an exact number of times without any remainder.', hint: 'HCF real-life: largest measure/container that divides all quantities exactly.', reexplanation: 'HCF(150,180,270): 150=2×3×5²; 180=2²×3²×5; 270=2×3³×5. HCF=2×3×5=30 kg.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "co-prime numbers" in a sentence explaining why their LCM equals their product.', answer: 'Since co-prime numbers have an HCF of 1, and the formula HCF × LCM = product of the numbers means 1 × LCM = product, their LCM must equal their product — for example, LCM(8,9) = 8 × 9 = 72.', hint: 'Co-prime: HCF=1. HCF×LCM=product → 1×LCM=product → LCM=product.', reexplanation: 'When HCF=1, the two numbers share no common factors, so the LCM must include all factors of both → LCM = product.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "divisibility rule" in a sentence testing whether 2728 is divisible by 11.', answer: 'Applying the divisibility rule for 11: sum of digits at even positions (7+8=15) minus sum at odd positions (2+2=4) equals 11, which is divisible by 11, so 2728 is divisible by 11.', hint: '|even-position digit sum − odd-position digit sum| = 0 or ÷11.', reexplanation: '2728: positions 1(2),2(7),3(2),4(8). Even-position sum=7+8=15. Odd-position sum=2+2=4. |15−4|=11 ÷ 11 ✓.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Find LCM of 30, 60, and 72 using the division method. Show all steps clearly.', answer: 'Division Method for LCM of 30, 60, 72:\n2 | 30  60  72 → 15  30  36\n2 | 15  30  36 → 15  15  18\n3 | 15  15  18 →  5   5   6\n5 |  5   5   6 →  1   1   6\n2 |  1   1   6 →  1   1   3\n3 |  1   1   3 →  1   1   1\n\nLCM = 2 × 2 × 3 × 5 × 2 × 3 = 360\n\nVerification: 360÷30=12 ✓; 360÷60=6 ✓; 360÷72=5 ✓', hint: 'Divide by smallest prime dividing at least two numbers; bring others down unchanged. Multiply all divisors used.', reexplanation: 'Division method: repeatedly divide by smallest common prime factor, carry down others, until all reach 1. LCM = product of all divisors: 2×2×3×5×2×3=360.', sectionId: 7 },
  ],
}

// ── CH 3: AREA AND PERIMETER ───────────────────────────────────────────────────
const q3: ChapterQuiz = {
  chapterId: 3, title: 'Area and Perimeter', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Perimeter of a rectangle with length 12 cm and breadth 5 cm is:', options: [{ label: 'A', text: '34 cm' }, { label: 'B', text: '60 cm' }, { label: 'C', text: '17 cm' }, { label: 'D', text: '24 cm' }], answer: 'A', reexplanation: 'P = 2(l+b) = 2(12+5) = 2×17 = 34 cm.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Area of a square of side 7 cm is:', options: [{ label: 'A', text: '28 cm' }, { label: 'B', text: '28 cm²' }, { label: 'C', text: '49 cm²' }, { label: 'D', text: '49 cm' }], answer: 'C', reexplanation: 'Area = side² = 7×7 = 49 cm². Area must be in square units (cm²), not linear units (cm).' },
    { id: 3, type: 'mcq', marks: 1, question: '1 hectare equals:', options: [{ label: 'A', text: '100 m²' }, { label: 'B', text: '1000 m²' }, { label: 'C', text: '10,000 m²' }, { label: 'D', text: '1,00,000 m²' }], answer: 'C', reexplanation: '1 hectare = 10,000 m². Also: 100 m² = 1 are; 100 ares = 1 hectare.' },
    { id: 4, type: 'mcq', marks: 1, question: 'A rectangular plot is 23 m long and its area is 391 m². Its perimeter is:', options: [{ label: 'A', text: '40 m' }, { label: 'B', text: '80 m' }, { label: 'C', text: '60 m' }, { label: 'D', text: '46 m' }], answer: 'B', reexplanation: 'Breadth = Area ÷ Length = 391 ÷ 23 = 17 m. Perimeter = 2(23+17) = 2×40 = 80 m.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Tile = 12 cm × 10 cm. Tiles needed to cover a floor of 3 m × 4 m:', options: [{ label: 'A', text: '100' }, { label: 'B', text: '500' }, { label: 'C', text: '1000' }, { label: 'D', text: '120' }], answer: 'C', reexplanation: 'Floor = 300×400 = 1,20,000 cm². Tile = 12×10 = 120 cm². Tiles = 1,20,000 ÷ 120 = 1000.' },
    { id: 6, type: 'single_word', marks: 1, question: 'State the formula for area of a rectangle.', answer: 'Area = length × breadth (A = l × b)', reexplanation: 'A = l × b. Derived: b = A ÷ l; l = A ÷ b.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'A square has perimeter 64 m. Find its area.', answer: 'Side = 64 ÷ 4 = 16 m. Area = 16² = 256 m²', reexplanation: 'P = 4s → s = 64÷4 = 16 m. Area = s² = 256 m².', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'A rectangular lawn is 68 m long and 35 m wide. Find the length of fencing around it.', answer: 'Perimeter = 2(68+35) = 2×103 = 206 m', reexplanation: 'Fencing = perimeter = 2(l+b) = 2(68+35) = 206 m.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'How many square metres equal 1 are?', answer: '1 are = 100 m²', reexplanation: '100 m² = 1 are. 100 ares = 1 hectare = 10,000 m².', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'A field is 180 m × 650 m. Find its area in hectares.', answer: '180 × 650 = 1,17,000 m² ÷ 10,000 = 11.7 hectares', reexplanation: 'A = 1,17,000 m². 1 ha = 10,000 m². So 1,17,000 ÷ 10,000 = 11.7 ha.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "perimeter" in a sentence solving: A garden 25 m × 15 m. How much fencing is needed?', answer: 'The perimeter of the garden = 2(25+15) = 2×40 = 80 m, so 80 m of fencing is needed to enclose it completely.', hint: 'Fencing = perimeter = 2(l+b).', reexplanation: 'P = 2(l+b) = 2(25+15) = 80 m.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "area" in a sentence solving: A square room has perimeter 80 cm. Find its floor area.', answer: 'The side of the square room = 80 ÷ 4 = 20 cm, so its floor area = 20 × 20 = 400 cm².', hint: 's = P÷4 = 20 cm. Area = s² = 400 cm².', reexplanation: 'P=4s → s=20 cm. Area=20²=400 cm².', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "irregular figure" in a sentence explaining how to find its area.', answer: 'To find the area of an irregular figure, we divide it into regular rectangles using dotted lines, calculate the area of each rectangle separately, then add all the areas to get the total.', hint: 'Divide into rectangles → find each area → add all.', reexplanation: 'Irregular figures: decompose into rectangles, sum all areas.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "breadth of the rectangle" in a sentence solving: Area = 8100 cm², length = 135 cm.', answer: 'The breadth of the rectangle = area ÷ length = 8100 ÷ 135 = 60 cm.', hint: 'b = A ÷ l = 8100 ÷ 135 = 60 cm.', reexplanation: 'From A=l×b: b=A÷l=8100÷135=60 cm. Then P=2(135+60)=390 cm.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "hectare" in a sentence finding the area of a 400 m × 250 m field.', answer: 'A field measuring 400 m by 250 m has area = 400 × 250 = 1,00,000 m² = 1,00,000 ÷ 10,000 = 10 hectares.', hint: '1 ha = 10,000 m². 400×250 = 1,00,000 m² = 10 ha.', reexplanation: '400×250=1,00,000 m². ÷10,000 = 10 ha.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'A square field has area equal to a rectangle of perimeter 360 cm and length 135 cm. Find (a) side of square (b) area of square (c) breadth of rectangle (d) perimeter of rectangle.', answer: '(a) Perimeter of square = 360 cm → side = 360 ÷ 4 = 90 cm.\n(b) Area of square = 90² = 8100 cm².\n(c) Rectangle has same area (8100 cm²) and length 135 cm. Breadth = 8100 ÷ 135 = 60 cm.\n(d) Perimeter of rectangle = 2(135 + 60) = 2 × 195 = 390 cm.', hint: '(a) side=360÷4=90; (b) 90²=8100; (c) b=8100÷135=60; (d) 2(135+60)=390.', reexplanation: 'Step by step: P_square=360→side=90; area=8100; rectangle same area→b=60; P_rect=390 cm.', sectionId: 7 },
  ],
}

// ── CH 4: VOLUME ───────────────────────────────────────────────────────────────
const q4: ChapterQuiz = {
  chapterId: 4, title: 'Volume', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Volume of a cuboid with l=5cm, b=3cm, h=2cm is:', options: [{ label: 'A', text: '10 cm³' }, { label: 'B', text: '30 cm³' }, { label: 'C', text: '25 cm³' }, { label: 'D', text: '16 cm³' }], answer: 'B', reexplanation: 'V = l × b × h = 5 × 3 × 2 = 30 cm³.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Volume of a cube of side 4 cm is:', options: [{ label: 'A', text: '16 cm³' }, { label: 'B', text: '24 cm³' }, { label: 'C', text: '64 cm³' }, { label: 'D', text: '48 cm³' }], answer: 'C', reexplanation: 'Volume of cube = side³ = 4³ = 4 × 4 × 4 = 64 cm³.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What is the difference between volume and capacity?', options: [{ label: 'A', text: 'They are the same thing' }, { label: 'B', text: 'Volume is the space occupied by a solid; capacity is the inner space of a hollow solid' }, { label: 'C', text: 'Capacity is bigger than volume always' }, { label: 'D', text: 'Volume is measured in cm²; capacity in cm³' }], answer: 'B', reexplanation: 'Volume = space occupied by a solid object. Capacity = the inner space of a hollow solid (like a glass or box) — how much it can hold.' },
    { id: 4, type: 'mcq', marks: 1, question: 'A cuboid has base area 200 cm² and height 15 cm. Its volume is:', options: [{ label: 'A', text: '3000 cm²' }, { label: 'B', text: '3000 cm³' }, { label: 'C', text: '300 cm³' }, { label: 'D', text: '215 cm³' }], answer: 'B', reexplanation: 'V = base area × height = 200 × 15 = 3000 cm³. Note the unit is cm³ (cubic centimetre), not cm².' },
    { id: 5, type: 'mcq', marks: 1, question: 'A cube is a special cuboid where:', options: [{ label: 'A', text: 'Length = Breadth only' }, { label: 'B', text: 'All 6 faces are rectangles' }, { label: 'C', text: 'Length = Breadth = Height' }, { label: 'D', text: 'Only two faces are squares' }], answer: 'C', reexplanation: 'A cube is a special cuboid where length = breadth = height. All 6 faces are identical squares. V = side³.' },
    { id: 6, type: 'single_word', marks: 1, question: 'State the formula for volume of a cuboid.', answer: 'Volume = length × breadth × height (V = l × b × h)', reexplanation: 'V = l × b × h. All measurements must be in the same unit. The result is in cubic units (cm³, m³, etc.).', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find the volume of a cube of side 5 cm.', answer: '5³ = 5 × 5 × 5 = 125 cm³', reexplanation: 'V = side³ = 5³ = 125 cm³.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'A cuboid is 2 m long, 30 cm wide, 20 cm high. Find its volume in cm³.', answer: 'Convert: l=200cm, b=30cm, h=20cm. V = 200×30×20 = 1,20,000 cm³', reexplanation: 'Always convert to same unit first. 2 m = 200 cm. V = 200 × 30 × 20 = 1,20,000 cm³.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the standard unit of volume?', answer: 'Cubic metre (m³) is the SI standard unit; cubic centimetre (cm³) is also commonly used.', reexplanation: 'SI unit of volume = cubic metre (m³). Other units: cm³, mm³. 1 m³ = 10⁶ cm³. Note: volume is always in cubic units, not square units.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'Sameer has 80 one-centimetre cubes. Which cuboid can he build: (a) 6×5×4 or (b) 8×5×2?', answer: '(b) 8×5×2 = 80 cm³. Option (a) 6×5×4 = 120 cm³ needs more than 80 cubes.', reexplanation: '(a) V=6×5×4=120>80 ✗. (b) V=8×5×2=80 ✓. He can build (b).', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "volume of cuboid" in a sentence solving: l=4cm, b=3cm, h=2cm.', answer: 'The volume of the cuboid with length 4 cm, breadth 3 cm, and height 2 cm = 4 × 3 × 2 = 24 cm³.', hint: 'V = l × b × h = 4 × 3 × 2.', reexplanation: 'V = 4 × 3 × 2 = 24 cm³.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "same unit" in a sentence explaining why you must convert before finding volume.', answer: 'Before calculating the volume of a cuboid, all three dimensions must be in the same unit — for example, if length is in metres and breadth is in centimetres, we must convert everything to centimetres first, otherwise the formula l × b × h gives a meaningless result.', hint: 'V = l×b×h only works when l, b, h are all in the same unit.', reexplanation: 'Mixing units (e.g., metres and centimetres) gives wrong answers. Always convert to one unit first.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "capacity" in a sentence distinguishing it from volume.', answer: 'Volume is the space occupied by a solid object like a brick or a marble, while capacity is the inner space of a hollow solid such as a glass or a water tank — a glass and a solid block of the same outer dimensions have the same volume but only the hollow glass has capacity.', hint: 'Volume = space occupied. Capacity = inner space of hollow solid.', reexplanation: 'Volume refers to any solid. Capacity is specific to hollow containers (glasses, boxes, tanks).', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "side³" in a sentence about a cube with side 8 cm.', answer: 'A cube with side 8 cm has volume = side³ = 8³ = 8 × 8 × 8 = 512 cm³, confirming that volume grows very rapidly as the side length increases.', hint: 'V = side³ = 8³ = 512 cm³.', reexplanation: '8³ = 512 cm³. If you double the side from 4 cm (64 cm³) to 8 cm (512 cm³), the volume increases 8 times.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "unit cubes" in a sentence explaining how to count volume of a 3×3×3 solid.', answer: 'A solid 3 cm × 3 cm × 3 cm is made up of 27 unit cubes arranged in 3 layers of 9 unit cubes each, so its volume = 27 cubic units = 3³.', hint: '3×3 = 9 cubes per layer × 3 layers = 27 unit cubes.', reexplanation: 'Counting method: cubes per layer = l×b = 9; layers = h = 3; total = 27 unit cubes = volume.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Find the volumes of these solids: (a) Cuboid 6m×3m×2m (b) Cube side 7cm (c) Cuboid with base area 150cm² and height 8cm. Also explain why all measurements must be in the same unit.', answer: '(a) Cuboid: V = l×b×h = 6×3×2 = 36 m³.\n(b) Cube: V = side³ = 7³ = 7×7×7 = 343 cm³.\n(c) Cuboid: V = base area × height = 150 × 8 = 1200 cm³.\n\nWhy same units matter: The formula V = l×b×h multiplies three lengths together to get a cubic unit. If l is in metres and b is in centimetres, the product l×b has no meaningful unit (it is neither m³ nor cm³). For example, if l=2m, b=30cm, h=20cm and we wrongly write V=2×30×20=1200, we have mixed metres and centimetres and the answer is meaningless. Converting all to cm first: 200×30×20=1,20,000 cm³ (the correct answer).', hint: '(a)6×3×2=36m³; (b)7³=343cm³; (c)150×8=1200cm³. Explain: units must match for formula to give meaningful cubic result.', reexplanation: 'Three part answer: cuboid, cube, and base-area method. Plus explanation of unit consistency.', sectionId: 7 },
  ],
}

// ── CH 5: FRACTIONS ────────────────────────────────────────────────────────────
const q5: ChapterQuiz = {
  chapterId: 5, title: 'Fractions', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: '2/15 + 7/10 = ?', options: [{ label: 'A', text: '9/25' }, { label: 'B', text: '5/6' }, { label: 'C', text: '14/150' }, { label: 'D', text: '9/15' }], answer: 'B', reexplanation: 'LCM(15,10)=30. 2/15=4/30; 7/10=21/30. Sum=25/30=5/6.' },
    { id: 2, type: 'mcq', marks: 1, question: 'The reciprocal of 5/6 is:', options: [{ label: 'A', text: '5/6' }, { label: 'B', text: '1' }, { label: 'C', text: '6/5' }, { label: 'D', text: '11/6' }], answer: 'C', reexplanation: 'Reciprocal of a/b = b/a. Reciprocal of 5/6 = 6/5. Verify: 5/6 × 6/5 = 30/30 = 1 ✓.' },
    { id: 3, type: 'mcq', marks: 1, question: '9/16 × 7/5 = ?', options: [{ label: 'A', text: '63/80' }, { label: 'B', text: '16/21' }, { label: 'C', text: '16/80' }, { label: 'D', text: '45/80' }], answer: 'A', reexplanation: 'Multiply numerators: 9×7=63. Multiply denominators: 16×5=80. Answer = 63/80.' },
    { id: 4, type: 'mcq', marks: 1, question: '4/5 ÷ 7/15 = ?', options: [{ label: 'A', text: '28/75' }, { label: 'B', text: '1 5/7' }, { label: 'C', text: '5/7' }, { label: 'D', text: '7/5' }], answer: 'B', reexplanation: '4/5 ÷ 7/15 = 4/5 × 15/7 = 60/35 = 12/7 = 1 5/7.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Which is a proper fraction?', options: [{ label: 'A', text: '7/4' }, { label: 'B', text: '15/15' }, { label: 'C', text: '3/8' }, { label: 'D', text: '9/5' }], answer: 'C', reexplanation: 'A proper fraction has numerator < denominator. 3/8 (3<8) ✓. 7/4 and 9/5 are improper. 15/15 = 1 (neither proper nor improper, it equals 1).' },
    { id: 6, type: 'single_word', marks: 1, question: 'Convert 2 3/5 to an improper fraction.', answer: '13/5 (= (2×5 + 3)/5)', reexplanation: 'Mixed to improper: (whole × denom + numer) / denom = (2×5+3)/5 = 13/5.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Reduce 36/48 to lowest terms.', answer: '3/4 (HCF of 36 and 48 = 12; 36÷12=3, 48÷12=4)', reexplanation: 'HCF(36,48)=12. 36÷12=3, 48÷12=4. Lowest terms: 3/4.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'Simplify: 11/16 − 4/9', answer: '35/144 (LCM(16,9)=144; 99/144 − 64/144 = 35/144)', reexplanation: 'LCM(16,9)=144. 11/16=99/144; 4/9=64/144. 99−64=35. Answer=35/144.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'Mona can walk 5 2/5 km in one hour. How far in 3 1/3 hours?', answer: '27/5 × 10/3 = 270/15 = 18 km', reexplanation: '5 2/5 = 27/5 km. 3 1/3 = 10/3 hours. Distance = 27/5 × 10/3 = 270/15 = 18 km.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'A chain 8 2/5 m long is cut into 6 equal parts. Find the length of each part.', answer: '42/5 ÷ 6 = 42/30 = 7/5 = 1 2/5 m', reexplanation: '8 2/5 = 42/5. Divide by 6: 42/5 ÷ 6 = 42/5 × 1/6 = 42/30 = 7/5 = 1 2/5 m.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "LCM method" in a sentence solving: 5/12 + 9/16 + 11/24.', answer: 'Using the LCM method, LCM(12,16,24)=48, so 5/12=20/48, 9/16=27/48, 11/24=22/48, and their sum = (20+27+22)/48 = 69/48 = 1 7/16.', hint: 'LCM(12,16,24)=48. Convert each, add numerators.', reexplanation: 'LCM=48. 5/12×4=20/48; 9/16×3=27/48; 11/24×2=22/48. Sum=69/48=23/16=1 7/16.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "reciprocal" in a sentence explaining how to divide 8 by 1 1/9.', answer: 'To divide 8 by 1 1/9, convert 1 1/9 to improper fraction 10/9, then multiply 8 by its reciprocal 9/10, giving 8 × 9/10 = 72/10 = 7 1/5.', hint: '1 1/9 = 10/9. Reciprocal = 9/10. 8 × 9/10 = 72/10 = 7 1/5.', reexplanation: 'Division = multiply by reciprocal. 8 ÷ 10/9 = 8 × 9/10 = 72/10 = 7.2 = 7 1/5.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "lowest terms" in a sentence solving: reduce 125/225.', answer: 'The fraction 125/225 can be reduced to its lowest terms by dividing both numerator and denominator by their HCF of 25, giving 125÷25 = 5 and 225÷25 = 9, so the answer is 5/9.', hint: 'HCF(125,225)=25. 125÷25=5, 225÷25=9. Lowest terms = 5/9.', reexplanation: 'HCF(125,225): 125=5³; 225=9×25=3²×5². HCF=5²=25. 125÷25=5; 225÷25=9. Fraction = 5/9.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "mixed fraction" in a sentence solving: add 2 5/8 + 4 3/16 + 1 23/48.', answer: 'Converting mixed fractions to improper: 2 5/8=21/8, 4 3/16=67/16, 1 23/48=71/48. LCM(8,16,48)=48. Sum = 126/48 + 201/48 + 71/48 = 398/48 = 199/24 = 8 7/24.', hint: 'Convert to improper, find LCM=48, add numerators: 126+201+71=398. 398÷48=8 r 14... check.', reexplanation: '21/8=126/48; 67/16=201/48; 71/48=71/48. Sum=(126+201+71)/48=398/48=199/24=8 7/24.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "product of fractions" in a sentence solving: 4 2/3 × 3 1/2.', answer: 'Converting to improper fractions first: 4 2/3 = 14/3 and 3 1/2 = 7/2. Using the product of fractions rule (numerators × numerators / denominators × denominators): 14/3 × 7/2 = (14×7)/(3×2) = 98/6 = 49/3 = 16 1/3.', hint: '4 2/3=14/3; 3 1/2=7/2. Product = 14×7/(3×2) = 98/6 = 16 1/3.', reexplanation: '14/3 × 7/2 = 98/6 = 49/3 = 16⅓.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Rahul saves 2/15 of his monthly salary. His salary is ₹39,000. Find (a) monthly savings (b) monthly expenditure. Also: Savita bought 2/5 m ribbon and Kavita bought 3/4 m. What is total length?', answer: '(a) Monthly savings = 2/15 × ₹39,000 = 2 × 39,000/15 = 2 × 2600 = ₹5,200.\n(b) Expenditure = ₹39,000 − ₹5,200 = ₹33,800.\n\nRibbon: Savita = 2/5 m, Kavita = 3/4 m. Total = 2/5 + 3/4.\nLCM(5,4) = 20.\n2/5 = 8/20; 3/4 = 15/20.\nTotal = (8+15)/20 = 23/20 = 1 3/20 m.', hint: '(a) 2/15 × 39000=5200; (b) 39000−5200=33800. Ribbon: LCM(5,4)=20; 8/20+15/20=23/20=1 3/20 m.', reexplanation: 'Two part problem. Savings: fraction × salary. Expenditure: salary − savings. Ribbon: add unlike fractions using LCM.', sectionId: 7 },
  ],
}

// ── CH 6: PERCENTAGE ───────────────────────────────────────────────────────────
const q6: ChapterQuiz = {
  chapterId: 6, title: 'Percentage', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: '50% expressed as a fraction in lowest terms is:', options: [{ label: 'A', text: '50/10' }, { label: 'B', text: '1/2' }, { label: 'C', text: '5/10' }, { label: 'D', text: '50/1' }], answer: 'B', reexplanation: '50% = 50/100 = 1/2.' },
    { id: 2, type: 'mcq', marks: 1, question: '0.25 expressed as a percentage is:', options: [{ label: 'A', text: '2.5%' }, { label: 'B', text: '250%' }, { label: 'C', text: '25%' }, { label: 'D', text: '0.25%' }], answer: 'C', reexplanation: '0.25 → move decimal 2 places right → 25%.' },
    { id: 3, type: 'mcq', marks: 1, question: '14/25 as a percentage is:', options: [{ label: 'A', text: '14.25%' }, { label: 'B', text: '56%' }, { label: 'C', text: '25%' }, { label: 'D', text: '140%' }], answer: 'B', reexplanation: '14/25 × 100 = 1400/25 = 56%.' },
    { id: 4, type: 'mcq', marks: 1, question: '10% of 500 is:', options: [{ label: 'A', text: '5' }, { label: 'B', text: '50' }, { label: 'C', text: '500' }, { label: 'D', text: '510' }], answer: 'B', reexplanation: '10% of 500 = 10/100 × 500 = 5000/100 = 50.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Ashna scored 70 out of 80 in Hindi. Her percentage is:', options: [{ label: 'A', text: '70%' }, { label: 'B', text: '80%' }, { label: 'C', text: '87.5%' }, { label: 'D', text: '75%' }], answer: 'C', reexplanation: '(70/80) × 100 = 7000/80 = 87.5%.' },
    { id: 6, type: 'single_word', marks: 1, question: 'Convert 134% to a fraction in lowest terms.', answer: '134/100 = 67/50', reexplanation: '134% = 134/100. HCF(134,100)=2. 134÷2=67; 100÷2=50. Fraction = 67/50.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Convert 90% to a decimal.', answer: '0.90 (or 0.9)', reexplanation: '90% = 90/100 = 0.90. Shift decimal 2 places LEFT: 90.0% → 0.90.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'Express 3/4 as a percentage.', answer: '75%', reexplanation: '3/4 × 100 = 300/4 = 75%.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'In a board exam, 92% of 350 students passed. How many passed?', answer: '92/100 × 350 = 32200/100 = 322 students passed', reexplanation: '92% of 350 = (92/100) × 350 = 322. Failed = 350 − 322 = 28.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'What is 17% of 45 km?', answer: '17/100 × 45 = 765/100 = 7.65 km', reexplanation: '17% of 45 = (17/100) × 45 = 7.65 km.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "per hundred" in a sentence explaining what 25% means.', answer: '25% means 25 per hundred — if 25% of students in a class of 100 passed, that means exactly 25 students passed, and if the class has 200 students, then 25% means 50 students (still 25 out of every 100).', hint: 'Percent = per hundred. 25% = 25 out of every 100.', reexplanation: 'Percent literally means per hundred. It is a ratio with denominator 100, making comparison easy regardless of total.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "fraction" and "decimal" in a sentence converting 67% both ways.', answer: '67% converted to a fraction is 67/100, and converted to a decimal it is 0.67 (shift decimal 2 places left), showing that percentage, fraction, and decimal are three ways of expressing the same value.', hint: '67% → fraction: 67/100. → decimal: 0.67.', reexplanation: '67% = 67/100 = 0.67. Three equivalent representations of the same quantity.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "percentage" in a sentence comparing Sunjay\'s two test scores: 62/80 in Maths and 15/50 in Science.', answer: 'Converting to percentage: Maths = (62/80)×100 = 77.5% and Science = (15/50)×100 = 30%, so Sunjay\'s percentage in Maths is much higher, showing he performed better in Maths.', hint: 'Maths: (62/80)×100=77.5%. Science: (15/50)×100=30%.', reexplanation: '62/80×100=77.5%. 15/50×100=30%. Percentage enables fair comparison between different-total exams.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "decimal into percent" in a sentence converting 1.21.', answer: 'To convert the decimal 1.21 into a percent, we shift the decimal point two places to the right and add the % symbol, giving 121%, which means 121 out of every 100.', hint: 'Decimal → %: shift decimal 2 right. 1.21 → 121%.', reexplanation: '1.21 = 121/100 = 121%. A percentage greater than 100% means more than one whole.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "16 2/3 %" in a sentence finding 16 2/3% of 630 grams.', answer: '16 2/3% of 630 grams = (50/3)/100 × 630 = 50/(3×100) × 630 = 50 × 630/300 = 31500/300 = 105 grams.', hint: '16 2/3% = 50/3 ÷ 100 = 50/300 = 1/6. 1/6 × 630 = 105 g.', reexplanation: '16 2/3% = 16.67% ≈ 1/6. (1/6)×630=105 g.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Fill in the complete table: convert each to all three forms.\n(a) 124% → fraction, decimal\n(b) 16/100 → %, decimal\n(c) 2/5 → %, decimal\n(d) 0.25 → %, fraction\n(e) 67% → fraction, decimal', answer: '(a) 124%: fraction=124/100=31/25; decimal=1.24.\n(b) 16/100: %=(16/100)×100=16%; decimal=0.16.\n(c) 2/5: %=(2/5)×100=40%; decimal=0.40.\n(d) 0.25: %=25%; fraction=25/100=1/4.\n(e) 67%: fraction=67/100; decimal=0.67.', hint: 'Three-way conversions: %→fraction (÷100); %→decimal (÷100); fraction→% (×100); decimal→% (×100).', reexplanation: '% to fraction: divide by 100. % to decimal: move decimal 2 left. Fraction to %: multiply by 100. Decimal to %: move decimal 2 right.', sectionId: 7 },
  ],
}

// ── CH 7: RATIO AND PROPORTION ─────────────────────────────────────────────────
const q7: ChapterQuiz = {
  chapterId: 7, title: 'Ratio and Proportion', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Ratio of 50 paise to ₹2 is:', options: [{ label: 'A', text: '50:2' }, { label: 'B', text: '1:4' }, { label: 'C', text: '4:1' }, { label: 'D', text: '25:1' }], answer: 'B', reexplanation: 'Convert to same unit: ₹2 = 200 paise. Ratio = 50:200 = 1:4.' },
    { id: 2, type: 'mcq', marks: 1, question: 'If 20:25 :: 12:15, they are in proportion because:', options: [{ label: 'A', text: '20+15 = 25+12' }, { label: 'B', text: 'Product of extremes = Product of means' }, { label: 'C', text: 'All four numbers are even' }, { label: 'D', text: 'Their sum is the same' }], answer: 'B', reexplanation: '20:25 :: 12:15. Extremes: 20 and 15. Means: 25 and 12. Product of extremes = 20×15=300. Product of means = 25×12=300. Equal ✓, so in proportion.' },
    { id: 3, type: 'mcq', marks: 1, question: '₹1200 is divided between Nobita and Shuzuka in ratio 6:4. Nobita\'s share is:', options: [{ label: 'A', text: '₹480' }, { label: 'B', text: '₹600' }, { label: 'C', text: '₹720' }, { label: 'D', text: '₹800' }], answer: 'C', reexplanation: 'Total parts = 6+4 = 10. Nobita = (6/10) × 1200 = ₹720.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Which property does a ratio NOT have?', options: [{ label: 'A', text: 'It has no units' }, { label: 'B', text: 'Order of terms matters' }, { label: 'C', text: 'Both quantities must be of the same kind' }, { label: 'D', text: 'It always equals 1' }], answer: 'D', reexplanation: 'A ratio is NOT always 1. Ratios: have no units ✓; order matters ✓ (3:2 ≠ 2:3); quantities must be same kind ✓.' },
    { id: 5, type: 'mcq', marks: 1, question: 'In proportion a:b :: c:d, the product of extremes is:', options: [{ label: 'A', text: 'a × b' }, { label: 'B', text: 'b × c' }, { label: 'C', text: 'a × d' }, { label: 'D', text: 'c × d' }], answer: 'C', reexplanation: 'In a:b :: c:d, extremes are the outer terms a and d. Means are the inner terms b and c. Proportion property: a×d = b×c.' },
    { id: 6, type: 'single_word', marks: 1, question: 'Simplify the ratio 35:63 to its simplest form.', answer: '5:9 (HCF of 35 and 63 = 7; 35÷7=5, 63÷7=9)', reexplanation: 'HCF(35,63)=7. 35÷7=5; 63÷7=9. Simplest form = 5:9.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find the ratio of 24 minutes to 3 hours (in simplest form).', answer: '24 min : 180 min = 24:180 = 2:15', reexplanation: 'Convert to same unit: 3 hrs = 180 min. Ratio = 24:180. HCF(24,180)=12. 24÷12=2; 180÷12=15. Ratio = 2:15.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'In proportion 51:x :: 81:108, find x.', answer: 'x = 51×108 ÷ 81 = 5508 ÷ 81 = 68', reexplanation: 'Proportion: product of means = product of extremes. x × 81 = 51 × 108 = 5508. x = 5508 ÷ 81 = 68.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'There are 115 male workers and ratio of male to female is 5:3. Find number of female workers.', answer: '5 parts = 115 → 1 part = 23. Female = 3 parts = 3×23 = 69', reexplanation: 'Male:Female = 5:3. Male = 5 parts = 115, so 1 part = 23. Female = 3×23 = 69.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'Find three equivalent ratios for 2:3.', answer: '4:6, 6:9, 8:12 (multiply both terms by 2, 3, 4 respectively)', reexplanation: 'Equivalent ratios: multiply/divide both terms by same non-zero number. 2:3 → ×2=4:6; ×3=6:9; ×4=8:12.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "same kind and same units" in a sentence explaining why you must convert before writing a ratio.', answer: 'A ratio can only be written when both quantities are of the same kind and in the same units — for example, to find the ratio of 2 m to 5 dm, we must convert both to dm (20 dm : 5 dm = 4:1) or both to cm, since we cannot directly compare metres with decimetres.', hint: 'Ratio: both quantities must be same kind, same units. Convert first.', reexplanation: '2 m = 20 dm. Ratio = 20:5 = 4:1. If we wrongly wrote 2:5, that would be incorrect.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "product of extremes" in a sentence checking if 2,3,6,12 are in proportion.', answer: 'Checking if 2:3 :: 6:12: the product of extremes = 2×12=24, but the product of means = 3×6=18, and since 24 ≠ 18, the four numbers are NOT in proportion.', hint: '2:3 :: 6:12. Extremes: 2,12 → product=24. Means: 3,6 → product=18. 24≠18 → NOT in proportion.', reexplanation: 'Proportion check: product of extremes must equal product of means. Here 24≠18 so 2,3,6,12 are not in proportion.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "ratio" in a sentence dividing 81 mangoes among 3 children in ratio 2:3:4.', answer: 'To divide 81 mangoes in ratio 2:3:4, we find total parts = 2+3+4=9, so each child gets 81÷9=9 mangoes per part: first child gets 2×9=18, second gets 3×9=27, and third gets 4×9=36 mangoes.', hint: 'Total parts=9. Each part=81÷9=9. Shares: 18, 27, 36. Check: 18+27+36=81 ✓.', reexplanation: '2:3:4 total parts=9. Unit=81÷9=9. Shares: 18, 27, 36. Sum=81 ✓.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "antecedent and consequent" in a sentence explaining equivalent ratios.', answer: 'If both the antecedent (first term) and consequent (second term) of a ratio are multiplied or divided by the same non-zero number, the ratio remains unchanged — so 8:4, 4:2, and 2:1 are all equivalent ratios formed from 8:4 by dividing both terms by 2 each time.', hint: 'Antecedent = first term; consequent = second term. Multiply/divide both by same number → equivalent ratio.', reexplanation: '8:4 ÷2= 4:2 ÷2= 2:1. All equivalent. This is the same principle as equivalent fractions.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "cross multiplication" in a sentence comparing ratios 3:10 and 4:7.', answer: 'Using cross multiplication to compare 3:10 and 4:7: we compute 3×7=21 and 4×10=40, and since 21 < 40, we conclude 3:10 < 4:7.', hint: 'Compare a:b and c:d → compute a×d and b×c. Larger cross-product indicates larger ratio.', reexplanation: '3:10 vs 4:7 → 3/10 vs 4/7. Cross: 3×7=21 and 10×4=40. 21<40 → 3:10 < 4:7.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Mrs Verma earns ₹20,000 per month and saves ₹3,000. Find ratio of (a) savings to income (b) income to expenditure (c) savings to expenditure. Also divide ₹1575 between Kamal and Madhu in ratio 7:2.', answer: 'Savings = ₹3,000. Expenditure = 20,000−3,000 = ₹17,000.\n(a) Savings : Income = 3,000 : 20,000 = 3:20.\n(b) Income : Expenditure = 20,000 : 17,000 = 20:17.\n(c) Savings : Expenditure = 3,000 : 17,000 = 3:17.\n\nDividing ₹1575 in ratio 7:2:\nTotal parts = 7+2 = 9.\nEach part = 1575÷9 = ₹175.\nKamal = 7×175 = ₹1225.\nMadhu = 2×175 = ₹350.\nCheck: 1225+350 = 1575 ✓', hint: 'Expenditure=17000. Ratios: savings:income=3000:20000=3:20; income:expenditure=20:17; savings:expenditure=3:17. Then 1575÷9=175 per part; 7×175=1225; 2×175=350.', reexplanation: 'Three ratios all using same data. Division: unit=1575÷9=175; shares 1225 and 350.', sectionId: 7 },
  ],
}

// ── CH 8: BASIC GEOMETRICAL CONCEPTS ──────────────────────────────────────────
const q8: ChapterQuiz = {
  chapterId: 8, title: 'Basic Geometrical Concepts', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Lines that never meet however far extended are called:', options: [{ label: 'A', text: 'Intersecting lines' }, { label: 'B', text: 'Perpendicular lines' }, { label: 'C', text: 'Parallel lines' }, { label: 'D', text: 'Concurrent lines' }], answer: 'C', reexplanation: 'Parallel lines never meet in the same plane however far extended. Symbol: ||. Examples: railway tracks, opposite sides of a rectangle.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Two lines that intersect at exactly 90° are called:', options: [{ label: 'A', text: 'Parallel lines' }, { label: 'B', text: 'Perpendicular lines' }, { label: 'C', text: 'Concurrent lines' }, { label: 'D', text: 'Collinear points' }], answer: 'B', reexplanation: 'Perpendicular lines intersect at exactly 90° (a right angle). Symbol: ⊥. Examples: adjacent sides of a square, diagonals of a square.' },
    { id: 3, type: 'mcq', marks: 1, question: 'Through two distinct points, how many lines can be drawn?', options: [{ label: 'A', text: 'None' }, { label: 'B', text: 'Infinite' }, { label: 'C', text: 'Exactly one' }, { label: 'D', text: 'Exactly two' }], answer: 'C', reexplanation: 'Through two distinct points, exactly ONE straight line can be drawn. (Through a single point, infinitely many lines can pass.)' },
    { id: 4, type: 'mcq', marks: 1, question: 'Three or more lines passing through the same point are called:', options: [{ label: 'A', text: 'Parallel lines' }, { label: 'B', text: 'Perpendicular lines' }, { label: 'C', text: 'Concurrent lines' }, { label: 'D', text: 'Collinear lines' }], answer: 'C', reexplanation: 'Concurrent lines are three or more lines that pass through the same single point, called the point of concurrence.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Two planes that do not meet are called:', options: [{ label: 'A', text: 'Intersecting planes' }, { label: 'B', text: 'Perpendicular planes' }, { label: 'C', text: 'Parallel planes' }, { label: 'D', text: 'Concurrent planes' }], answer: 'C', reexplanation: 'Two planes are either parallel (never meet) or intersecting (they meet along a line). Opposite walls of a room are parallel planes.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is a plane in geometry?', answer: 'A flat surface that extends indefinitely in all directions and has no thickness.', reexplanation: 'A plane has no thickness, no boundaries, extends infinitely. Examples: floor, table top, blackboard surface.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the difference between a line and a line segment?', answer: 'A line has no endpoints and extends infinitely in both directions. A line segment has two definite endpoints and a measurable length.', reexplanation: 'Line: no endpoints, infinite length. Line segment: two endpoints, finite measurable length. Ray: one endpoint, infinite in one direction.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'Give two real-life examples each of (a) parallel lines (b) perpendicular lines.', answer: '(a) Parallel: railway tracks, ruled lines on notebook. (b) Perpendicular: adjacent sides of a square, crossroads.', reexplanation: 'Parallel: never meet — railway tracks, opposite sides of rectangle. Perpendicular: meet at 90° — room corner, adjacent sides of square.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'Through a given single point, how many lines can be drawn?', answer: 'An unlimited (infinite) number of lines can be drawn through a given single point.', reexplanation: 'Through one point: infinitely many lines. Through two points: exactly one line.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'When two planes intersect, what do they form?', answer: 'Two intersecting planes always meet along a line (not a point).', reexplanation: 'Two planes intersect along a line. This is different from two lines which intersect at a point.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "parallel lines" in a sentence with two real-life examples explaining why they are called parallel.', answer: 'Parallel lines — like the two rails of a railway track or the ruled lines in a notebook — are called parallel because they lie in the same plane but never meet, maintaining a constant distance between them no matter how far they are extended.', hint: 'Parallel lines: same plane, never meet, constant distance. Examples: railway tracks, ruled notebook lines.', reexplanation: 'Parallel lines are equidistant at every point. They cannot be curved — they must be straight lines in the same plane.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "perpendicular lines" in a sentence about the diagonals of a square.', answer: 'The diagonals of a square are perpendicular lines — they intersect each other at exactly 90° at the centre of the square, which is why we write them as diagonal₁ ⊥ diagonal₂.', hint: 'Perpendicular: intersect at 90°. Symbol ⊥. Diagonals of a square are perpendicular to each other.', reexplanation: 'In a square, diagonals are both perpendicular (cross at 90°) and equal in length, and they bisect each other.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "concurrent lines" in a sentence about a real-life example.', answer: 'The spokes of a bicycle wheel are concurrent lines — they all pass through the same central point (the hub), which is their point of concurrence.', hint: 'Concurrent lines: 3 or more lines through same point = point of concurrence.', reexplanation: 'Bicycle wheel spokes all meet at the hub. Diagonals of a polygon sometimes also pass through a common point.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the word "plane" in a sentence with three real-life examples.', answer: 'A plane is a flat surface that extends indefinitely in all directions — the floor of a room, the surface of a classroom table, and the face of a blackboard are all real-life examples of portions of planes.', hint: 'Plane: flat, extends indefinitely, no thickness. Examples: floor, table top, blackboard surface.', reexplanation: 'A plane is an ideal flat surface with infinite extent and no thickness. Real-life planes are finite portions of this ideal.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "compass" in a sentence explaining how to copy a line segment XY onto another line.', answer: 'To copy line segment XY onto a line p using a compass, we first mark a point L on line p, then open the compass to exactly the length XY, place the compass tip at L, and mark point M on line p — giving LM = XY.', hint: 'Mark L on line p. Open compass = XY. Place tip at L, cut line at M. LM = XY.', reexplanation: 'Compass copies lengths precisely — this is geometric construction. The compass preserves the distance XY and transfers it to any location.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Explain the four types of line relationships in geometry: parallel, intersecting, perpendicular, and concurrent. For each: give the definition, state the key property, and give two examples.', answer: '1. Parallel lines: Two or more lines in the same plane that never meet, however far extended. Key property: they are always the same distance apart. Examples: railway tracks; opposite sides of a rectangle.\n\n2. Intersecting lines: Two lines that meet at exactly one common point (point of intersection). Key property: they share exactly one point. Examples: diagonals of a rectangle; crossroads.\n\n3. Perpendicular lines: Two lines that intersect at exactly 90° (a right angle). Key property: they form four right angles at the point of intersection. Symbol: ⊥. Examples: adjacent sides of a square; the horizontal and vertical lines in a graph.\n\n4. Concurrent lines: Three or more lines that all pass through the same single point (the point of concurrence). Key property: all lines share exactly one common point. Examples: spokes of a bicycle wheel meeting at the hub; three or more diagonals of a polygon meeting at one point.', hint: 'Four types: parallel (never meet), intersecting (meet at one point), perpendicular (meet at 90°), concurrent (3+ through same point). Definition + key property + 2 examples each.', reexplanation: 'Complete definitions and examples for all four relationships. Note: perpendicular is a special case of intersecting.', sectionId: 7 },
  ],
}

// ── CH 9: ANGLES ───────────────────────────────────────────────────────────────
const q9: ChapterQuiz = {
  chapterId: 9, title: 'Angles', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'An angle measuring 144° is called:', options: [{ label: 'A', text: 'Acute angle' }, { label: 'B', text: 'Right angle' }, { label: 'C', text: 'Obtuse angle' }, { label: 'D', text: 'Reflex angle' }], answer: 'C', reexplanation: 'Obtuse angle: 90° < θ < 180°. 144° lies in this range, so it is obtuse.' },
    { id: 2, type: 'mcq', marks: 1, question: 'Vertically opposite angles are:', options: [{ label: 'A', text: 'Always supplementary' }, { label: 'B', text: 'Always equal' }, { label: 'C', text: 'Always complementary' }, { label: 'D', text: 'Always adjacent' }], answer: 'B', reexplanation: 'Vertically opposite angles are always equal in measure. When two lines intersect, the angles on opposite sides of the intersection are equal.' },
    { id: 3, type: 'mcq', marks: 1, question: 'The sum of angles in a linear pair is:', options: [{ label: 'A', text: '90°' }, { label: 'B', text: '270°' }, { label: 'C', text: '360°' }, { label: 'D', text: '180°' }], answer: 'D', reexplanation: 'A linear pair consists of two adjacent angles whose non-common arms form opposite rays. Their sum is always 180° (supplementary).' },
    { id: 4, type: 'mcq', marks: 1, question: 'Two angles are complementary if their sum is:', options: [{ label: 'A', text: '180°' }, { label: 'B', text: '90°' }, { label: 'C', text: '360°' }, { label: 'D', text: '45°' }], answer: 'B', reexplanation: 'Complementary angles sum to 90°. Supplementary angles sum to 180°. Complementary does not require the angles to be adjacent.' },
    { id: 5, type: 'mcq', marks: 1, question: 'An angle of 258° is classified as:', options: [{ label: 'A', text: 'Obtuse' }, { label: 'B', text: 'Straight' }, { label: 'C', text: 'Reflex' }, { label: 'D', text: 'Complete' }], answer: 'C', reexplanation: 'Reflex angle: 180° < θ < 360°. 258° lies in this range, so it is a reflex angle.' },
    { id: 6, type: 'single_word', marks: 1, question: 'Find the complement of 37°.', answer: '90° − 37° = 53°', reexplanation: 'Complement of angle A = 90° − A. Complement of 37° = 90° − 37° = 53°.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find the supplement of 120°.', answer: '180° − 120° = 60°', reexplanation: 'Supplement of angle A = 180° − A. Supplement of 120° = 180° − 120° = 60°.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'In the figure, angle AOB is a straight line. One angle = (x+10°) and adjacent angle = 75°. Find x.', answer: '(x+10°) + 75° = 180° → x + 85° = 180° → x = 95°', reexplanation: 'Linear pair: sum = 180°. (x+10) + 75 = 180. x + 85 = 180. x = 95°.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the bisector of an angle?', answer: 'The ray that divides an angle into two equal parts. If ray BD bisects ∠ABC, then ∠ABD = ∠DBC = ½ × ∠ABC.', reexplanation: 'Angle bisector = ray that cuts angle exactly in half. The two resulting angles are equal.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'Two intersecting lines form how many pairs of vertically opposite angles?', answer: 'Two pairs of vertically opposite angles.', reexplanation: 'When two lines intersect, four angles are formed. They pair up into two pairs of vertically opposite angles: (∠1,∠3) and (∠2,∠4).', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "linear pair" in a sentence explaining why ∠XOY + ∠YOZ = 180°.', answer: '∠XOY and ∠YOZ form a linear pair — their non-common arms OX and OZ are opposite rays forming a straight line — so their sum ∠XOY + ∠YOZ = 180°.', hint: 'Linear pair: adjacent angles whose non-common arms are opposite rays → sum = 180°.', reexplanation: 'Linear pair angles always add to 180° because together they form a straight angle (a straight line = 180°).', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "complementary" in a sentence about angles 40° and 50°.', answer: '40° and 50° are complementary angles because their sum = 40° + 50° = 90°, and each is the complement of the other — 50° is the complement of 40°, and 40° is the complement of 50°.', hint: 'Complementary: sum = 90°. 40+50=90 ✓.', reexplanation: 'Complementary angles need not be adjacent — they just need to sum to 90°.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "vertically opposite" in a sentence proving ∠POQ = ∠SOR when two lines PQ and RS intersect.', answer: 'When lines PQ and RS intersect at O, the angles ∠POQ and ∠SOR are vertically opposite angles — their arms form pairs of opposite rays — so they are always equal in measure: ∠POQ = ∠SOR.', hint: 'Vertically opposite: formed on opposite sides of intersection. Always equal.', reexplanation: 'Two intersecting lines form 4 angles. Opposite pairs are equal: ∠POQ=∠SOR and ∠POS=∠QOR.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "obtuse angle" in a sentence classifying 5 angles: 25°, 144°, 258°, 90°, 175°.', answer: '25° is acute (between 0° and 90°), 144° is obtuse (between 90° and 180°), 258° is a reflex angle (between 180° and 360°), 90° is a right angle, and 175° is also obtuse (between 90° and 180°).', hint: 'Acute: 0°–90°; Right: 90°; Obtuse: 90°–180°; Reflex: 180°–360°.', reexplanation: 'Classification: 25° acute; 90° right; 144° obtuse; 175° obtuse; 258° reflex.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "supplementary" in a sentence explaining why angles in a linear pair are always supplementary.', answer: 'Angles in a linear pair are always supplementary (sum = 180°) because their non-common arms form a straight line — and a straight angle measures 180° — so the two adjacent angles together must make up that straight angle.', hint: 'Straight line = 180°. Linear pair fills the entire straight angle → must sum to 180° → supplementary.', reexplanation: 'A straight line forms an angle of 180°. A linear pair together fills this straight angle, so they must sum to 180° = supplementary.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Define and give one example each of: adjacent angles, linear pair, vertically opposite angles, complementary angles, supplementary angles. State one key property of each.', answer: '1. Adjacent angles: Two angles with the same vertex and one common arm, with other arms on opposite sides. Property: they share a vertex and one arm but do not overlap. Example: ∠POQ and ∠QOR with common vertex O and common arm OQ.\n\n2. Linear pair: Two adjacent angles whose non-common arms are opposite rays. Property: always supplementary (sum = 180°). Example: ∠XOY and ∠YOZ where OX and OZ are opposite rays.\n\n3. Vertically opposite angles: Two angles formed on opposite sides when two lines intersect. Property: always equal in measure. Example: when lines PQ and RS cross at O, ∠POQ = ∠SOR.\n\n4. Complementary angles: Two angles whose sum = 90°. Property: each angle is the complement of the other; complement of A = 90° − A. Example: 40° and 50° are complementary.\n\n5. Supplementary angles: Two angles whose sum = 180°. Property: each is the supplement of the other; supplement of A = 180° − A. Example: 120° and 60° are supplementary.', hint: 'Five definitions + one key property + one example each.', reexplanation: 'All five types with clear definitions, properties, and examples.', sectionId: 7 },
  ],
}

// ── CH 10: CIRCLES ─────────────────────────────────────────────────────────────
const q10: ChapterQuiz = {
  chapterId: 10, title: 'Circles', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'The diameter of a circle is 12 cm. Its radius is:', options: [{ label: 'A', text: '24 cm' }, { label: 'B', text: '12 cm' }, { label: 'C', text: '6 cm' }, { label: 'D', text: '3 cm' }], answer: 'C', reexplanation: 'Radius = diameter ÷ 2 = 12 ÷ 2 = 6 cm.' },
    { id: 2, type: 'mcq', marks: 1, question: 'The longest chord of a circle is:', options: [{ label: 'A', text: 'Any chord' }, { label: 'B', text: 'A secant' }, { label: 'C', text: 'A tangent' }, { label: 'D', text: 'The diameter' }], answer: 'D', reexplanation: 'The diameter is the longest chord because it passes through the centre, giving it the maximum possible length across the circle.' },
    { id: 3, type: 'mcq', marks: 1, question: 'A straight line touching a circle at exactly one point is called:', options: [{ label: 'A', text: 'A chord' }, { label: 'B', text: 'A secant' }, { label: 'C', text: 'A tangent' }, { label: 'D', text: 'A diameter' }], answer: 'C', reexplanation: 'A tangent touches the circle at exactly one point (the point of tangency). A secant intersects the circle at two points. A chord has both endpoints on the circle.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Circumference of a circle of radius 7 cm (using π = 22/7) is:', options: [{ label: 'A', text: '22 cm' }, { label: 'B', text: '44 cm' }, { label: 'C', text: '154 cm' }, { label: 'D', text: '49 cm' }], answer: 'B', reexplanation: 'C = 2πr = 2 × 22/7 × 7 = 2 × 22 = 44 cm.' },
    { id: 5, type: 'mcq', marks: 1, question: 'A sector with angle 90° between the two radii is called:', options: [{ label: 'A', text: 'Minor arc' }, { label: 'B', text: 'Major sector' }, { label: 'C', text: 'Quadrant' }, { label: 'D', text: 'Semicircle' }], answer: 'C', reexplanation: 'A quadrant is a sector where the angle between the two radii = 90°. It is exactly one-quarter of the circle.' },
    { id: 6, type: 'single_word', marks: 1, question: 'Find the circumference of a circle with radius 14 cm (π = 22/7).', answer: 'C = 2πr = 2 × 22/7 × 14 = 88 cm', reexplanation: 'C = 2πr = 2 × (22/7) × 14 = 2 × 22 × 2 = 88 cm.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find the radius of a circle whose circumference is 44 cm (π = 22/7).', answer: 'r = C/(2π) = 44/(2×22/7) = 44×7/44 = 7 cm', reexplanation: 'C = 2πr → r = C/(2π) = 44 ÷ (44/7) = 44 × 7/44 = 7 cm.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'What is the difference between a chord and a diameter?', answer: 'A chord is any line segment with both endpoints on the circle. A diameter is a chord that passes through the centre — and is the longest chord.', reexplanation: 'All diameters are chords, but not all chords are diameters. Diameter is the special chord that passes through the centre O.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'A cycle wheel has diameter 28 cm. Find its circumference (π = 22/7).', answer: 'C = πd = 22/7 × 28 = 88 cm', reexplanation: 'C = πd = (22/7) × 28 = 22 × 4 = 88 cm. This is the distance the wheel covers in one revolution.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'What is the difference between a minor sector and a major sector?', answer: 'Minor sector: angle between two radii < 180°. Major sector: angle between two radii > 180°. Quadrant = sector with angle = 90°.', reexplanation: 'Minor sector is the smaller "slice"; major sector is the larger "slice". Together they make the complete circle.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "radius" and "diameter" in a sentence about a circle with circumference 132 m.', answer: 'A circle with circumference 132 m has radius r = C/(2π) = 132/(2×22/7) = 132×7/44 = 21 m, and its diameter = 2r = 2×21 = 42 m.', hint: 'r = C÷(2π) = 132÷(44/7) = 132×7/44 = 21 m. d = 42 m.', reexplanation: 'C=2πr → r=C/(2π)=132÷(44/7)=132×7/44=21 m. d=2×21=42 m.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "secant" and "tangent" in a sentence explaining the difference.', answer: 'A secant is a straight line that intersects a circle at two distinct points, while a tangent is a straight line that touches the circle at exactly one point — called the point of tangency — just grazing the circle without entering it.', hint: 'Secant: cuts circle at 2 points. Tangent: touches at exactly 1 point.', reexplanation: 'Secant crosses the circle (2 intersection points). Tangent just touches (1 point of contact).', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "circumference" in a sentence finding how far a cycle wheel (radius 35 cm) travels in 200 revolutions.', answer: 'The circumference of the cycle wheel = 2πr = 2 × 22/7 × 35 = 220 cm, so in 200 revolutions the wheel travels 200 × 220 = 44,000 cm = 440 m.', hint: 'C = 2×(22/7)×35 = 220 cm per revolution. 200 revolutions = 200×220 = 44,000 cm = 440 m.', reexplanation: 'C = 2πr = (2×22/7)×35 = 220 cm. Distance = 200×220 = 44,000 cm = 440 m.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "arc" in a sentence distinguishing between minor arc and major arc with a diagram description.', answer: 'When a chord AB divides a circle, the smaller curved part of the circumference between A and B is the minor arc, and the larger curved part is the major arc — together they make up the full circumference.', hint: 'Minor arc: smaller curved part. Major arc: larger curved part. Together: full circumference.', reexplanation: 'Any chord divides the circumference into two arcs: minor (shorter) and major (longer). Semicircle divides it into two equal arcs.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "segment" in a sentence explaining the difference between minor and major segment.', answer: 'Every chord of a circle divides its interior into two segments: the minor segment (the smaller region that does not contain the centre) and the major segment (the larger region that contains the centre of the circle).', hint: 'Segment = region between chord and arc. Major segment contains centre; minor segment does not.', reexplanation: 'Chord divides circle into two segments. Major (larger, contains O). Minor (smaller, does not contain O).', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Name and define 7 elements of a circle: centre, radius, diameter, chord, arc, sector, segment. State the key relationships between radius and diameter, and calculate the circumference and radius of a circle park where Dr Hathi runs 3 times and covers 396 m total.', answer: 'Seven elements:\n1. Centre (O): fixed interior point from which all boundary points are equidistant.\n2. Radius (r): distance from centre to any point on circumference. All radii are equal.\n3. Diameter (d): chord passing through centre; d = 2r; longest chord.\n4. Chord: line segment with both endpoints on the circle.\n5. Arc: any curved part of the circumference (minor = smaller, major = larger).\n6. Sector: region enclosed by two radii and an arc.\n7. Segment: region between a chord and an arc.\n\nKey relationships: d = 2r; r = d/2; C = 2πr = πd.\n\nDr Hathi problem:\nTotal distance = 396 m (3 rounds).\nCircumference = 396 ÷ 3 = 132 m.\nr = C/(2π) = 132/(2×22/7) = 132×7/44 = 21 m.\nSo the park has circumference 132 m and radius 21 m.', hint: '7 elements with definitions. C=396÷3=132m. r=132÷(2×22/7)=21m.', reexplanation: 'Complete definitions plus calculation: C=132m, r=21m.', sectionId: 7 },
  ],
}

// ── CH 11: VEDIC KNOWLEDGE ─────────────────────────────────────────────────────
const q11: ChapterQuiz = {
  chapterId: 11, title: 'Vedic Knowledge', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Who revived and systematised Vedic Mathematics?', options: [{ label: 'A', text: 'Aryabhata' }, { label: 'B', text: 'Swami Bharti Krishna Tirthaji' }, { label: 'C', text: 'Ramanujan' }, { label: 'D', text: 'Brahmagupta' }], answer: 'B', reexplanation: 'Swami Shri Bharti Krishna Tirthaji (1884–1960) revived and systematised Vedic Mathematics from the study of ancient Vedic texts. He wrote 16 volumes on the subject.' },
    { id: 2, type: 'mcq', marks: 1, question: '21 × 22 using the Vedic method is:', options: [{ label: 'A', text: '452' }, { label: 'B', text: '426' }, { label: 'C', text: '462' }, { label: 'D', text: '482' }], answer: 'C', reexplanation: '21 × 22: left=2×2=4; right=2×1=2; middle=2×(2+1)=6. Answer = 462.' },
    { id: 3, type: 'mcq', marks: 1, question: '75² using Ekadhikena Purvena is:', options: [{ label: 'A', text: '5225' }, { label: 'B', text: '5625' }, { label: 'C', text: '5425' }, { label: 'D', text: '6025' }], answer: 'B', reexplanation: '75²: right=25 (always). Left=7×(7+1)=7×8=56. Answer=5625.' },
    { id: 4, type: 'mcq', marks: 1, question: '23 × 27 using Ekadhikena Purvena (units add to 10, same tens digit) is:', options: [{ label: 'A', text: '621' }, { label: 'B', text: '641' }, { label: 'C', text: '581' }, { label: 'D', text: '721' }], answer: 'A', reexplanation: '23×27: units 3+7=10 ✓, tens both 2 ✓. Right=3×7=21. Left=2×(2+1)=6. Answer=621.' },
    { id: 5, type: 'mcq', marks: 1, question: 'The Vedic sutra for squaring numbers ending in 5 is:', options: [{ label: 'A', text: 'Nikhilam' }, { label: 'B', text: 'Ekadhikena Purvena' }, { label: 'C', text: 'Anurupyena' }, { label: 'D', text: 'Vertically and Crosswise' }], answer: 'B', reexplanation: 'Ekadhikena Purvena means "One more than the previous" in Sanskrit. It is used to square numbers ending in 5 and multiply numbers with same tens digit and units digits summing to 10.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "Ekadhikena Purvena" mean in Sanskrit?', answer: '"One more than the previous"', reexplanation: 'Eka = one; Adhikena = more than; Purvena = the previous. So "Ekadhikena Purvena" = "One more than the previous." Used for squaring numbers ending in 5.', sectionId: 4 },
    { id: 7, type: 'single_word', marks: 1, question: 'Find 45² using Ekadhikena Purvena.', answer: 'Right=25; Left=4×5=20. Answer = 2025', reexplanation: '45²: right=25 (always). Left=tens digit × (tens digit+1) = 4×5=20. Answer=2025.', sectionId: 4 },
    { id: 8, type: 'single_word', marks: 1, question: 'Find 34 × 22 using the Vedic multiply-by-22 method.', answer: 'Left=2×3=6; Right=2×4=8; Middle=2×(3+4)=14. 6|14|8 → carry → 748', reexplanation: 'Left=2×3=6; Middle=2×7=14; Right=2×4=8. Write 6|14|8: carry the 1 from 14 → 7|4|8 = 748.', sectionId: 4 },
    { id: 9, type: 'single_word', marks: 1, question: 'Use Nikhilam to divide 143 by 9.', answer: 'Q=15, R=8 (first digit 1=first Q digit; 1+4=5=second Q digit; 1+4+3=8=remainder)', reexplanation: 'Nikhilam for 143÷9: Step1: Q starts with 1 (first digit). Step2: 1+4=5 (second Q digit). Step3: Sum of all digits 1+4+3=8=Remainder. Answer: Q=15, R=8. Verify: 15×9+8=135+8=143 ✓.', sectionId: 4 },
    { id: 10, type: 'single_word', marks: 1, question: 'Find 65² using Ekadhikena Purvena.', answer: 'Right=25; Left=6×7=42. Answer = 4225', reexplanation: '65²: right=25. Left=6×(6+1)=6×7=42. Answer=4225.', sectionId: 4 },
    { id: 11, type: 'sentence', marks: 2, question: 'Use "Vedic Mathematics" in a sentence about Swami Bharti Krishna Tirthaji and its origin.', answer: 'Vedic Mathematics is a unique system of mental calculation based on Sanskrit Sutras, revived and systematised by Swami Shri Bharti Krishna Tirthaji (1884–1960) from his study of ancient Vedic scriptures — showing that India\'s mathematical heritage stretches back thousands of years.', hint: 'Vedic Maths = system based on Sutras; revived by Swami Bharti Krishna Tirthaji (1884–1960) from ancient Vedic texts.', reexplanation: 'Vedic Maths origin: ancient Vedic texts. Modern systematisation: Swami Tirthaji. Demonstrates India\'s ancient mathematical legacy.', sectionId: 5 },
    { id: 12, type: 'sentence', marks: 2, question: 'Use "Ekadhikena Purvena" in a sentence demonstrating how to find 55².', answer: 'Using the Vedic sutra Ekadhikena Purvena ("One more than the previous"), 55² is found by: right part = 25 (always = 5×5), left part = tens digit × (tens digit+1) = 5×6 = 30, giving the answer 3025.', hint: '55²: right=25; left=5×6=30. Answer=3025.', reexplanation: 'Ekadhikena Purvena for 55²: right=25, left=5×(5+1)=30. Answer=3025.', sectionId: 5 },
    { id: 13, type: 'sentence', marks: 2, question: 'Use "Nikhilam sutra" in a sentence solving 243 ÷ 9.', answer: 'Using the Nikhilam sutra to divide 243 by 9: the first digit 2 is the first quotient digit; running sum 2+4=6 is the second quotient digit; the sum of all digits 2+4+3=9 is the remainder — but since remainder equals the divisor, we add 1 to the quotient: Q=27, R=0. So 243÷9=27.', hint: '243÷9: Q starts as 2; 2+4=6 → Q=26; remainder=2+4+3=9, which equals divisor → Q=27, R=0.', reexplanation: 'When remainder=divisor, carry 1 to quotient. 243÷9=27 exactly.', sectionId: 5 },
    { id: 14, type: 'sentence', marks: 2, question: 'Use "multiply by 22" in a sentence showing 43 × 22.', answer: 'To multiply 43 by 22 using the Vedic method: left = 2×4=8, right = 2×3=6, middle = 2×(4+3) = 2×7=14; writing 8|14|6 and carrying the 1 from 14 gives 8+1=9, so the answer is 946.', hint: 'Left=2×4=8; Middle=2×7=14; Right=2×3=6. 8|14|6 → carry → 9|4|6 = 946.', reexplanation: '43×22: Left=8, Middle=14, Right=6. 8|14|6 → 946. Verify: 43×22=43×20+43×2=860+86=946 ✓.', sectionId: 5 },
    { id: 15, type: 'sentence', marks: 2, question: 'Use "sutra" in a sentence listing all the Vedic sutras taught in this chapter with their meanings.', answer: 'This chapter teaches three Vedic sutras: "Ekadhikena Purvena" (meaning "One more than the previous"), used for squaring numbers ending in 5 and multiplying numbers with same tens digit and units adding to 10; and "Nikhilam" (meaning "all from 9"), used for dividing 3-digit numbers by 9 mentally.', hint: 'Three sutras: Ekadhikena Purvena (squaring ending in 5 + multiply same-tens), Nikhilam (divide by 9).', reexplanation: 'Two sutras taught: Ekadhikena Purvena and Nikhilam. Both are ancient Sanskrit mathematical rules.', sectionId: 5 },
    { id: 16, type: 'long_answer', marks: 5, question: 'Show the complete working for: (a) 95² (b) 36 × 34 (c) 21 × 22 (d) 132 ÷ 9. For each, name the Vedic technique used.', answer: '(a) 95² — Ekadhikena Purvena (squaring numbers ending in 5):\nRight part = 5×5 = 25.\nLeft part = 9 × (9+1) = 9×10 = 90.\nAnswer = 9025.\n\n(b) 36 × 34 — Ekadhikena Purvena (same tens digit 3; units: 6+4=10 ✓):\nRight = 6×4 = 24.\nLeft = 3×(3+1) = 3×4 = 12.\nAnswer = 1224.\n\n(c) 21 × 22 — Vedic multiply-by-22 method:\nLeft = 2×2 = 4.\nMiddle = 2×(2+1) = 6.\nRight = 2×1 = 2.\nAnswer = 462.\n\n(d) 132 ÷ 9 — Nikhilam sutra:\nStep 1: First digit 1 = first quotient digit.\nStep 2: 1+3 = 4 = second quotient digit. Q so far = 14.\nStep 3: Sum of all digits = 1+3+2 = 6 = Remainder.\nAnswer: Q=14, R=6.\nVerify: 14×9 + 6 = 126 + 6 = 132 ✓', hint: '(a) 95²: R=25, L=9×10=90→9025. (b) 36×34: R=24, L=12→1224. (c) 21×22: L=4,M=6,R=2→462. (d) 132÷9: Q=14, R=6.', reexplanation: 'All four worked examples with named techniques. (a) Ekadhikena squares; (b) Ekadhikena multiply; (c) ×22 method; (d) Nikhilam division.', sectionId: 7 },
  ],
}

export const ALL_MTH_QUIZZES: ChapterQuiz[] = [q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11]
export function getMthQuiz(chapterId: number): ChapterQuiz | undefined {
  return ALL_MTH_QUIZZES.find(q => q.chapterId === chapterId)
}
