// Sanskrit Quiz Content — Gyaanpravaha
// सुरभारती — All 8 chapters, 25 marks each

export type QuestionType = 'mcq' | 'single_word' | 'sentence' | 'long_answer'
export interface MCQOption { label: string; text: string }
export interface Question {
  id: number; type: QuestionType; marks: number; question: string
  options?: MCQOption[]; answer: string; reexplanation: string; hint?: string
}
export interface ChapterQuiz { chapterId: number; title: string; totalMarks: number; questions: Question[] }

const quiz1: ChapterQuiz = {
  chapterId: 1, title: 'Prarthana (Prayer)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'Which goddess is invoked in the first shloka of Prarthana?', options: [{ label: 'A', text: 'Lakshmi' }, { label: 'B', text: 'Saraswati (Sharada)' }, { label: 'C', text: 'Durga' }, { label: 'D', text: 'Parvati' }], answer: 'B', reexplanation: 'The first shloka begins "नमामि शारदां देवीम्" — I bow to Goddess Sharada. Sharada is another name for Saraswati, the goddess of knowledge, music, and arts. She is described as holding a veena and a book (वीणापुस्तकधारिणीम्).' },
    { id: 2, type: 'mcq', marks: 1, question: 'What does the second shloka (Appi Swarnamayi Lanka...) teach us?', options: [{ label: 'A', text: 'Gold is the most valuable thing' }, { label: 'B', text: 'Lanka is more beautiful than India' }, { label: 'C', text: 'Mother and motherland are greater than even heaven' }, { label: 'D', text: 'Lakshmana was Rama\'s favourite brother' }], answer: 'C', reexplanation: 'The second shloka spoken by Rama to Lakshmana says: "जननी जन्मभूमिश्च स्वर्गादपि गरीयसी" — Mother and motherland are greater even than heaven. Even though Lanka is made of gold, Rama says it does not appeal to him — his own homeland is more valuable.' },
    { id: 3, type: 'mcq', marks: 1, question: 'According to Shloka 3 (Bhartrhari), how does a WICKED person use wealth?', options: [{ label: 'A', text: 'For charity' }, { label: 'B', text: 'For gaining wisdom' }, { label: 'C', text: 'For arrogance / pride' }, { label: 'D', text: 'For protection of others' }], answer: 'C', reexplanation: 'Bhartrhari says: "धनं मदाय" — wealth is for arrogance/pride (for the wicked). The noble person uses wealth for charity (दानाय). The wicked uses knowledge for argument, wealth for arrogance, and power to harm others.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Lord Ganesha is described as "गौरीसुताय" — meaning?', options: [{ label: 'A', text: 'Son of Saraswati' }, { label: 'B', text: 'Son of Gauri (Parvati)' }, { label: 'C', text: 'Son of Vishnu' }, { label: 'D', text: 'Son of Brahma' }], answer: 'B', reexplanation: 'गौरीसुताय = son of Gauri. Gauri is a name of Goddess Parvati — who is the wife of Lord Shiva and the mother of Lord Ganesha. This is one of many names used in Shloka 4 to describe Ganesha.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What does "विघ्नेश्वराय" mean — one of Ganesha\'s names in Shloka 4?', options: [{ label: 'A', text: 'Lover of sweets' }, { label: 'B', text: 'Son of Shiva' }, { label: 'C', text: 'Lord of obstacles' }, { label: 'D', text: 'Destroyer of enemies' }], answer: 'C', reexplanation: 'विघ्नेश्वराय = Lord of obstacles. Vighna = obstacle, Ishvara = Lord. Ganesha is the lord and controller of obstacles — he can place obstacles to test us or remove them to help us succeed. That is why he is worshipped first before any new beginning.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "जन्मभूमि:" mean?', answer: 'Motherland / Land of birth', reexplanation: 'जन्मभूमि: = Janmabhumi = Motherland. Janma = birth, Bhumi = land/earth. The land where you were born. In the second shloka, Rama says जननी जन्मभूमिश्च स्वर्गादपि गरीयसी — mother and motherland are greater than heaven.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What does "गरीयसी" mean in the context of the second shloka?', answer: 'Greater / more valuable', reexplanation: 'गरीयसी = greater, more valuable, more weighty. From the same root as "guru" (heavy, important). In the shloka, it means that mother and motherland are गरीयसी — greater — even than heaven.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What are the two objects that Goddess Saraswati holds, as described in Shloka 1?', answer: 'Veena (musical instrument) and a book (pustaka)', reexplanation: 'Shloka 1 describes Saraswati as वीणापुस्तकधारिणीम् — the one who holds a veena and a book. The veena represents music, arts and harmony; the book represents knowledge and learning. Together they symbolise all that Saraswati governs.' },
    { id: 9, type: 'single_word', marks: 1, question: 'According to Shloka 3, what do the noble (साधु:) use their strength for?', answer: 'Protecting others (रक्षणाय)', reexplanation: 'According to Bhartrhari\'s Shloka 3, the noble person (साधु:) uses power/strength for रक्षणाय — for the protection of others. The wicked (खल:) uses strength for परपीडनाय — for harming others. The same resource produces opposite results depending on character.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What does "नमस्ते" literally mean in Sanskrit?', answer: 'Salutation / bow to you (Namas = bow, Te = to you)', reexplanation: 'नमस्ते = namas + te. Namas means salutation or bow, Te means to you. So नमस्ते = salutation to you / I bow to you. It is a respectful greeting — used both for greeting and for farewell in Indian culture.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "prayer" in a sentence explaining why we pray before beginning studies.', answer: 'A prayer before beginning studies reminds us to approach learning with humility — asking for the blessings of a higher power and dedicating our effort to something greater than ourselves.', hint: 'Think about what prayer does for the mind before learning begins.', reexplanation: 'The Prarthana chapter begins with a prayer to Saraswati before starting any study. Prayer is a way of humbling ourselves, focusing our mind, and dedicating our effort. In the Hindu tradition, invoking the blessing of the deity of learning before beginning study is an ancient practice.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "motherland" in a sentence inspired by Shloka 2.', answer: 'Even if our motherland is not the richest or most beautiful place on Earth, it is still the most precious to us — because it is where we were born and belong.', hint: 'Shloka 2 says the motherland is greater even than heaven. Think about why your home feels special.', reexplanation: 'The second shloka (from the Ramayana) teaches that the motherland is greater even than heaven. Rama says this while standing in golden Lanka. The key insight is that the value of a place is not in its material wealth but in its emotional and spiritual significance to you.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "character" in a sentence about Shloka 3 (Bhartrhari).', answer: 'Shloka 3 by Bhartrhari teaches that it is not what you have but your character that determines whether your knowledge, wealth and power will be used for good or for harm.', hint: 'Character determines how the same resources — knowledge, wealth, power — are used differently by the wicked vs the noble.', reexplanation: 'Bhartrhari\'s shloka is a profound statement about character. The same resources — knowledge, wealth, strength — produce completely different outcomes depending on the moral character of the person using them. The wicked use them to argue, show off and harm; the noble use them to learn, give and protect.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "remove obstacles" in a sentence about Lord Ganesha.', answer: 'Lord Ganesha is worshipped at the beginning of every new task because he is believed to remove obstacles from the path of those who seek his blessings.', hint: 'Ganesha\'s role as Vighnaharta (obstacle-remover) is why he is worshipped first.', reexplanation: 'Ganesha is called Vighnaharta (remover of obstacles) and Vighnesha (Lord of obstacles). He is worshipped before every new venture — a new year, a new business, a new journey, a new school year — because devotees believe he clears the path of difficulties and ensures success.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "humility" in a sentence about why students bow to Saraswati before studying.', answer: 'Bowing to Saraswati before studying is an act of humility — the student acknowledges that all knowledge comes from something greater than themselves.', hint: 'Humility means acknowledging that we do not know everything and that we need help to learn.', reexplanation: 'The act of prayer (नमामि — I bow) is fundamentally an act of humility. The student admits: I am small, knowledge is vast, I need divine blessing and guidance to learn. This is the opposite of arrogance — and the best attitude for any learner.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Write the meaning of all four shlokas in the Prarthana chapter. For each shloka, name the deity or subject, write the key Sanskrit line, and explain what it teaches us.', answer: 'The Prarthana chapter contains four shlokas. First, the prayer to Goddess Saraswati (Sharada): "नमामि शारदां देवीम् वीणापुस्तकधारिणीम्" — I bow to Goddess Sharada who holds a veena and a book. It teaches us to approach all learning with humility and to seek divine blessings before beginning study. Second, the verse from the Ramayana spoken by Rama to Lakshmana about the motherland: "जननी जन्मभूमिश्च स्वर्गादपि गरीयसी" — Mother and motherland are greater even than heaven. Even though Lanka is made of gold, Rama says it does not appeal to him. It teaches us to love and value our homeland above all material wealth. Third, the verse by Bhartrhari about knowledge: "विद्या विवादाय धनं मदाय शक्ति: परेषां परपीडनाय" — for the wicked, knowledge is for argument, wealth for arrogance, power to harm others. But for the noble person, the same things serve wisdom, charity and protection. It teaches us that character determines how we use our gifts. Fourth, the prayer to Lord Ganesha: "गौरीसुताय गणनाथ नमो नमस्ते" — salutation to the son of Gauri, Lord of the Ganas. Ganesha is the remover of obstacles and giver of boons, worshipped before every new beginning.', hint: 'Go through each shloka: (1) To whom/about whom, (2) the key Sanskrit line, (3) what it teaches. Cover all four in order.', reexplanation: 'Cover all four shlokas in order: (1) Saraswati/Sharada — veena and book — humility in learning; (2) Rama-Lakshmana/Motherland — janmabhumi greater than heaven — patriotism and love of homeland; (3) Bhartrhari/Knowledge — wicked vs noble use of vidya/dhana/shakti — character determines how gifts are used; (4) Ganesha — son of Gauri, Lord of Ganas, remover of obstacles — pray before new beginnings.' },
  ],
}

const quiz2: ChapterQuiz = {
  chapterId: 2, title: 'Vivekananda (Vivekanandah)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What was Vivekananda\'s name before he became a monk?', options: [{ label: 'A', text: 'Vishwanath Datta' }, { label: 'B', text: 'Narendradatt' }, { label: 'C', text: 'Ramakrishna' }, { label: 'D', text: 'Narayan Das' }], answer: 'B', reexplanation: 'पूर्वस्मिन् वयसि विवेकानन्दस्य नाम नरेन्द्रदत्त: आसीत् — In his earlier age, Vivekananda\'s name was Narendradatt. Vishwanath Datta was his father\'s name. He became known as Swami Vivekananda after becoming a monk.' },
    { id: 2, type: 'mcq', marks: 1, question: 'When did Narendra\'s father pass away?', options: [{ label: 'A', text: 'When Narendra was a child' }, { label: 'B', text: 'When Narendra became a graduate (स्नातक)' }, { label: 'C', text: 'After Narendra\'s Chicago speech' }, { label: 'D', text: 'When Narendra met Ramakrishna' }], answer: 'B', reexplanation: 'नरेन्द्र: यदा स्नातकोऽभवत् तदा तस्य पिता परलोकमगच्छत् — When Narendra became a graduate, at that time his father went to the other world (passed away). This left Narendra in great difficulty at a young age.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What happened when Ramakrishna Paramahamsa touched Narendra?', options: [{ label: 'A', text: 'Narendra became healthy' }, { label: 'B', text: 'Narendra entered a state of samadhi (deep meditation)' }, { label: 'C', text: 'Narendra decided to go to America' }, { label: 'D', text: 'Narendra became a graduate' }], answer: 'B', reexplanation: 'एकदा कस्याञ्चित् सभायां नरेन्द्र: रामकृष्ण-परमहंस महोदयस्य स्पर्शमधिगत्य समाधिस्थौभवत् — Once in some assembly, having received the touch of Ramakrishna Paramahamsa, Narendra entered into a state of samadhi.' },
    { id: 4, type: 'mcq', marks: 1, question: 'In which city and country was the World Parliament of Religions held in 1893?', options: [{ label: 'A', text: 'New York, USA' }, { label: 'B', text: 'London, England' }, { label: 'C', text: 'Chicago, USA' }, { label: 'D', text: 'Paris, France' }], answer: 'C', reexplanation: '1893 तमे वर्षे अमेरिका देशे शिकागो नाम नगरे विश्व धर्म सम्मेलनम् अभवत् — In the year 1893, in the city called Chicago in America, a World Parliament of Religions took place. Vivekananda\'s speech there made him world famous.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Which of the following is NOT one of Vivekananda\'s five teachings listed in the chapter?', options: [{ label: 'A', text: 'निर्भय: भव (Be fearless)' }, { label: 'B', text: 'कर्मयोगी भव (Be a Karmayogi)' }, { label: 'C', text: 'धनवान् भव (Be wealthy)' }, { label: 'D', text: 'राष्ट्रदेव: भव (See the nation as God)' }], answer: 'C', reexplanation: 'Vivekananda\'s five teachings are: निर्भय: भव (be fearless), तेजस्वी भव (be illustrious), श्रद्धावान् भव (be full of faith), कर्मयोगी भव (be a karmayogi), राष्ट्रदेव: भव (see the nation as God). "Become wealthy" is NOT one of his teachings.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "परलोकम् अगच्छत्" mean?', answer: 'Went to the other world / passed away', reexplanation: 'परलोकम् अगच्छत् = went to the other world. Paraloka = the other world (after death), Agachchhat = went. This is the Sanskrit way of saying "passed away." It appears in the chapter when describing the death of Narendra\'s father.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the Sanskrit word for "propagation" or "spreading" — used when describing Vivekananda spreading Indian culture?', answer: 'प्रचार: (Prachar)', reexplanation: 'प्रचार: = propagation, spreading. The chapter says: भारतीय संस्कृते: च प्रचारं अकरोत् — He propagated Indian culture. Prachar is still used in modern Hindi/Sanskrit to mean advertising, spreading a message, or propagation.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What is the Sanskrit synonym for "गुरु:" given in the समानार्थकशब्दान् list?', answer: 'शिक्षक: (Shikshak)', reexplanation: 'In the समानार्थकशब्दान् (synonyms) section of the chapter, गुरु: = शिक्षक: (teacher). Both words refer to a teacher, though in Indian tradition a guru carries a deeper meaning — a spiritual guide and mentor for life.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the antonym of "प्रशंसित:" (praised) given in the विलोमपदानि list?', answer: 'निन्दित: (Nindit) — condemned / criticised', reexplanation: 'In the विलोमपदानि (antonyms) section: प्रशंसित: × निन्दित:. Prashamsit = praised, Nindit = condemned or criticised. At Chicago, all listeners praised (प्रशंसितार: अभवन्) Vivekananda — the opposite of being criticised.' },
    { id: 10, type: 'single_word', marks: 1, question: 'Where is Vivekananda\'s temple located — "दक्षिण भारते समुद्रस्य मध्ये पर्वते"?', answer: 'In South India, on a rock in the middle of the sea (Kanyakumari, Tamil Nadu)', reexplanation: 'दक्षिण भारते समुद्रस्य मध्ये पर्वते तस्य मन्दिरम् अस्ति — In South India, on a rock in the middle of the sea, is his temple. This is the Vivekananda Rock Memorial in Kanyakumari, Tamil Nadu, inaugurated by India\'s President in 1970.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "samadhi" in a sentence about Vivekananda and Ramakrishna.', answer: 'When Ramakrishna Paramahamsa touched Narendra in an assembly, Narendra immediately entered a state of samadhi — a deep, spontaneous meditation — which ended only when the guru touched him again.', hint: 'Samadhi is a state of deep meditation or trance. Narendra entered it through Ramakrishna\'s touch.', reexplanation: 'Samadhi is the highest state of concentration and meditation in yoga and Indian philosophy. The extraordinary event in the chapter is that Narendra entered samadhi spontaneously through the touch of a great spiritual master — and could only come out of it through that same master\'s touch.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "fearless" in a sentence about Vivekananda\'s teachings.', answer: '"Be fearless" was Vivekananda\'s first and most fundamental teaching — he believed that fear was the root of weakness, and that a fearless mind could achieve anything.', hint: 'Nirbhay bhav — be fearless — was the first of his five great teachings.', reexplanation: 'निर्भय: भव (Be fearless) is the first of Vivekananda\'s five teachings. He believed that fear — of people, of failure, of judgment — was the main obstacle to human greatness. A fearless person is free to pursue truth, serve others, and fulfil their purpose.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "propagated" in a sentence about what Vivekananda did for Indian culture.', answer: 'After receiving his guru\'s blessing and wandering across India, Vivekananda propagated (spread) Indian culture and Vedantic philosophy across the world — particularly through his historic speech in Chicago in 1893.', hint: 'Propagated means spread widely. Vivekananda spread Indian culture (भारतीय संस्कृते: प्रचारम् अकरोत्).', reexplanation: 'The chapter says: भारतीय संस्कृते: च प्रचारं अकरोत् — he propagated Indian culture. Vivekananda brought the message of the Vedanta — the unity of all religions and the divinity of the human soul — to a global audience. His Chicago address began with "Sisters and Brothers of America" and brought the audience to their feet.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the word "karmayogi" in a sentence about what it means.', answer: 'A karmayogi is one who performs all their actions selflessly — without attachment to rewards — dedicating every action to the service of God or humanity.', hint: 'Karma = action, Yoga = union. A karmayogi works without desire for personal gain.', reexplanation: 'Karmayoga is a central teaching of the Bhagavad Gita, which deeply influenced Vivekananda. A Karmayogi performs their duty without being attached to the outcome — they work for the sake of service, not for personal reward. Vivekananda said: "Be a karmayogi" — work and serve without selfish motive.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "graduate" in a sentence about the timing of Narendra\'s father\'s death.', answer: 'At the very moment Narendra should have been celebrating becoming a graduate, tragedy struck — his father passed away, leaving him to face the world alone.', hint: 'Narendra\'s father died when he became a graduate (स्नातक) — at a time when he most needed support.', reexplanation: 'The timing of Vishwanath Datta\'s death was particularly difficult — it came exactly when Narendra (स्नातक: = graduate) had just completed his formal education and should have been starting a career. Instead, he was thrust into financial hardship, which ultimately led him toward spirituality.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Describe the life of Swami Vivekananda based on the Sanskrit passage in this chapter. Include: his original name, his father\'s name, how he met his guru, his historic achievement in 1893, his five key teachings, and the memorial built in his honour.', answer: 'According to the Sanskrit passage, Swami Vivekananda\'s original name was Narendradatt (नरेन्द्रदत्त:). His father\'s name was Vishwanath Datta (विश्वनाथदत्त:). When Narendra became a graduate (स्नातक:), his father passed away, leaving him in great difficulty. Once in an assembly, Narendra received the touch of Sri Ramakrishna Paramahamsa and immediately entered into a state of samadhi (deep meditation). Only his guru\'s touch ended the samadhi. From that day, Narendra made Ramakrishna his guru and performed tapas (spiritual penance). Knowing the command of his guru, he wandered across India and spread Indian culture (प्रचारम् अकरोत्). In 1893, at the World Parliament of Religions in Chicago, USA, he gave a speech that made all listeners his admirers, and his fame spread everywhere. His five key teachings are: Be fearless (निर्भय: भव), Be illustrious (तेजस्वी भव), Be full of faith (श्रद्धावान् भव), Be a karmayogi (कर्मयोगी भव), See the nation as God (राष्ट्रदेव: भव). His temple — the Vivekananda Rock Memorial — stands in South India on a rock in the sea, and was inaugurated by the President of India in 1970.', hint: 'Structure your answer in order: original name → father → how he met guru → samadhi → teaching → Chicago 1893 → five teachings → rock memorial.', reexplanation: 'Cover all these points from the chapter: original name = Narendradatt; father = Vishwanath Datta; met guru = Ramakrishna Paramahamsa\'s touch in assembly → samadhi; wandered India, spread Indian culture; 1893 Chicago World Parliament of Religions; five teachings (nirbhay, tejasvi, shraddhavan, karmayogi, rashtradev); temple in South India on sea rock, inaugurated by President in 1970.' },
  ],
}

const quiz3: ChapterQuiz = {
  chapterId: 3, title: 'Sanchalana Geetam (March Song)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What does "सञ्चलनगीतम्" mean?', options: [{ label: 'A', text: 'Patriotic prayer' }, { label: 'B', text: 'March song' }, { label: 'C', text: 'Evening hymn' }, { label: 'D', text: 'Battle cry' }], answer: 'B', reexplanation: 'सञ्चलनगीतम् = march song. Sanchalana = march/movement, Geetam = song. It is a patriotic poem designed to be recited while marching — as in a march past during Independence Day or Republic Day celebrations.' },
    { id: 2, type: 'mcq', marks: 1, question: 'In Stanza 2, which of the following is NOT a description of the brave soldier?', options: [{ label: 'A', text: 'मार्गदर्शक: (guide)' }, { label: 'B', text: 'देशरक्षक: (protector of nation)' }, { label: 'C', text: 'ज्ञानदाता: (giver of knowledge)' }, { label: 'D', text: 'शत्रुनाशक: (destroyer of enemies)' }], answer: 'C', reexplanation: 'Stanza 2 calls the soldier: मार्गदर्शक: (guide), देशरक्षक: (protector of the nation), शत्रुनाशक: (destroyer of enemies), and कालनागतक्षक: (slayer of the deadly serpent). ज्ञानदाता (giver of knowledge) is not mentioned — that is not one of the descriptions.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What does "साहसी सदा भव" mean?', options: [{ label: 'A', text: 'Be strong always' }, { label: 'B', text: 'Always be courageous' }, { label: 'C', text: 'March forward always' }, { label: 'D', text: 'Be a guide always' }], answer: 'B', reexplanation: 'साहसी सदा भव = always be courageous. Sahasi = courageous/daring, Sada = always, Bhav = be (command form). This is from Stanza 3 — the poem commands the veer (brave one) to be courageous at all times, not just occasionally.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What does the last line of the poem "सर्वदा जयो भवेत्" mean?', options: [{ label: 'A', text: 'Victory belongs to the strong' }, { label: 'B', text: 'May there always be victory' }, { label: 'C', text: 'India will always win' }, { label: 'D', text: 'March forward to victory' }], answer: 'B', reexplanation: 'सर्वदा जयो भवेत् = may there always be victory. Sarvada = always/forever, Jaya = victory, Bhavet = may there be (optative form — expressing a wish). The full line: भारतस्य गौरवाय सर्वदा जयो भवेत् — may there always be victory for the glory of India.' },
    { id: 5, type: 'mcq', marks: 1, question: 'Which of the following is an imperative (command) verb form used in the poem?', options: [{ label: 'A', text: 'अगच्छत् (he went)' }, { label: 'B', text: 'अस्ति (it is)' }, { label: 'C', text: 'एहि (come!)' }, { label: 'D', text: 'भवति (it becomes)' }], answer: 'C', reexplanation: 'एहि (come!) is an imperative (command) verb form. The poem uses several command forms: एहि (come!), विधेहि (show!), प्रदेहि (offer!), भव (be!), भज (embrace!), धर (hold!). Agachchhat, asti, and bhavati are all indicative forms (stating facts), not commands.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "वीरता" mean?', answer: 'Bravery / heroism / valour', reexplanation: 'वीरता = bravery, heroism, valour. It is the abstract noun form of वीर (brave/hero). The suffix -ta turns an adjective into a quality noun — so veera (brave) becomes veerata (bravery). The poem says वीरतां विधेहि (show/create bravery) and वीरतां सदा भज (always embrace bravery).' },
    { id: 7, type: 'single_word', marks: 1, question: 'What does "भारतीयसंस्कृति" mean?', answer: 'Indian culture', reexplanation: 'भारतीयसंस्कृति = Indian culture. Bharatiya = Indian (relating to Bharat/India), Sanskriti = culture (from Sanskrit — that which has been cultivated and refined). The poem says: भारतीयसंस्कृतिं मानसे सदा धर — always hold Indian culture in your heart.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What does "पदं पदं पुरश्चलेत्" mean?', answer: 'Let us march forward step by step', reexplanation: 'पदं पदं पुरश्चलेत् = step by step, let us march forward. Padam = step/foot, Puras = forward, Chalet = should move/march. This is the opening line of Stanza 4 — the call to march forward with enthusiasm and purpose.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What does "उत्साह" mean?', answer: 'Enthusiasm / zeal / energy', reexplanation: 'उत्साह = enthusiasm, energy, zeal, inspiration. The poem says सोत्साहं मनो भवेत् — let the mind be filled with enthusiasm. Utsaha is one of the most celebrated Sanskrit virtues — it is the inner fire that drives all great achievement.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What does "गौरव" mean?', answer: 'Honour / glory / pride', reexplanation: 'गौरव = honour, glory, pride, dignity. From the same root as guru (heavy, weighty, important) — gaurav is that which gives weight and dignity to something. The poem: भारतस्य गौरवाय = for the glory of India.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "valour" in a sentence about Stanza 1 of the march song.', answer: 'Stanza 1 calls upon the brave soldier to show his valour and offer his life for the protection of India — a call to the highest form of courage and sacrifice.', hint: 'Valour means great courage in the face of danger. Stanza 1 says: वीरतां विधेहि — show your bravery.', reexplanation: 'Valour (वीरता) is the subject of Stanza 1. The poem calls out to the veer (brave one) and commands: show bravery (वीरताम् विधेहि), offer your life for India\'s protection (भारतस्य रक्षणाय जीवनम् प्रदेहि). This is the highest expression of valour — the willingness to sacrifice everything for one\'s country.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "protector" in a sentence about how the poem describes the soldier.', answer: 'The poem calls the soldier the "देशरक्षक" — the protector of the nation — honouring the role of those who keep the country safe from all threats.', hint: 'देशरक्षक: = protector of the nation. This is one of the descriptions in Stanza 2.', reexplanation: 'Stanza 2 gives the soldier four titles: मार्गदर्शक: (guide), देशरक्षक: (protector of nation), शत्रुनाशक: (destroyer of enemies), कालनागतक्षक: (slayer of the deadly serpent). "Desharaksak" — nation protector — is perhaps the most fundamental of these roles.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the word "culture" in a sentence about Stanza 3 of the poem.', answer: 'Stanza 3 asks us to always hold Indian culture (भारतीयसंस्कृतिम्) in our hearts — reminding us that true patriotism includes cherishing the art, values, and wisdom of our civilisation.', hint: 'भारतीयसंस्कृतिम् मानसे सदा धर — always hold Indian culture in your mind/heart.', reexplanation: 'The third stanza connects bravery (वीरता) with culture (संस्कृति). A true patriot is not just physically brave — they also carry the values, arts, wisdom and traditions of their civilisation in their heart. Holding Indian culture in the mind means understanding what we are protecting and why it is worth protecting.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "step by step" in a sentence about Stanza 4.', answer: 'Stanza 4 reminds us that great journeys are completed step by step — पदं पदं पुरश्चलेत् — marching forward consistently, with enthusiasm, is how victory is achieved for the glory of India.', hint: 'पदं पदं = step by step. Stanza 4 is about marching forward consistently and enthusiastically.', reexplanation: 'The final stanza is about sustained forward movement: पदं पदं पुरश्चलेत् (step by step march forward), सोत्साहं मनो भवेत् (with enthusiastic mind), भारतस्य गौरवाय (for the glory of India), सर्वदा जयो भवेत् (may there always be victory). The message: march consistently with enthusiasm and victory will come.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "enthusiasm" in a sentence about what the poem asks of us.', answer: 'The poem asks us to march forward with enthusiasm — सोत्साहं मनो भवेत् — because it is not just physical effort but the enthusiasm of the mind that makes any march, any effort, truly powerful.', hint: 'उत्साह = enthusiasm. The poem says the mind should be filled with enthusiasm as we march forward.', reexplanation: 'Utsaha (enthusiasm) is the inner quality that the poem asks for in Stanza 4. Physical marching without enthusiasm is meaningless. The poem asks that the mind (मन:) be sotsaham — filled with enthusiasm. This applies to all endeavours: study, work, sports, service — enthusiasm of mind multiplies the effect of physical effort.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Write the meaning of all four stanzas of the Sanchalana Geetam. For each stanza, write the first line in Sanskrit and explain what it calls upon us to do or be.', answer: 'The Sanchalana Geetam (March Song) has four stanzas. Stanza 1 begins: "एहि एहि वीर रे" — Come, come, O brave one! It calls upon the brave soldier to show bravery (वीरतां विधेहि) and offer his life for the protection of India (भारतस्य रक्षणाय जीवनं प्रदेहि). Stanza 2 begins: "त्वं हि मार्गदर्शक:" — You are indeed the guide. It lists four roles of the soldier: guide (मार्गदर्शक:), protector of the nation (देशरक्षक:), destroyer of enemies (शत्रुनाशक:), and slayer of the deadly serpent of time (कालनागतक्षक:). Stanza 3 begins: "साहसी सदा भव" — Always be courageous. It commands us to always embrace bravery (वीरतां सदा भज) and to always hold Indian culture in our hearts (भारतीयसंस्कृतिं मानसे सदा धर). Stanza 4 begins: "पदं पदं पुरश्चलेत्" — Let us march forward step by step. It calls for an enthusiastic mind (सोत्साहं मनो भवेत्) and prays: may there always be victory for the glory of India (भारतस्य गौरवाय सर्वदा जयो भवेत्).', hint: 'Go through each stanza: write the first line in Sanskrit, then explain what it says and what it calls upon us to do/be.', reexplanation: 'Cover all four stanzas: Stanza 1 (एहि एहि वीर रे — come O brave one, show bravery, offer life for India); Stanza 2 (त्वं हि मार्गदर्शक: — you are guide, protector, destroyer of enemies, slayer of time\'s serpent); Stanza 3 (साहसी सदा भव — always be courageous, hold Indian culture in heart); Stanza 4 (पदं पदं पुरश्चलेत् — march step by step with enthusiasm, may there always be victory for India\'s glory).' },
  ],
}

const quiz4: ChapterQuiz = {
  chapterId: 4, title: 'Sanskritabhasha Grihe Grihe (Vocabulary)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What does "वातायनम्" mean?', options: [{ label: 'A', text: 'Door' }, { label: 'B', text: 'Fan' }, { label: 'C', text: 'Window' }, { label: 'D', text: 'Bag' }], answer: 'C', reexplanation: 'वातायनम् = window. It is a beautiful compound: Vata (wind/air) + Ayana (path/passage) = the path/passage for wind. A window is literally "the path for air" in Sanskrit — a poetic and accurate description.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What is the Sanskrit word for "pen"?', options: [{ label: 'A', text: 'मार्जक:' }, { label: 'B', text: 'लेखनी' }, { label: 'C', text: 'लेखन पुस्तिका' }, { label: 'D', text: 'स्यूत:' }], answer: 'B', reexplanation: 'लेखनी = pen. From the root likh (to write) — lekhani is "that which writes." मार्जक: = eraser, लेखन पुस्तिका = notebook, स्यूत: = bag. The root likh also gives us lekhak (writer/author) and lekhan (writing).' },
    { id: 3, type: 'mcq', marks: 1, question: 'What does "आम्रम्" mean?', options: [{ label: 'A', text: 'Apple' }, { label: 'B', text: 'Banana' }, { label: 'C', text: 'Mango' }, { label: 'D', text: 'Orange' }], answer: 'C', reexplanation: 'आम्रम् = mango. It is the Sanskrit word for mango, and the Hindi word "aam" comes directly from this. Interesting fact: the English word "mango" comes from the Tamil word "mangai" which itself traces back to Sanskrit.' },
    { id: 4, type: 'mcq', marks: 1, question: 'Which Sanskrit word for a fruit gave the English language its common name for that fruit?', options: [{ label: 'A', text: 'कदली (banana)' }, { label: 'B', text: 'नारङ्गम् (orange)' }, { label: 'C', text: 'सेवम् (apple)' }, { label: 'D', text: 'पनसम् (jackfruit)' }], answer: 'B', reexplanation: 'नारङ्गम् (orange) gave the world the word "orange." The Sanskrit word narangam → Persian narang → Arabic naranj → Spanish naranja → English orange. Sanskrit was the origin of this word\'s global journey through many languages.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What does "मधुकर्कटी" mean?', options: [{ label: 'A', text: 'Watermelon' }, { label: 'B', text: 'Pomegranate' }, { label: 'C', text: 'Muskmelon' }, { label: 'D', text: 'Jackfruit' }], answer: 'C', reexplanation: 'मधुकर्कटी = muskmelon. It is a compound: Madhu (sweet/honey) + Karkata (melon/crab). So muskmelon is literally "the sweet melon" in Sanskrit — an accurate description of this honeyed fruit.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What is the Sanskrit word for "eraser"?', answer: 'मार्जक: (Marjak)', reexplanation: 'मार्जक: = eraser. From the root "marj" meaning to clean or wipe. An eraser cleans away writing — it is the मार्जक (cleaner/wiper). The same root gives us the word marjana (cleaning).' },
    { id: 7, type: 'single_word', marks: 1, question: 'What does "कदली" mean?', answer: 'Banana', reexplanation: 'कदली = banana. The Sanskrit word for banana. Kadalivana means a banana grove. Interestingly, the banana plant is called Kadalitaru (kadalee tree) in Sanskrit — the banana is one of the oldest cultivated fruits in India.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What is the Sanskrit word for "bag" (school bag)?', answer: 'स्यूत: (Syoot)', reexplanation: 'स्यूत: = bag, satchel. The word refers to a bag or satchel, specifically a bag that is sewn (from the root "siv" = to sew). Your school bag is a स्यूत: in Sanskrit.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What does "दाडिमम्" mean?', answer: 'Pomegranate', reexplanation: 'दाडिमम् = pomegranate. The Sanskrit word for pomegranate. In Hindi it is called "anar" (from Persian), but Sanskrit uses this ancient word. Pomegranate is considered sacred and auspicious in many Sanskrit texts.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What does "गृहे-गृहे" mean in the chapter title "संस्कृतभाषा गृहे-गृहे"?', answer: 'In every home / house to house', reexplanation: 'गृहे-गृहे = in every home, house to house. Griha = home, Grihe = in the home (locative singular). The repetition "grihe-grihe" in Sanskrit means "in every home, in every home." The title means "Sanskrit language in every home" — the goal of making Sanskrit a living spoken language.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the Sanskrit word "लेखनी" in an English sentence explaining what it means and how it is formed.', answer: 'लेखनी (lekhani) means "pen" in Sanskrit — it comes from the root "likh" meaning to write, so a lekhani is literally "that which writes."', hint: 'Lekhani = pen. It comes from the Sanskrit root likh (to write). Think about how the name describes what the pen does.', reexplanation: 'The Sanskrit root likh means to write. Adding the suffix -ani creates the instrument noun — the thing that performs the action. So likh + ani = lekhani = that which writes = pen. This is a common Sanskrit word-formation pattern.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "compound" to explain how "वातायनम्" (window) is formed.', answer: '"वातायनम्" (window) is a compound word formed by joining "वात" (wind/air) and "अयन" (path/passage) — the window is literally "the path for wind."', hint: 'A compound word is made by joining two or more words. Vataynam = Vata (wind) + Ayana (path).', reexplanation: 'Vataynam is a beautiful Sanskrit compound. Vata = wind or air, Ayana = path or passage (from the root "i" = to go). Together: "the path through which wind passes" = window. Sanskrit compound words are called samasa and are very common in the language.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the Sanskrit word "आम्रम्" in a sentence showing your knowledge of its connection to Hindi.', answer: 'The Sanskrit word "आम्रम्" for mango became "आम" in Hindi — showing how most Hindi words for everyday things trace back to Sanskrit roots.', hint: 'Aam in Hindi for mango comes directly from the Sanskrit Aamram. The relationship shows how Hindi developed from Sanskrit.', reexplanation: 'The Sanskrit word Aamram → Hindi Aam. This direct connection illustrates how Hindi and other North Indian languages are daughters of Sanskrit. Most food words in Hindi (and many other Indian languages) trace directly back to Sanskrit roots.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the phrase "Sanskrit in everyday life" in a sentence about the goal of this chapter.', answer: 'This chapter uses Sanskrit in everyday life — giving Sanskrit names to the objects around us, like the pen (लेखनी), the window (वातायनम्), and the mango (आम्रम्) — to show that Sanskrit can be a living spoken language.', hint: 'The chapter title "संस्कृतभाषा गृहे-गृहे" means Sanskrit language in every home. The goal is to make Sanskrit part of daily life.', reexplanation: 'The movement to use Sanskrit in everyday life (Sanskrit Bharati movement) aims to revive Sanskrit as a spoken language. Chapters like this one — giving Sanskrit names to everyday objects — are an important first step. When you call your eraser a "marjak" or your bag a "syoot," you are bringing Sanskrit into your daily reality.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "pomegranate" in a sentence with its Sanskrit name "दाडिमम्"।', answer: 'The pomegranate — called "दाडिमम्" (dadimam) in Sanskrit — has been celebrated in Indian culture for thousands of years as a symbol of prosperity and fertility.', hint: 'Dadimam = pomegranate. Think about its Sanskrit name and cultural significance.', reexplanation: 'The pomegranate (दाडिमम्) is one of the most ancient and culturally significant fruits in India. It appears in Sanskrit literature, Ayurveda (where it is called dadima and valued for its medicinal properties), and Hindu religious symbolism. Its Hindi name "anar" comes from Persian, but Sanskrit uses the ancient word dadimam.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'List all 20 Sanskrit words from this chapter with their English meanings, divided into their two groups (classroom objects and fruits). Then explain the meaning of the chapter title "संस्कृतभाषा गृहे-गृहे."', answer: 'Classroom objects (1-10): 1. मापिका = Scale/ruler; 2. पुन: पूरणी = Refill; 3. लेखन पुस्तिका = Notebook; 4. मार्जक: = Eraser; 5. लेखनी = Pen; 6. स्यूत: = Bag; 7. व्यजनम् = Fan; 8. वातायनम् = Window; 9. आसन्द: = Chair; 10. उत्पीठिका = Stool. Fruits (11-20): 11. सुधाखण्ड = Chalk; 12. आम्रम् = Mango; 13. द्राक्षा = Grapes; 14. कदली = Banana; 15. सेवम् = Apple; 16. कलिङ्गम् = Watermelon; 17. मधुकर्कटी = Muskmelon; 18. नारङ्गम् = Orange; 19. पनसम् = Jackfruit; 20. दाडिमम् = Pomegranate. The chapter title "संस्कृतभाषा गृहे-गृहे" means "Sanskrit language in every home." Griha = home, Grihe = in the home (locative), and the repetition grihe-grihe means "in every home, in every home." The goal is to make Sanskrit a living, spoken language used in everyday life — not just in temples and textbooks.', hint: 'List all 20 words in two groups of 10. Then explain the title: Sanskrit language (संस्कृतभाषा), in every home (गृहे-गृहे = repetition meaning everywhere).', reexplanation: 'List all 20 words correctly in both groups. Then for the title: संस्कृतभाषा = Sanskrit language; गृहे = in the home (locative); गृहे-गृहे = in every home (repetition for emphasis). The title expresses the aspiration of the Sanskrit revival movement — to bring Sanskrit back into daily household use across India.' },
  ],
}

const quiz5: ChapterQuiz = {
  chapterId: 5, title: 'Sankhyah (Numbers 21-40)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What is the Sanskrit word for the number 25?', options: [{ label: 'A', text: 'पञ्चविंशति:' }, { label: 'B', text: 'पञ्चत्रिंशत्' }, { label: 'C', text: 'चतुर्विंशति:' }, { label: 'D', text: 'षड्विंशति:' }], answer: 'A', reexplanation: 'पञ्चविंशति: = 25. Pancha (5) + Vimshati (20) = 25. पञ्चत्रिंशत् = 35, चतुर्विंशति: = 24, षड्विंशति: = 26. The pattern for 21-29 is: unit + विंशति:.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What is the Sanskrit word for 30?', options: [{ label: 'A', text: 'एकत्रिंशत्' }, { label: 'B', text: 'त्रिंशत्' }, { label: 'C', text: 'त्रयोविंशति:' }, { label: 'D', text: 'चत्वारिंशत्' }], answer: 'B', reexplanation: 'त्रिंशत् = 30. It is a standalone word — the base number for thirty. एकत्रिंशत् = 31, त्रयोविंशति: = 23, चत्वारिंशत् = 40. त्रिंशत् comes from tri (3) × dasha (10) = 30.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What pattern is used for numbers 31-39?', options: [{ label: 'A', text: 'Unit + विंशति:' }, { label: 'B', text: 'Unit + त्रिंशत्' }, { label: 'C', text: 'Unit + चत्वारिंशत्' }, { label: 'D', text: 'त्रिंशत् + Unit' }], answer: 'B', reexplanation: 'Numbers 31-39 follow the pattern: Unit + त्रिंशत्. So 31 = एक + त्रिंशत् = एकत्रिंशत्; 37 = सप्त + त्रिंशत् = सप्तत्रिंशत्. Numbers 21-29 use the pattern unit + विंशति: instead.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What is the Sanskrit word for 38?', options: [{ label: 'A', text: 'अष्टाविंशति:' }, { label: 'B', text: 'अष्टात्रिंशत्' }, { label: 'C', text: 'नवत्रिंशत्' }, { label: 'D', text: 'नवविंशति:' }], answer: 'B', reexplanation: 'अष्टात्रिंशत् = 38. Ashta (8) + Trimshat (30) = 38. अष्टाविंशति: = 28 (8 + 20), नवत्रिंशत् = 39 (9 + 30), नवविंशति: = 29 (9 + 20). Note that 28 uses अष्टा (with the longer a) while 38 also uses अष्टा.' },
    { id: 5, type: 'mcq', marks: 1, question: 'The word "पञ्च" (five) gave us which modern Sanskrit/Hindi word?', options: [{ label: 'A', text: 'Panchayat' }, { label: 'B', text: 'Panchal' }, { label: 'C', text: 'Panjim' }, { label: 'D', text: 'All of the above' }], answer: 'A', reexplanation: 'पञ्च (Pancha = five) gave us पञ्चायत् (Panchayat — originally an assembly of five elders). It also gave us Pancha Mahavratas (five great vows of Jainism), Panchatantra (five books of wisdom), and Panchsheel (five principles).' },
    { id: 6, type: 'single_word', marks: 1, question: 'Write the Sanskrit word for 22.', answer: 'द्राविंशति: (Dvavimshati)', reexplanation: 'द्राविंशति: = 22. Dva/Draa (2) + Vimshati (20) = 22. Note that the unit number "two" changes its form slightly when combined: dva → draa in this compound. This is an example of sandhi (sound combination) in Sanskrit numbers.' },
    { id: 7, type: 'single_word', marks: 1, question: 'Write the Sanskrit word for 33.', answer: 'त्रयस्त्रिंशत् (Trayastrimshat)', reexplanation: 'त्रयस्त्रिंशत् = 33. Traya (3, in the form traya) + s + Trimshat (30) = 33. Note the connecting "s" sound between traya and trimshat — this is another example of sandhi in Sanskrit compounds. The form of "three" changes from tri to traya to trayo depending on the context.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What does "सङ्ख्या" mean?', answer: 'Number / numeral', reexplanation: 'सङ्ख्या = number, numeral. It is also the name of one of India\'s oldest philosophical systems — Sankhya Darshana — which involves a systematic enumeration and categorisation of all aspects of reality.' },
    { id: 9, type: 'single_word', marks: 1, question: 'Write the Sanskrit word for 40.', answer: 'चत्वारिंशत् (Chatvarimshhat)', reexplanation: 'चत्वारिंशत् = 40. This is a special standalone form — it does not follow the simple unit + vimshati/trimshat pattern. Chatvara relates to the number four (chatur), and the compound means 4 × 10 = 40. It is one of the irregular forms in Sanskrit numbers.' },
    { id: 10, type: 'single_word', marks: 1, question: 'The word "नव" (nava) in Sanskrit has two meanings. What are they?', answer: 'Nine (9) and New', reexplanation: 'नव (Nava) has two meanings in Sanskrit: (1) Nine — the number 9, and (2) New — as in नवीन (new/fresh). This dual meaning is interesting: Navaratri = nine nights of the goddess; but also Nava = new. The word "novel" in English comes from the Latin "novus" which shares the same ancient Indo-European root as Sanskrit "nava."' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "pattern" in a sentence explaining how Sanskrit numbers 21-29 work.', answer: 'Sanskrit numbers from 21 to 29 follow a clear pattern — the unit number comes first, followed by विंशति: (twenty) — so 21 is एकविंशति: (one-twenty) and 27 is सप्तविंशति: (seven-twenty).', hint: 'The pattern is: unit number + विंशति: for all numbers from 21 to 29.', reexplanation: 'The pattern unit + Vimshati works for all numbers 21-29. Just put the unit first and add vimshati: 21 = eka + vimshati = ekavimshati, 22 = dva + vimshati = dvavimshati, and so on up to 29 = nava + vimshati = navavimshati.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "decimal" in a sentence about India\'s contribution to mathematics.', answer: 'India gave the world the decimal system — the system of tens used by every country today — and Sanskrit was the language in which this mathematical revolution was first expressed.', hint: 'The decimal system (based on tens) was developed in India. Sanskrit number words show this ten-based structure.', reexplanation: 'The decimal system — counting in tens — was one of India\'s greatest contributions to world mathematics. Zero (shunya), the decimal system, and the numerals 1-9 all originated in India. Sanskrit words for numbers show this structure: vimshati (20 = 2×10), trimshat (30 = 3×10), chatvarimshhat (40 = 4×10).' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the number "सप्त" (seven) in a sentence about Indian culture.', answer: 'The number "सप्त" (seven) is deeply significant in Indian culture — Saptapadi (seven steps of the wedding), Saptasindhu (seven rivers), and Saptarishi (seven great sages) all use this sacred Sanskrit number.', hint: 'Sapta = seven. Think of Sanskrit/Hindi words that begin with "sapt" — Saptapadi, Saptasindhu, Saptarishi.', reexplanation: 'The number seven (sapta) appears throughout Indian culture: Saptapadi (the seven steps of the Hindu wedding ceremony), Saptasindhu (the region of seven rivers — the name the Aryans gave to Punjab), Saptarishi (the seven great sages of Hindu tradition), and the seven musical notes (saptaswara).' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the Sanskrit number "एकविंशति:" (21) in a sentence.', answer: 'India\'s 21st Prime Minister... or: A class of एकविंशति: (21) students went on a field trip to the science museum.', hint: 'एकविंशति: = 21. Use it in a sentence about 21 of something.', reexplanation: 'एकविंशति: (21) follows the pattern eka (1) + vimshati (20) = 21. Use it in any sentence that involves the number 21 — it could be about 21 students, 21 days, 21 questions, or any other group of 21.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the Sanskrit word "अष्ट" (eight) in a sentence about yoga.', answer: 'The word "अष्टांग" yoga — from "अष्ट" (eight) + "अंग" (limb) — refers to the eight-limbed yoga system of Patanjali, showing how Sanskrit number knowledge appears in everyday wellness practice.', hint: 'Ashta = eight. Ashtanga yoga = eight-limbed yoga. Think of other eight-related Sanskrit compounds.', reexplanation: 'Ashta (eight) appears in many important Sanskrit compounds: Ashtanga (eight-limbed — Patanjali\'s yoga system), Ashtami (the eighth day of the lunar fortnight — Janmashtami, the birthday of Krishna), and Ashta Lakshmi (the eight forms of Goddess Lakshmi).' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Write all 20 Sanskrit numbers from 21 to 40. Then explain the pattern for (a) numbers 21-29, (b) number 30, (c) numbers 31-39, and (d) number 40.', answer: 'The 20 Sanskrit numbers from 21 to 40 are: 21-एकविंशति:, 22-द्राविंशति:, 23-त्रयोविंशति:, 24-चतुर्विंशति:, 25-पञ्चविंशति:, 26-षड्विंशति:, 27-सप्तविंशति:, 28-अष्टाविंशति:, 29-नवविंशति:, 30-त्रिंशत्, 31-एकत्रिंशत्, 32-द्रात्रिंशत्, 33-त्रयस्त्रिंशत्, 34-चतुस्त्रिंशत्, 35-पञ्चत्रिंशत्, 36-षट्त्रिंशत्, 37-सप्तत्रिंशत्, 38-अष्टात्रिंशत्, 39-नवत्रिंशत्, 40-चत्वारिंशत्. The patterns are: (a) Numbers 21-29 follow: unit number + विंशति: (twenty). The unit comes first, followed by vimshati. (b) Number 30 = त्रिंशत् — a standalone word, from tri (3) × dasha (10). (c) Numbers 31-39 follow: unit number + त्रिंशत् (thirty). Same pattern as 21-29 but using trimshat instead of vimshati. (d) Number 40 = चत्वारिंशत् — a standalone word, from chatvara (four) × dasha (10). It does not follow the regular unit+ten pattern.', hint: 'List all 20 numbers, then explain the four patterns: 21-29 (unit+vimshati), 30 (trimshat standalone), 31-39 (unit+trimshat), 40 (chatvarimshhat standalone).', reexplanation: 'List all 20 numbers correctly. Then explain the patterns clearly: 21-29 = unit+vimshati:; 30 = trimshat (standalone, 3×10); 31-39 = unit+trimshat; 40 = chatvarimshhat (standalone, 4×10). Note that 30 and 40 are standalone special forms — they do not follow the regular pattern.' },
  ],
}

const quiz6: ChapterQuiz = {
  chapterId: 6, title: 'Sandhi (Combination of Letters)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What does "Sandhi" literally mean?', options: [{ label: 'A', text: 'Grammar rule' }, { label: 'B', text: 'Junction / combination' }, { label: 'C', text: 'Vowel change' }, { label: 'D', text: 'Consonant merge' }], answer: 'B', reexplanation: 'Sandhi literally means junction or combination — the point where two sounds meet and combine. It comes from sam (together) + dhi (to hold/join). In Sanskrit, when two words are placed next to each other, the sounds at their junction combine according to specific rules.' },
    { id: 2, type: 'mcq', marks: 1, question: 'In Savarna Dirgha Sandhi, what happens when इ/ई + इ/ई combine?', options: [{ label: 'A', text: 'They become आ' }, { label: 'B', text: 'They become ई' }, { label: 'C', text: 'They become ए' }, { label: 'D', text: 'They become ओ' }], answer: 'B', reexplanation: 'In Savarna Dirgha Sandhi, इ/ई + इ/ई = ई. This is the rule: similar vowels combine into one long vowel. So नदी + इव = नदीव (like a river); कपि + ईश: = कपीश: (Lord of monkeys). The short and long versions of the same vowel are "savarna" (same class).' },
    { id: 3, type: 'mcq', marks: 1, question: 'What type of Sandhi creates "गणेश:" from "गण + ईश:"?', options: [{ label: 'A', text: 'Savarna Dirgha Sandhi' }, { label: 'B', text: 'Vyanjana Sandhi' }, { label: 'C', text: 'Guna Sandhi' }, { label: 'D', text: 'Visarga Sandhi' }], answer: 'C', reexplanation: 'गण + ईश: = गणेश: is Guna Sandhi. The rule: अ/आ + इ/ई = ए. Here: गण (ending in अ) + ईश: (starting with ई) → the अ and ई combine to form ए, giving गणेश:. This is how Lord Ganesha\'s name is formed through Sanskrit grammar!' },
    { id: 4, type: 'mcq', marks: 1, question: 'What is the Sandhi result of "महा + उत्सव:"?', options: [{ label: 'A', text: 'महाउत्सव:' }, { label: 'B', text: 'महेत्सव:' }, { label: 'C', text: 'महोत्सव:' }, { label: 'D', text: 'महौत्सव:' }], answer: 'C', reexplanation: 'महा + उत्सव: = महोत्सव: (great festival). This is Guna Sandhi rule ii: आ + उ = ओ. महा (ending in आ) + उत्सव: (starting with उ) → the आ and उ combine to form ओ, giving महोत्सव:.' },
    { id: 5, type: 'mcq', marks: 1, question: 'What is the Sandhi result of "पुस्तक + आलय:"?', options: [{ label: 'A', text: 'पुस्तकआलय:' }, { label: 'B', text: 'पुस्तकालय:' }, { label: 'C', text: 'पुस्तकेलय:' }, { label: 'D', text: 'पुस्तकोलय:' }], answer: 'B', reexplanation: 'पुस्तक + आलय: = पुस्तकालय: (library!). This is Savarna Dirgha Sandhi: अ + आ = आ. पुस्तक (ending in अ) + आलय: (starting with आ) → the अ and आ combine into one long आ, giving पुस्तकालय: — the house of books = library.' },
    { id: 6, type: 'single_word', marks: 1, question: 'Solve this Sandhi: देव + इन्द्र: = ?', answer: 'देवेन्द्र: (Devendra)', reexplanation: 'देव + इन्द्र: = देवेन्द्र: (Indra, king of gods). Guna Sandhi rule i: अ + इ = ए. देव (ending in अ) + इन्द्र: (starting with इ) → the अ and इ combine to form ए, giving देवेन्द्र:.' },
    { id: 7, type: 'single_word', marks: 1, question: 'Solve this Sandhi: अति + इव = ?', answer: 'अतीव (Ateeva)', reexplanation: 'अति + इव = अतीव (extremely/very much). Savarna Dirgha Sandhi: इ + इ = ई. अति (ending in इ) + इव (starting with इ) → the two इ sounds combine into one long ई, giving अतीव. Ateeva is commonly used in Sanskrit to mean "very much" or "extremely."' },
    { id: 8, type: 'single_word', marks: 1, question: 'Solve this Sandhi: गङ्गा + उदक: = ?', answer: 'गङ्गोदक: (Gangodakah)', reexplanation: 'गङ्गा + उदक: = गङ्गोदक: (water of the Ganga). Guna Sandhi: आ + उ = ओ. गङ्गा (ending in आ) + उदक: (starting with उ) → आ and उ combine to form ओ, giving गङ्गोदक:.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What does "दीर्घ" mean in Sanskrit grammar?', answer: 'Long (as in a long vowel)', reexplanation: 'दीर्घ = long. In Sanskrit phonetics, vowels can be short (hrasva — one mora) or long (dirgha — two morae, taking twice as long to pronounce). The Savarna Dirgha Sandhi rule substitutes similar short and long vowels with a single long (dirgha) vowel.' },
    { id: 10, type: 'single_word', marks: 1, question: 'Solve this Sandhi: यथा + उचितम् = ?', answer: 'यथोचितम् (Yathochitam)', reexplanation: 'यथा + उचितम् = यथोचितम् (as appropriate/fitting). Guna Sandhi: आ + उ = ओ. यथा (ending in आ) + उचितम् (starting with उ) → आ and उ combine to form ओ, giving यथोचितम्. This word means "as is fitting" or "appropriately."' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the word "junction" in a sentence explaining what Sandhi is.', answer: 'Sandhi is the Sanskrit term for the junction between two words — where the final sound of one word and the first sound of the next combine and change according to precise rules.', hint: 'Sandhi literally means junction or combination. Think of it as the point where two words meet.', reexplanation: 'Sandhi is the phenomenon that occurs at the junction of two words in Sanskrit. When words are placed next to each other, their boundary sounds change according to systematic rules. This is what gives Sanskrit its musical, flowing quality when spoken correctly.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the name "पुस्तकालय:" in a sentence, explaining how it is formed through Sandhi.', answer: '"पुस्तकालय:" (library) is formed through Savarna Dirgha Sandhi — पुस्तक (book) + आलय: (house) → the final अ of pustaka and the initial आ of alayah combine to form one long आ — giving पुस्तकालय: = the house of books.', hint: 'Pustakalaya = pustaka (book) + alayah (house) — Savarna Dirgha Sandhi: a + aa = aa.', reexplanation: 'Pustakalayah is a perfect teaching example of Sandhi. Pustaka (book) ends in अ. Alayah (house) begins with आ. Rule: अ + आ = आ (Savarna Dirgha Sandhi). Result: pustaka + alayah = pustakalayah = library (literally, house of books).' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the name "महेश:" in a sentence, explaining the Guna Sandhi that created it.', answer: '"महेश:" is one of the names of Lord Shiva, formed through Guna Sandhi: महा (great) + ईश: (Lord) → आ + ई = ए, giving महेश: — the Great Lord.', hint: 'Mahesh = Maha + Esha. Guna Sandhi: aa + ii = e.', reexplanation: 'Mahesh (one of Shiva\'s names) is formed by Guna Sandhi. Maha = great (ending in आ), Eshah = Lord (starting with ई). Rule ii of Guna Sandhi: आ + ई = ए. So: Maha + Eeshah → Mahesh. A perfect example of how Sandhi creates famous names.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the word "savarna" in a sentence explaining what kind of vowels combine in Savarna Dirgha Sandhi.', answer: 'In Savarna Dirgha Sandhi, savarna vowels — vowels of the same class, like the short and long versions of the same vowel — combine into one single long vowel when they meet.', hint: 'Savarna = same class/similar. Short and long versions of the same vowel are savarna (e.g. a and aa are savarna; i and ii are savarna).', reexplanation: 'Savarna means "same class" in Sanskrit grammar. The short vowel (a) and its long version (aa) are savarna. Similarly, i and ii are savarna; u and uu are savarna. When two savarna vowels meet (a+a, a+aa, aa+a, aa+aa), they all combine into a single long vowel (aa). This is Savarna Dirgha Sandhi.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the phrase "Guna Sandhi" in a sentence with an example from daily life or from Indian culture.', answer: 'Guna Sandhi is at work in the name "Ganesh" — गण (group) + ईश: (Lord) becomes गणेश: through the rule अ + ई = ए, showing how a well-known name is actually a product of Sanskrit grammar.', hint: 'Guna Sandhi: a/aa + i/ii = e; a/aa + u/uu = o. Famous examples: Ganesha, Mahesh, Upendra, Mahotsava.', reexplanation: 'Guna Sandhi has created many of the most well-known names in Indian culture: Ganesha (gana+esha), Mahesh (maha+esha), Mahendra (maha+indra), Upendra (upa+indra), Mahotsava (maha+utsava). Once you know Guna Sandhi, you see it everywhere in Sanskrit vocabulary.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Explain the two types of Sandhi taught in this chapter. For each type, state the rule, give two examples from the chapter (showing the combination clearly), and explain what the resulting compound word means.', answer: 'This chapter teaches two types of Sandhi (vowel combination rules). Type 1 — Savarna Dirgha Sandhi: The rule is that when similar vowels meet, they combine into one long vowel. There are four sub-rules: (a) अ/आ + अ/आ = आ: Example 1: पुस्तक + आलय: = पुस्तकालय: (library — house of books); Example 2: नव + अपि = नवापि (even nine). (b) इ/ई + इ/ई = ई: Example: कपि + ईश: = कपीश: (Lord of monkeys = Hanuman). (c) उ/ऊ + उ/ऊ = ऊ: Example: भानु + उदय: = भानूदय: (sunrise). Type 2 — Guna Sandhi: (a) अ/आ + इ/ई = ए: Example 1: गण + ईश: = गणेश: (Lord Ganesha — Lord of the ganas); Example 2: महा + ईश: = महेश: (great Lord = Shiva). (b) अ/आ + उ/ऊ = ओ: Example 1: महा + उत्सव: = महोत्सव: (great festival); Example 2: यथा + उचितम् = यथोचितम् (as appropriate). The key difference: Savarna Dirgha combines IDENTICAL vowels into one long vowel. Guna combines a/aa with i/ii to make e, or a/aa with u/uu to make o.', hint: 'Cover both types: Savarna Dirgha (identical vowels → long vowel: a+a=aa, i+i=ii, u+u=uu) and Guna (a/aa+i/ii=e and a/aa+u/uu=o). For each give the rule and two examples.', reexplanation: 'Savarna Dirgha: rule (similar vowels → long vowel), examples (pustakalayah, navapi, kapeesh, bhanudaya). Guna: rule i (a/aa+i/ii=e) with examples Ganesh/Mahesh; rule ii (a/aa+u/uu=o) with examples Mahotsava/Yathochitam. Explain the key distinction between the two types.' },
  ],
}

const quiz7: ChapterQuiz = {
  chapterId: 7, title: 'Bhutakalah (Past Tense)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What is the meaning of "भूतकाल:"?', options: [{ label: 'A', text: 'Future tense' }, { label: 'B', text: 'Present tense' }, { label: 'C', text: 'Past tense' }, { label: 'D', text: 'Imperative (command) form' }], answer: 'C', reexplanation: 'भूतकाल: = past tense. Bhuta = past / that which has been, Kala = time. The past tense in Sanskrit uses the Langlakar (लङ्गलकार:) — all forms of which have the prefix अ (a) added to the verb root.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What does "अपठत्" mean?', options: [{ label: 'A', text: 'I read' }, { label: 'B', text: 'You read' }, { label: 'C', text: 'He/she read' }, { label: 'D', text: 'They read' }], answer: 'C', reexplanation: 'अपठत् = he/she read. This is the Prathama Purusha (third person), Ekavachanam (singular) form of पठ् in Langlakar (past tense). अपठम् = I read; अपठ: = you read; अपठन् = they (all) read.' },
    { id: 3, type: 'mcq', marks: 1, question: 'What does "अहं भोजनम् अखादम्" mean?', options: [{ label: 'A', text: 'I will eat food' }, { label: 'B', text: 'I ate food' }, { label: 'C', text: 'I am eating food' }, { label: 'D', text: 'He ate food' }], answer: 'B', reexplanation: 'अहं भोजनम् अखादम् = I ate food. Aham = I, Bhojanam = food (accusative), Akhadam = ate (past tense, first person singular of khad = to eat). This is sentence 7 from the example sentences in the chapter.' },
    { id: 4, type: 'mcq', marks: 1, question: 'What is the Tritiya Purusha (first person) plural past tense form of पठ् (to read)?', options: [{ label: 'A', text: 'अपठत्' }, { label: 'B', text: 'अपठन्' }, { label: 'C', text: 'अपठाम' }, { label: 'D', text: 'अपठ:' }], answer: 'C', reexplanation: 'अपठाम = we (all) read. This is the Tritiya Purusha (first person), Bahuvachanam (plural) form. अपठत् = he/she read (3rd person singular); अपठन् = they all read (3rd person plural); अपठ: = you (one) read (2nd person singular).' },
    { id: 5, type: 'mcq', marks: 1, question: 'How many cases (विभक्ति:) does Sanskrit have?', options: [{ label: 'A', text: '5' }, { label: 'B', text: '6' }, { label: 'C', text: '7' }, { label: 'D', text: '8' }], answer: 'D', reexplanation: 'Sanskrit has 8 cases (विभक्ति:): Prathama (nominative), Dvitiya (accusative), Tritiya (instrumental), Chaturti (dative), Panchami (ablative), Shashti (genitive), Saptami (locative), and Sambodhana (vocative). This is why the वन शब्दरूप table has 8 rows.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "आवां जलं अपिबाव" mean?', answer: 'We two drank water', reexplanation: 'आवां जलं अपिबाव = we two drank water. Avam = we two (dual pronoun), Jalam = water (accusative), Apibav = drank (past tense, first person dual of pib = to drink). This is sentence 8 from the example sentences.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What is the "वनस्य" form of वन, and what case is it?', answer: 'वनस्य = of the forest (षष्ठी — genitive case, singular)', reexplanation: 'वनस्य = of the forest. This is the Shashti Vibhakti (sixth case = genitive — showing possession or relation) in the singular. Example from the textbook: एतद् वनस्य नाम "गिर" इति अस्ति — The name of this forest is "Gir."' },
    { id: 8, type: 'single_word', marks: 1, question: 'What does "पिता देवम् अपूजयत्" mean?', answer: 'Father worshipped God', reexplanation: 'पिता देवम् अपूजयत् = Father worshipped God. Pita = father (subject), Devam = God (accusative object), Apujayat = worshipped (past tense, third person singular of puj = to worship). This is sentence 10 from the example sentences.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the plural neuter form (प्रथमा विभक्ति:) of वन?', answer: 'वनानि (Vanani)', reexplanation: 'वनानि = forests (plural). This is the Prathama Vibhakti (nominative case) in the plural (Bahuvachanam) of वन. The plural neuter form adds -ani to the stem. Example: पुष्पाणि तत्र सन्ति — Flowers are there (पुष्पाणि = flowers, plural neuter nominative).' },
    { id: 10, type: 'single_word', marks: 1, question: 'Name any three Sanskrit nouns that decline like "वन" (neuter, ending in अ).', answer: 'Any three from: फल (fruit), पुष्प (flower), पुस्तक (book), नेत्र (eye), फलक (board), व्यजन (fan), वस्त्र (cloth), गीत (song)', reexplanation: 'All अकारान्त नपुसकलिंग (akaaranta napumsaka linga) nouns — neuter nouns ending in अ — decline like वन. The textbook specifically mentions: फल, पुष्प, पुस्तक, नेत्र, फलक, व्यजन, वस्त्र as examples.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the phrase "past tense" in a sentence explaining why Sanskrit uses a prefix अ (a) in the Langlakar.', answer: 'In Sanskrit\'s Langlakar (past tense), the prefix अ (a) is added to every verb form — so "he went" becomes अगच्छत् and "I read" becomes अपठम् — making past tense forms easy to recognise at a glance.', hint: 'Langlakar = past tense. All forms add the prefix a- to the verb root. अगच्छत् = he went (from gam = to go).', reexplanation: 'The prefix अ (a) called the "augment" is added to all Langlakar (past tense) forms. This makes past tense forms distinguishable from present tense forms — whenever you see a verb starting with अ followed by a known verb root, you know it is past tense. अगच्छत् (went), अपठत् (read), अखादम् (ate), अपूजयत् (worshipped).' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "dual" in a sentence about a unique feature of Sanskrit grammar.', answer: 'Sanskrit uniquely has a dual (द्विवचन) number for nouns and verbs — a special form used when exactly two people or things are involved — which gives Sanskrit greater precision than English.', hint: 'Dual = dvivachana in Sanskrit. Used for exactly two people or things. English has only singular and plural.', reexplanation: 'Sanskrit is unusual among world languages in having a three-way distinction of number: singular (one), dual (exactly two), and plural (three or more). In English, "they went" could mean two or two hundred. In Sanskrit, अगच्छताम् means exactly two went; अगच्छन् means three or more went. This precision is a distinctive feature of Sanskrit.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the form "वने" in a sentence about an animal (using the locative singular of वन).', answer: 'पशव: वने वसन्ति — Animals live in the forest. (वने is the Saptami Vibhakti, locative singular of वन, meaning "in the forest.")', hint: 'वने = in the forest (Saptami Vibhakti — locative case, showing location). This is sentence 6 in the chapter.', reexplanation: 'वने is the Saptami Vibhakti (seventh case = locative — showing location, meaning "in/at/on") of वन in the singular. पशव: वने वसन्ति = Animals live in the forest. The locative singular of वन-type nouns is always formed by adding -e to the stem.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Translate this sentence into English: "छात्रौ पुस्तकं अपठताम्।"', answer: 'The two students read the book. (Chhatrau = two students, Pustakam = the book, Apathatam = read — past tense dual form)', hint: 'छात्रौ = two students (dual), पुस्तकम् = book, अपठताम् = they two read (past tense, 3rd person dual of path).', reexplanation: 'छात्रौ = two students (nominative dual); पुस्तकम् = the book (accusative singular); अपठताम् = they two read (Prathama Purusha Dvivachana of पठ् in Langlakar). The dual form (अपठताम्) is the key — it tells us exactly two students are being talked about.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the form "पुस्तकानि" in a sentence, and explain what case it is.', answer: '"पुस्तकानि" is the nominative or accusative plural form of "पुस्तक" (book). Example: बालका: पुस्तकानि पठन्ति — Children read books.', hint: 'पुस्तकानि = books (nominative or accusative plural of पुस्तक, which declines like वन). -ani is the plural ending for neuter nouns.', reexplanation: 'पुस्तकानि is the Prathama (nominative) or Dvitiya (accusative) Bahuvachana (plural) of पुस्तक. In neuter nouns (like वन), the nominative and accusative singular and plural forms are identical. -ani is the standard neuter plural ending.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Write the complete Langlakar (past tense) conjugation of the verb पठ् (to read) — all 9 forms, with their English meanings. Then write any 5 example sentences from the chapter in Sanskrit, with their English meanings.', answer: 'Langlakar conjugation of पठ् (to read): Prathama Purusha (3rd person): अपठम् (I read), अपठाव (we two read), अपठाम (we all read). Dvitiya Purusha (2nd person): अपठ: (you read), अपठतम् (you two read), अपठत (you all read). Tritiya Purusha (1st person — note: Sanskrit numbering reverses from English): अपठत् (he/she read), अपठताम् (they two read), अपठन् (they all read). Five example sentences: 1. बालक: पाठशालां अगच्छत् — The boy went to school. 2. छात्रौ पुस्तकं अपठताम् — The two students read the book. 3. बालिका: कथां अकथयन् — The girls told a story. 4. अहं भोजनम् अखादम् — I ate food. 5. पिता देवम् अपूजयत् — Father worshipped God.', hint: 'Write all 9 forms of apathat in a 3×3 grid (3 persons × 3 numbers). Then write 5 example sentences with meanings.', reexplanation: 'The 9 forms: Prathama (3rd person): apatham (I), apathav (we 2), apathaam (we all); Dvitiya (2nd person): apathaH (you), apatatham (you 2), apathat (you all); Tritiya (1st person): apathat (he/she), apathataam (they 2), apathan (they all). Note: Sanskrit \'Prathama Purusha\' = English 3rd person, and \'Tritiya Purusha\' = English 1st person — the numbering is reversed.' },
  ],
}

const quiz8: ChapterQuiz = {
  chapterId: 8, title: 'Sambhashanam (Conversation — Nutritious Food)', totalMarks: 25,
  questions: [
    { id: 1, type: 'mcq', marks: 1, question: 'What food was Siya eating at the beginning of the conversation?', options: [{ label: 'A', text: 'Sprouts (अङ्कुराणि)' }, { label: 'B', text: 'Burger (बर्गर)' }, { label: 'C', text: 'Mango (आम्रम्)' }, { label: 'D', text: 'Rice (ओदनम्)' }], answer: 'B', reexplanation: 'At the beginning, Siya says: अहं बर्गर खादामि — I am eating a burger. Ananya asks what Siya is eating, and Siya replies with बर्गर (burger) — before Ananya explains the importance of nutritious food.' },
    { id: 2, type: 'mcq', marks: 1, question: 'What food did Ananya say she would eat instead?', options: [{ label: 'A', text: 'Banana (कदली)' }, { label: 'B', text: 'Mango (आम्रम्)' }, { label: 'C', text: 'Sprouts (अङ्कुराणि)' }, { label: 'D', text: 'Rice (ओदनम्)' }], answer: 'C', reexplanation: 'Ananya says: अहम् एतानि अङ्कुराणि खादिष्यामि — I will eat these sprouts. She then adds: एतत् तु पौष्टिक भोजनम् अस्ति — but this is nutritious food.' },
    { id: 3, type: 'mcq', marks: 1, question: 'How did Ananya define पौष्टिक भोजनम् (nutritious food)?', options: [{ label: 'A', text: 'Expensive food' }, { label: 'B', text: 'Health-promoting food (स्वास्थ्यवर्धकं भोजनम्)' }, { label: 'C', text: 'Traditional Indian food' }, { label: 'D', text: 'Food without oil' }], answer: 'B', reexplanation: 'Ananya explains: स्वास्थ्यवर्धकं भोजनम् एव पौष्टिक भोजनं भवति — Health-promoting food alone is nutritious food. Swasthyavardhakam = health-promoting (swasthya = health, vardhak = increasing/promoting).' },
    { id: 4, type: 'mcq', marks: 1, question: 'What does Siya promise to do the next day (श्व:)?', options: [{ label: 'A', text: 'Teach Ananya about food' }, { label: 'B', text: 'Cook lunch for the class' }, { label: 'C', text: 'Bring and eat nutritious food' }, { label: 'D', text: 'Stop eating entirely' }], answer: 'C', reexplanation: 'Siya says: श्व: अहमपि पौष्टिक भोजनम् एव आनेष्यामि खादिष्यामि च — Tomorrow I too will bring nutritious food and will eat it. श्व: = tomorrow; आनेष्यामि = I will bring; खादिष्यामि = I will eat (both are future tense forms).' },
    { id: 5, type: 'mcq', marks: 1, question: 'What Sanskrit word meaning "excellent" does Ananya use at the end?', options: [{ label: 'A', text: 'सुन्दरम्' }, { label: 'B', text: 'अतिशोभनम्' }, { label: 'C', text: 'प्रसन्नम्' }, { label: 'D', text: 'शोभनम्' }], answer: 'B', reexplanation: 'Ananya says: अतिशोभनम् — Excellent! Atishobhanam = very beautiful/excellent. Ati = very/beyond, Shobhana = beautiful/auspicious. This is an expression of enthusiastic approval in Sanskrit.' },
    { id: 6, type: 'single_word', marks: 1, question: 'What does "श्व:" mean?', answer: 'Tomorrow', reexplanation: 'श्व: = tomorrow. It is an unusual Sanskrit word — very different from the Hindi "kal." In Sanskrit, ह्य: (hyah) = yesterday and श्व: (shvah) = tomorrow. These are different words, unlike Hindi "kal" which can mean both.' },
    { id: 7, type: 'single_word', marks: 1, question: 'What does "अङ्कुराणि" mean?', answer: 'Sprouts (plural neuter)', reexplanation: 'अङ्कुराणि = sprouts. Ankura = a sprout or new shoot (singular). Ankurani = sprouts (plural neuter, using the -ani ending like the वन table). Sprouts are formed when seeds are soaked and allowed to germinate — they are very nutritious and high in protein.' },
    { id: 8, type: 'single_word', marks: 1, question: 'What does "महत्वम्" mean?', answer: 'Importance / significance', reexplanation: 'महत्वम् = importance, significance. From Maha (great) + the suffix -tva (making an abstract noun). Mahatva = the quality of being great = importance. The final line of the conversation says: त्वं पौष्टिकं भोजनस्य महत्वं अवगच्छसि — You understand the importance of nutritious food.' },
    { id: 9, type: 'single_word', marks: 1, question: 'What is the future tense form of "to bring" used by Siya? (आनेष्यामि)', answer: 'I will bring / आनेष्यामि (Aneshyami)', reexplanation: 'आनेष्यामि = I will bring. This is the future tense (Bhavishyakala) first person singular form of the verb "ana" (to bring). Future tense in Sanskrit is formed by adding -ishya- between the verb root and the personal ending.' },
    { id: 10, type: 'single_word', marks: 1, question: 'What does "अवगच्छसि" mean?', answer: 'You understand / you grasp', reexplanation: 'अवगच्छसि = you understand. Ava = prefix giving the meaning of grasping/comprehension, gam = to go, asi = you (present tense, 2nd person singular). The prefix "ava" turns the verb "to go" into "to go down into" = to comprehend/understand.' },
    { id: 11, type: 'sentence', marks: 2, question: 'Use the phrase "पौष्टिक भोजनम्" in a sentence explaining what it means.', answer: 'पौष्टिक भोजनम् means nutritious food — specifically, स्वास्थ्यवर्धकं भोजनम् (health-promoting food) like sprouts, fruits and vegetables that strengthen the body.', hint: 'Paushtik bhojanam = nutritious food. Ananya defines it as swasthyavardhakam bhojanam — health-promoting food.', reexplanation: 'Paushtik comes from the Sanskrit root "push" (to nourish/strengthen). Paushtik bhojanam is food that nourishes and strengthens the body. Ananya defines it precisely in the conversation: स्वास्थ्यवर्धकं भोजनम् एव पौष्टिक भोजनं भवति — health-promoting food alone is nutritious food.' },
    { id: 12, type: 'sentence', marks: 2, question: 'Use the word "sprouts" in a sentence about the conversation.', answer: 'In the conversation, Ananya chooses to eat sprouts (अङ्कुराणि) instead of a burger, explaining that sprouts are nutritious and health-promoting food.', hint: 'Ankurani = sprouts. Ananya says she will eat these sprouts (एतानि अङ्कुराणि खादिष्यामि).', reexplanation: 'Ankurani (sprouts) is the key food item in the conversation that contrasts with the burger. Sprouts represent paushtik (nutritious) food — they are packed with nutrients. The contrast between burger and sprouts effectively illustrates the difference between tasty-but-unhealthy and nutritious food.' },
    { id: 13, type: 'sentence', marks: 2, question: 'Use the future tense in a sentence, following the Sanskrit pattern shown in this chapter.', answer: 'अहम् अद्य पौष्टिक भोजनम् आनेष्यामि — Today I will bring nutritious food (following the same future tense pattern as the chapter, using aaneshyami = I will bring).', hint: 'Future tense in this chapter: खादिष्यामि (I will eat), आनेष्यामि (I will bring), खादिष्यसि (you will eat).', reexplanation: 'Sanskrit future tense is formed by adding -ishya- between the verb root and the personal ending. खादिष्यामि = I will eat (khad + ishya + mi), आनेष्यामि = I will bring (an + eshya + mi), खादिष्यसि = you will eat (khad + ishya + si). These are the future tense forms from the conversation.' },
    { id: 14, type: 'sentence', marks: 2, question: 'Use the Sanskrit word "प्रसन्ना" in a sentence about Ananya\'s reaction.', answer: 'When Siya promised to eat nutritious food the next day, Ananya said: अहं प्रसन्ना अस्मि — I am happy — showing how true friendship encourages better choices.', hint: 'Prasanna = happy/pleased. Ananya says: अहं प्रसन्ना अस्मि (I am happy) when Siya agrees to eat nutritious food.', reexplanation: 'प्रसन्ना (prasanna) = happy, pleased, serene. Ananya feels genuinely happy (प्रसन्ना अस्मि) when Siya decides to change her eating habits. This reflects the ideal of true friendship — not just accepting wrong choices, but gently guiding friends toward better ones.' },
    { id: 15, type: 'sentence', marks: 2, question: 'Use the word "conversation" in a sentence about why this chapter uses conversation to teach Sanskrit.', answer: 'The conversation format in this chapter shows that Sanskrit is a living language — capable of expressing everyday situations, future intentions, questions, agreements, and emotions — not just ancient texts and prayers.', hint: 'Sambhashanam = conversation. Why is a conversation a good way to learn Sanskrit?', reexplanation: 'A conversation (sambhashanam) is an excellent teaching tool because it shows language in action — in a real, relatable situation. The conversation covers: present tense (I eat, you eat), future tense (I will eat, I will bring), questions (किम् खादसि — what are you eating?), agreements (आम् — yes), and emotional responses (अतिशोभनम्, प्रसन्ना अस्मि). All of Sanskrit grammar comes alive in conversation.' },
    { id: 16, type: 'long_answer', marks: 5, question: 'Retell the entire conversation between Ananya and Siya in your own words in English. Include: what each character said, what nutritious food means according to the conversation, what Siya promised, and what Ananya said at the end.', answer: 'The conversation is a dialogue between two friends — Ananya and Siya — about nutritious food. It begins with Ananya asking Siya what she is eating. Siya replies that she is eating a burger, and asks Ananya what she will eat. Ananya says she will eat sprouts (ankurani) and tells Siya that sprouts are nutritious food. Siya, curious, asks if Ananya knows what nutritious food actually means. Ananya answers: Yes — health-promoting food alone is nutritious food (swasthyavardhakam bhojanam eva paushtik bhojanam bhavati). Siya, convinced, says: tomorrow I too will bring and eat nutritious food. Ananya responds with great enthusiasm — Excellent! I am happy. She tells Siya that she now understands the importance of nutritious food. The conversation shows two important lessons: (1) Nutritious food is food that promotes health — like sprouts, fruits and vegetables; (2) Good friendship means helping friends make better choices — not through criticism but through kind explanation and encouragement.', hint: 'Retell in order: Ananya asks → Siya eating burger → Ananya will eat sprouts → Siya asks what nutritious food is → Ananya defines it → Siya promises to change → Ananya says excellent and I am happy. Then mention the two lessons.', reexplanation: 'A complete answer covers: (1) The opening — Ananya asking Siya what she eats; (2) Siya eating a burger; (3) Ananya\'s choice of sprouts (ankurani) and statement that it is nutritious; (4) Siya\'s question about what nutritious food means; (5) Ananya\'s definition — swasthyavardhakam bhojanam; (6) Siya\'s promise — tomorrow I will bring nutritious food; (7) Ananya\'s response — atishobhanam, prasanna asmi, you understand the mahatvam; (8) The two lessons: healthy eating + good friendship.' },
  ],
}

export const ALL_SKT_QUIZZES: ChapterQuiz[] = [quiz1, quiz2, quiz3, quiz4, quiz5, quiz6, quiz7, quiz8]

export function getSktQuiz(chapterId: number): ChapterQuiz | undefined {
  return ALL_SKT_QUIZZES.find(q => q.chapterId === chapterId)
}
