// Auto-generated

const CHAPTER_16 = {
  id: 16,
  title: 'Swami Disappears',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"SWAMINATHAN'S father felt ashamed of himself as he approached\nEllaman Street, the last street of the town, which turned into a rough track\nfor about a hundred yards, and disappeared into the sands of the Sarayu\nRiver. He hesitated for a second at the end of Market Road, which was\nbright with the lights of a couple of late shops and a street gas lamp, before\nhe turned to plunge into the darkness and silence of Ellaman Street. A shaft\nof greenish light from the gas-lamp fell athwart Ellaman Street, illuminating\nonly a few yards of the street and leaving the rest in deep gloom. A couple\nof municipal lanterns smouldered in their wicks, emphasising the darkness\naround. Swaminathan's father felt ashamed of himself. He was going to cross the\nstreet, plod through the sand, and gaze into the Sarayu—for the body of his\nson! His son, Swami, to be looked for in the Sarayu! It seemed to him a\nridiculous thing to do. But what could he do? He dared not return home\nwithout some definite news of his son, good or bad. The house had worn a\nfunereal appearance since nine o'clock. His wife and his old mother were\nmore or less dazed and demented. She—his wife—had remained cheerful\ntill the Taluk Office gong struck ten, when her face turning white, she had\nasked him to go and find out from Swaminathan's friends and teachers what\nhad happened to him. He did not know where Swaminathan's Head Master lived. He had gone to\nthe Board School and asked the watchman, who misdirected him and made\nhim wander over half the town without purpose." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"He could not find Mani's\nhouse. He had gone to Rajam's house, but the house was dark, everybody had gone\nto bed, and he felt that it would be absurd to wake up the household of a\nstranger to ask if they had seen his son. From what he could get out of the\nservant sleeping in the veranda, he understood that Swaminathan had not\nbeen seen in Rajam's house that evening. He had then vaguely wandered in\n\nthe streets. He was doing it to please his wife and mother. He had not shared\nin the least his wife's nervousness. He had felt all along that the boy must\nhave gone out somewhere and would return, and then he would treat him\nwith some firmness and nip this tendency in the bud." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"He had spent nearly an\nhour thus and gone home. Even his mother had left her bed and was\nhobbling agitatedly about the house, praying to the God of the Thirupathi\nHills and promising him rich offerings if he should restore Swaminathan to\nher safe and sound. His wife stood like a stone image, looking down the\nstreet. The only tranquil being in the house was the youngest member 'of\nthe family, whose soft breathings came from the cradle, defying the gloom\nand heaviness in the house. When Swaminathan's father gave his wife the news—or no news—\nthat he had gathered from his wanderings, he had assumed a heavy\naggressive cheerfulness. It had lasted for a while, and gradually the anxiety\nand the nervousness of the two women infected him. He had begun to feel\nthat something must have happened to his son—a kidnapping or an\naccident. He was trying to reason out these fears when his wife asked in a trembling\nvoice: 'Did you search in the hospital?' and broke into a hysterical cry." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"He\nreceived this question with apparent disdain while his mind was conjuring\nup a vision of his son lying in a pulp in the hospital. He was struggling to\nerase this picture from his mind when his mother made matters worse with\nthe question: 'Tell me— tell me—where could the boy have gone? Were\nyou severe with him for anything this morning?' He was indignant at this\nquestion. Everybody seemed to be holding him responsible for\nSwaminathan's disappearance. Since nine o'clock he had been enduring the\nsly references and the suspicious glances. But this upset him, and he sharply\nasked his mother to return to her bed and not to let her brain concoct silly\nquestions. He had after that reviewed his behaviour with his son since the\nmorning, and discovered with surprise and relief that he had not seen him\nthe whole day." },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"The boy had risen from bed, studied, and gone to school,\nwhile he had shut himself up in his room with his clients. He then wondered\nif he had done anything in the past two or three days. He was not certain of\nhis memory, but he felt that his conduct was blameless. As far as he could\n\nremember there had not been any word or act of his that could have\nembittered the boy and make him do—do—wild things. It was nearing\ntwelve and he found his wife still sobbing. He tried to console her and rose\nto go out saying, again with a certain loud cheerfulness: 'I am going out to\nlook for him. If he comes before I return, for Heaven's sake don't let him\nknow what I am out for. I don't care to appear a fool in his eyes.'\nHe had walked rather briskly up Hospital Road, but had turned back after\nstaring at the tall iron gates of the hospital." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"He told himself that it was\nunnecessary to enter the hospital, but in fact knew that he lacked the\ncourage. That very window in which a soft dim light appeared might have\nbehind it the cot containing Swaminathan all pulped and bandaged. He\nbriskly moved out of Hospital Road and wandered about rather aimlessly\nthrough a few dark lanes around the place. With each hour, his heart\nbecame heavier. He had slunk past Market Road, and now entered Ellaman\nStreet. He swiftly passed through Ellaman Street and crossed the rough toot-path\nleading to the river. His pace slackened as he approached the river. He tried\nto convince himself that he was about to do a piece of work which was a\nfarce." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"But if the body of his son, sodden and bloated, should be seen stuck up\namong the reeds, and rocking gently on the ripples.... He shut his eyes and\nprayed: 'Oh, God, help me.' He looked far up and down the river which was\ngliding along with gentle music. The massive -peepul trees overhanging the\nriver sighed to the night. He started violently at the sight of the flimsy\nshadow of some branch on the water; and again as some float kept tilting\nagainst the moss-covered parapet with muffled thuds. And then, still calling himself a fool, he went to the Malgudi Railway\nStation and walked a mile or so along the railway line, keenly examining\nthe iron rails and the sleepers. The ceaseless hum and the shrill whistle of\nnight insects, the whirring of bats, and the croaking of frogs, came through\nthe awful loneliness of the night. He once stooped with a shudder to put his\nfinger on some wet patch on the rails. As he held up the finger and\nexamined it in the starlight and found that it was only water and not blood,\nhe heaved a sigh of relief and thanked God." },
  ],
}

export default CHAPTER_16