// Auto-generated chapter file

const CHAPTER_19 = {
  id: 19,
  title: 'Parting Present',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"ON Tuesday morning, ten days later, Swaminathan rose from bed with a\ngreat effort of will at five o'clock. There was still an hour for the train to\narrive at the Malgudi Station and leave it four minutes later, carrying away\nRajam, for ever.\nSwaminathan had not known that this was to happen till Mani came and\ntold him, on the previous night at about ten, that Rajam's father was\ntransferred -to Trichinopoly and the whole family would be leaving\nMalgudi on the following morning. Mani said that he had known it for\nabout a week, but Rajam had strictly forbidden him to say anything about it\nto Swaminathan. But at the last moment Mani could not contain himself and\nhad violated Rajam's ban.\nA great sense of desolation seized Swaminathan at once. The world seemed\nto have become blank all of a sudden. The thought of Lawley Extension\nwithout Rajam appalled him with its emptiness. He swore that he would\nnever go there again. He raved at Mani. And Mani bore it patiently.\nSwaminathan could not think of a world without Rajam. What was he to do\nin the evenings? How was he to spend the holiday afternoons? Whom was\nhe to think of as his friend?\nAt the same time he was filled with a sense of guilt: he had not gone and\nseen Rajam even once after his return. Fear, shame, a feeling of uncertainty,\nhad made him postpone his visit to Rajam day after day. Twice he had gone\nup to the gate of Rajam's house, but had turned back, his courage and\ndetermination giving way at the last moment. He was in this state, hoping to\nsee Rajam every to-morrow, when Mani came to him with the shattering\nnews. Swaminathan wanted to rush up to Rajam's house that very second\nand claim him once again. But—but—he felt awkward and shirked.\nTomorrow morning at the station. The train was leaving at six. He would go\nto the station at five." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"'Mani, will you call me at five to-morrow morning?'\n'No. I am going to sleep in Rajam's house, and go with him to the station.'\nFor a moment Swaminathan was filled with the darkest jealousy. Mani to sleep in Rajam's house, keep him company till the last moment,\ntalk and laugh till midnight, and he to be excluded! He wanted to cling to\nMani desperately and stop his going. When Mani left, Swaminathan went in, opened his dealwood box, and\nstood gazing into it. He wanted to pick out something that could be\npresented to Rajam on the following morning. The contents of the box were\na confused heap of odds and ends of all metals and materials. Here a\ncardboard box that had once touched Swaminathan's fancy, and there a toy\nwatch, a catalogue, some picture books, nuts and bolts, disused insignificant\nparts of defunct machinery, and so on to the brim. He rummaged in it for\nhalf an hour, but there seemed to be nothing in it worth taking to Rajam. The only decent object in it was a green engine given to him over a year\nago by Rajam. The sight of it, now dented and chipped in a couple of places\nand lying between an empty thread-reel and a broken porcelain vase, stirred\nin him vivid memories. He became maudlin. . ." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:". He wondered if he would\nhave to return that engine to Rajam now that they were no longer friends. He picked it up to take it with him to the station and return it to Rajam. On\nsecond thoughts, he put it back, partly because he loved the engine very\nmuch, partly because he told himself that it might be an insult to reject a\npresent after such a long time. . . . Rajam was a good reader, and\nSwaminathan decided to give him a book. He could not obviously give him\nany of the text-books. He took out the only book that he respected (as the\nfact of his separating it from the text-books on his desk and giving it a place\nin the dealwood box showed). It was a neat tiny volume of Andersen's Fairy\nTales that his father had bought in Madras years ago for him. He could\nnever get through the book to his satisfaction. There were too many\nunknown unpronounceable English words in it. He would give this book to\nRajam. He went to his desk and wrote on the fly-leaf 'To my dearest friend\nRaja m'." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"Malgudi Station was half dark when Swaminathan reached it with the tiny\nvolume of Andersen's Fairy Tales in his hand. The Station Master was just\nout of bed and was working at the table with a kerosene light, not minding\nin the least the telegraph keys that were tapping away endless messages to\nthe dawn.\nA car drew up outside. Swaminathan saw Rajam, his father, mother,\nsomeone he did not know, and Mani, getting down. Swaminathan shrank at\nthe sight of Rajam. All his determination oozed out as he saw the captain\napproach the platform, dressed like a 'European boy'. His very dress and\ntidiness made Swaminathan feel inferior and small. He shrank back and\ntried to make himself inconspicuous.\nAlmost immediately, the platform officers and policemen. Rajam was\nunapproachable. He was standing with his father in the middle of a cluster\nof people in uniform. All that Swaminathan could see of Rajam was his left\nleg, through a gap between two policemen. Even that was obstructed when\nthe policemen drew closer. Swaminathan went round, in search of further\ngaps.\nThe train was sighted. There was at once a great bustle.\nThe train hissed and boomed into the platform. The hustle and activity\nincreased. Rajam and his party moved to the edge of the platform. Things\nwere dragged and pushed into a Second Class compartment with desperate\nhaste by a dozen policemen. Rajam's mother got in. Rajam and his father\nwere standing outside the compartment. The police officers now barricaded\nthem completely, bidding them farewell and garlanding them. There was a\nmomentary glimpse of Rajam with a huge rose garland round his neck.\nSwaminathan looked for, and found Mani. 'Mani, Rajam is going away.'\n'Yes, Swami, he is going away.'\n'Mani, will Rajam speak to me?'\n'Oh, yes. Why not?' asked Mani." },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"Now Rajam and his father had got into the compartment. The door was\nclosed and the door-handle turned.\n'Mani, this book must be given to Rajam.' Swaminathan said. Mani saw that\nthere was no time to lose. The bell rang. They desperately pushed their way\nthrough the crowd and stood under a window. Swaminathan could hardly\nsee anything above. His head hardly came up to the door-handle.\nThe crowd pressed from behind. Mani shouted into the compartment:\n'Here is Swami to bid you good-bye.' Swaminathan stood on his toes. A\nhead leaned over the window and said: 'Good-bye, my Mani. Don't forget\nme.\nWrite to me.\n'Good-bye friend. . . . Here is Swami,' Mani said. Rajam craned his neck.\nSwaminathan's upturned eyes met his. At the sight of the familiar face\nSwaminathan lost control of himself and cried: 'Oh, Rajam, Rajam, you are\ngoing away, away. When will you come back?' Rajam kept looking at him\nwithout a word and then (as it seemed to Swaminathan) opened his mouth\nto say something, when everything was disturbed by the guard's blast and\nthe hoarse whistle of the engine. There was a slight rattling of chains, a\ntremendous hissing, and the train began to move. Rajam's face, with the\nwords still unuttered on his lips, receded. Swaminathan became desperate\nand blurted: 'Oh, Mani! This book must be given to him,' and pressed the\nbook into Mani's hand. Mani ran along the platform with the train and\nshouted over the noise of the train: 'Good-bye, Rajam. Swami gives you this\nbook.' Rajam held out his hand for the book, and took it, and waved a\nfarewell. Swaminathan waved back frantically.\nSwaminathan and Mani stood as if glued, where they were, and watched the\ntrain. The small red lamp of the last van could be seen for a long time, it\ndiminished in size every minute, and disappeared around a bend. All the\njarring, raiding, clanking, spurting, and hissing of the moving train softened\nin the distance into something that was half a sob and half a sigh." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"Swaminathan said: 'Mani, I am glad he has taken the book. Mani, he waved\nto me. He was about to say something when the train started. Mani, he did\nwave to me and to me alone. Don't deny it.'\n'Yes, yes,' Mani agreed.\nSwaminathan broke down and sobbed.\nMani said: 'Don't be foolish, Swami.'\n'Does he ever think of me now?' Swaminathan asked hysterically.\n'Oh, yes,' said Mani. He paused and added: 'Don't worry.\nIf he has not talked to you, he will write to you.' What do you mean?'\n'He told me so,' Mani said.\n'But he does not know my address.'\n'He asked me, and I have given it,' said Mani.\n'No. No. It is a lie. Come on, tell me, what is my address?'\n'It is—it is—never mind what.... I have given it to Rajam.'\nSwaminathan looked up and gazed on Mani's face to find out whether Mani\nwas joking or was in earnest. But for once Mani's face had become\ninscrutable.\n\nTable of Contents" },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"Now Rajam and his father had got into the compartment. The door was\nclosed and the door-handle turned.\n'Mani, this book must be given to Rajam.' Swaminathan said. Mani saw that\nthere was no time to lose. The bell rang. They desperately pushed their way\nthrough the crowd and stood under a window. Swaminathan could hardly\nsee anything above. His head hardly came up to the door-handle.\nThe crowd pressed from behind. Mani shouted into the compartment:\n'Here is Swami to bid you good-bye.' Swaminathan stood on his toes. A\nhead leaned over the window and said: 'Good-bye, my Mani. Don't forget\nme.\nWrite to me.\n'Good-bye friend. . . . Here is Swami,' Mani said. Rajam craned his neck.\nSwaminathan's upturned eyes met his. At the sight of the familiar face\nSwaminathan lost control of himself and cried: 'Oh, Rajam, Rajam, you are\ngoing away, away. When will you come back?' Rajam kept looking at him\nwithout a word and then (as it seemed to Swaminathan) opened his mouth\nto say something, when everything was disturbed by the guard's blast and\nthe hoarse whistle of the engine. There was a slight rattling of chains, a\ntremendous hissing, and the train began to move. Rajam's face, with the\nwords still unuttered on his lips, receded. Swaminathan became desperate\nand blurted: 'Oh, Mani! This book must be given to him,' and pressed the\nbook into Mani's hand. Mani ran along the platform with the train and\nshouted over the noise of the train: 'Good-bye, Rajam. Swami gives you this\nbook.' Rajam held out his hand for the book, and took it, and waved a\nfarewell. Swaminathan waved back frantically.\nSwaminathan and Mani stood as if glued, where they were, and watched the\ntrain. The small red lamp of the last van could be seen for a long time, it\ndiminished in size every minute, and disappeared around a bend. All the\njarring, raiding, clanking, spurting, and hissing of the moving train softened\nin the distance into something that was half a sob and half a sigh." },
  ],
}

export default CHAPTER_19