// Auto-generated

const CHAPTER_18 = {
  id: 18,
  title: 'The Return',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"IT was three-thirty on Sunday afternoon. The match between the M.C.C.\nand the Y.M.U. was still in progress. The Y.M.U. had won the toss, and\nwere all out for eighty-six at two o'clock. The captain's was the top score,\nthirty-two. The M.C.C. had none to bowl him out, and he stood there like an\nautomaton, hitting right and left, tiring out all the bowlers.\nHe kept on for hours, and the next batsman was as formidable, though not a\nscorer. He exhausted the M.C.C. of the little strength that was left, and\nRajam felt keenly the lack of a clever bowler.\nAfter the interval the game started again at two-thirty, and for the hour that\nthe M.C.C. batted the score stood at the unimpressive figure of eight with\nthree out in quick succession. Rajam and Mani had not batted. Rajam\nwatched the game with the blackest heart and cursed heartily everybody\nconcerned. The match would positively close at five-thirty; just two hours\nmore, and would the remaining eight make up at least seventy-eight and\ndraw the match? It was a remote possibility. In his despair he felt that at\nleast six more would follow suit without raising the score even to twenty.\nAnd then he and Mani would be left. And he had a wild momentary hope\nthat each might be able to get forty with a few judicious sixers and\nboundaries.\nHe was squatting along with his players on the ground in the shade of the\ncompound wall.\n'Raju, a minute, come here,', came a voice from above.\nRajam looked up and saw his father's head over the wall.\n'Father, is it very urgent?'\n'It is. I won't detain you for more than a minute.'" },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"When he hopped over the wall and was at his father's side, he was given a\nletter. He glanced through it, gave it back to his father, and said casually, 'So\nhe is safe and sound. I wonder what he is doing there.' He ruminated for a\nsecond and turned to go.\n'I am sending this letter to Swaminathan's father. He is sure to get a car and\nrush to the place. I shall have to go with him. Would you like to come?'\nRajam remained silent for a minute and said emphatically, 'No.'\n'Don't you want to see your friend and bring him back?'\n'I don't care,' Rajam said briefly, and joined his friends. He went back to his\nseat in the shade of the wall. The fourth player was promising. Rajam\nwhispered to Mani, 'I say that boy is not bad. Six runs already! Good, good.'\n'If these fellows make at least fifty we can manage the rest.'\nRajam nodded an assent, but an unnoticed corner of his mind began to be\nbusy with something other than the match. His father's news had stirred in\nhim a mixture of feelings. He felt an urgent desire to tell Mani what he had\njust heard. 'Mani, you know Swami—' he said and stopped short because he\nremembered that he was not interested in Swaminathan. Mani sprang up\nand asked, 'What about Swami? What about him? Tell me, Rajam. Has he\nbeen found?'\n'I don't know.'\n'Oh, Rajam, Rajam, you were about to say something about him.'\n'Nothing. I don't care.'\nSwaminathan had a sense of supreme well-being and security. He was\nflattered by the number of visitors that were coming to see him. His granny\nand mother were hovering round him ceaselessly, and it was with a\nsneaking satisfaction that he saw his little brother crowing unheeded in the\ncradle, for once overlooked and abandoned by everybody." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"Many of father's friends came to see him and behaved more or less alike. They stared at him with amusement and said how relieved they were to\nhave him back and asked some stereo typed questions and went away after\nuttering one or two funny remarks. Father went out with one of his friends. Before going, he said, 'Swami, I hope I shall not have to look for you when\nI come back.' Swaminathan was hurt by this remark. He felt it to be cruel\nand inconsiderate. After his father left, he felt more free, free to lord over a mixed gathering\nconsisting of mother's and granny's friends and some old men who were\nknown to the family long before Swaminathan's father was bom. Everybody gazed at Swaminathan and uttered loud remarks to his face. Through all this crowd Swaminathan espied the cook and bestowed a smile\non him. Over the babble the cook uttered some irrelevant, happy remark,\nwhich concluded with the hope that now father, mother and granny might\nresume the practice of taking food." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"Swaminathan was about to shout\nsomething in reply when his attention was diverted by the statement of a\nwidow, who, rolling her eyes and pointing heavenward, said that He alone\nhad saved the boy, and who could have foreseen that the Forest Officer\nwould be there to save the boy from die jaws of wild beasts? Granny said that she would have to set about fulfilling the great promises of\nofferings made to the Lord of the Seven Hills to whom alone she owed the\nsafe return of the child. Mother had meanwhile disappeared into the kitchen\nand now came out with a tumbler of hot coffee with plenty of sugar in it,\nand some steaming tiffin in a plate. Swaminathan, quickly and with great relish, disposed of both. A mixed\nfragrance, delicate and suggestive, came from the kitchen. Swaminathan cast his mind back and felt ashamed of himself for his\nconduct with the Forest Officer, when that harassed gentleman was waiting\nfor a reply from the Deputy Superintendent of Police, which took the form\nof a taxi drawing up before the Travellers' Bungalow, disgorging father,\nmother, Rajam's father, and an inspector of police. What a scene his mother\ncreated when she saw him! He had at first feared that Rajam's father and the\ninspector were going to handcuff him. What a fine man Rajam's father was!" },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"And how extraordinarily kind his own father was! So much so that, five\nminutes after meeting him, Swaminathan blurted out the whole story, from\nhis evasion of Drill Classes to his disappearance, without concealing a\nsingle detail. What was there so funny in his narration? Everybody laughed\nuproariously, and mother covered her face with the end of her sari and\nwiped her eyes at the end of every fit of laughter. . . .\nThis retrospect was spoiled by one memory. He had forgotten to take leave\nof the Forest Officer, though that gentleman opened the door of the car and\nstood near it. Swaminathan's conscience scorched him at the recollection of\nit.\nA gulp came to his throat at the thought of the kindly District Forest\nOfficer, looking after the car speeding away from him, thoroughly broken hearted by the fact that a person whose life he had saved should be so\nwicked as to go away without saying 'Good-bye.'\nHis further reflections on the subject and the quiet discussion among the\nvisitors about the possible dangers that might have befallen Swaminathan,\nwere all disturbed—destroyed, would be more accurate—by a tornado-like\npersonality sweeping into their midst with the tremendous shout,\n'What! Oh! Swami!' The visitors were only conscious of some mingled\nshoutings and brisk movements and after that both Swaminathan and Mani\ndisappeared from the hall. As they came to a secluded spot in the backyard,\nMani said, 'I thought you were dead or some such thing.'\n'I was, nearly.'\n'What a fool you were to get frightened of that Head Master and run away\nlike that!’ Rajam told me everything.\nI wanted to break your shoulders for not calling me when you had come to\nour school and called Rajam. . . .'\n'I had no time, Mani.'" },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"'Oh, Swami. I am so glad to see you alive. I was—I was very much troubled\nabout you. Where were you all along?'\n'I—I—I really can't say. I don't know where I was. Some- where—'\nHe recounted in this style his night of terrors and the subsequent events. 'Have I not always said that you were the worst coward I have ever known? You would have got safely back home if you had kept your head cool and\nfollowed the straight road. ‘You imagined all sorts of things.'\nSwaminathan took this submissively and said, 'But I can't believe that I was\npicked up by that cart-man. I don't remember it at all.'\nMani advised, 'If he happens to come to your place during Deepavali or\nPongal festival, don't behave like a niggard. He deserves a bag of gold. If he\nhad not cared to pic k you up, you might have been eaten by a tiger.'\n'And I have done another nasty thing,' Swaminathan said, 'I didn't thank and\nsay \"Good-bye\" to the Forest Officer before I came away. He was standing\nnear the car all the time.' 'If he was so near why did you seal your mouth'?'\n'I didn't think of it till the car had come half-way.'\n'You are a—a very careless fellow. You ought to have thanked him.'\n'Now what shall I do? Shall I write to him?'\n'Do. But do you know his address?'\n'My father probably does.'\n'What will you write?'\n'Just tell him—I don't know. I shall have to ask father about it. Some nice\nletter, you know. I owe him so much for bringing me back in time for the\nmatch.'\n\n'What are you saying?' Mani asked. 'Are you deaf? I was saying that I must ask father to write a nice letter, that\nis all.'\n'Not that. I heard something about the match. What is it?'\n'Yes?'\n'Are you mad to think that you are in time for the match?' asked Mani. He then related to Swaminathan the day's encounter with the Y.M.U. and\nthe depressing results, liberally explaining what Swaminathan's share was\nin the collapse of the M.C.C." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"'Why did you have it to-day?' Swaminathan asked weakly. ‘Why not?'\n'But this is only Saturday.'\n'Who said that?'\n‘The Forest Officer said that this was only Saturday.’\n'You may go and tell him that he is a blockhead,' Mani retorted. Swaminathan persisted that it could not be Sunday, till Mani threatened to\nthrow him down, sit on his body, and press his entrails out. Swaminathan remained in silence, and then said, 'I won't write him that\nletter. He has deceived me.'\n'Who?'\n'The Forest Officer. . . . And what does Rajam say about me?'\n'Rajam says a lot, which I don't wish to repeat. But I will tell you one thing. Never appear before him. He will never speak to yo u. He may even shoot\n\nyou on sight.'\n'What have I done?' asked Swaminathan. 'You have ruined the M.C.C. You need not have promised us, if you had\nwanted to funk. At least you could have told us you were going away. Why did you hide it from Rajam when you saw him at our school? That is\nwhat Rajam wants to know.'\nSwaminathan quietly wept, and begged Mani to pacify Rajam and convey\nto him Swaminathan's love and explanations. Mani refused to interfere,\n'You don't know Rajam. He is a gem. But it is difficult to get on with him.'\nWith a forced optimism in his tone Swaminathan said,\n'He will be all right when he sees me. I shall see him tomorrow morning.'\nMani wanted to change the topic, and asked: 'Are you going back to\nschool?'\n'Yes, next week. My father has already seen the Head Master, and it seems\nthings will be all right in the school. He seems to have known everything\nabout the Board School business.'\n‘Yes, I and Rajam told him everything.'\n'After all, I shall have to go back to the Board High School. Father says I\ncan't change my school now.'" },
  ],
}

export default CHAPTER_18