// Auto-generated

const CHAPTER_2 = {
  id: 2,
  title: 'Rajam and Mani',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"RIVER SARAYU was the pride of Malgudi. It was some ten minutes walk\nfrom Ellaman Street, the last street of the town, chiefly occupied by\noilmongers. Its sand-banks were the evening resort of all the people of the\ntown. The Municipal President took any distinguished visitor to the top of\nthe Town Hall and proudly pointed to him Sarayu in moonlight, glistening\nlike a silver belt across the North. The usual evening crowd was on the sand. Swaminathan and Mani sat aloof\non a river-step, with their legs dangling in water. The peepul branches\noverhanging the river rustled pleasantly. A light breeze played about the\nboughs and scattered stray leaves on the gliding stream below. Birds filled\nthe air with their cries. Far away, near Nallappa's Mango Grove, a little\ndownstream, a herd of cattle was crossing the river. And then a country cart\ndrawn by bullocks passed, the cart-man humming a low tune. It was some\nfifteen minutes past sunset and there was a soft red in the West. 'The water runs very deep here, doesn't it?' Mani asked. 'Yes, why?'\n'I am going to bring Rajam here, bundle him up, and throw him into the\nriver.'\nRajam was a fresh arrival in the First A. He had sauntered into the class on\nthe reopening day of the Second Term, walked up to the last bench, sat\nbeside Mani, and felt very comfortable indeed till Mani gave him a jab in\nthe ribs, which he returned. He had impressed the whole class on the very\nfirst day. He was a new-comer; he dressed very well—he was the only boy\nin the class who wore socks and shoes, fur cap and tie, and a wonderful coat\nand knickers." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"He came to the school in a car. As well as all this, he proved to be a very\ngood student too. There were vague rumours that he had come from some\n\nEnglish boys' school somewhere in Madras. He spoke very good English,\n'Exactly like a \"European\"'; which meant that few in the school could make\nout what he said. Many of his class-mates could not trust themselves to\nspeak to him, their fund of broken English being small. Only Sankar, the\ngenius of the class, had the courage to face him, though his English sounded\nhalting and weak before that of Rajam. This Rajam was a rival to Mani. In his manner to Mani he assumed a\ncertain nonchalance to which Mani was not accustomed. If Mani jabbed,\nRajam jabbed; if Mani clouted, he clouted; if Mani kicked, he kicked. If\nMani was the overlord of the class, Rajam seemed to be nothing less. And add to all this the fact that Rajam was a regular seventy percenter,\nsecond only to Sankar. There were sure indications that Rajam was the new\npower in the class. Day by day as Mani looked on, it was becoming\nincreasingly clear that a new menace had appeared in his life. All this lay behind his decision on the river-step to bundle up Rajam and\nthrow him into the river. Swaminathan expressed a slight fear: \"You forget\nthat his father is the police superintendent.' Mani remained silent for a while\nand said, What do I care? Some night I am going to crack his shoulders\nwith my clubs.'\n'If I were you, I would keep out of the way of policemen. They are an awful\nlot,' said Swaminathan." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"'If you were me! Huh! But thank God I am not you, a milk-toothed coward\nlike you.'\nSwaminathan bit his lips and sighed. 'And that reminds me,' said the other, 'you are in need of a little warning. I\nfind you hanging about that Rajam a bit too much. Well, have a care for\nyour limbs. That is all I can say.'\nSwaminathan broke into loud protestations. Did Mani think that\nSwaminathan could respect anyone but him, Mani the dear old friend and\n\nguide? What made him think so? As far as Swaminathan could remember,\nhe had never been within three yards of Rajam. Oh, how he hated him! That vile upstart! When had Mani seen him with Rajam? Oh, yes, it must\nhave been during the Drawing period on Monday. It was Rajam who had\ncome and talked to him in spite of the cold face that Swaminathan had\nturned to him. That ass had wanted a pencil sharpener, which he did not get, as he was\npromptly directed to go to a shop and buy it if he needed it so urgently. Oh, there was no comparison between Rajam and Mani. This pleased Mani greatly. For the first time that evening he laughed, and\nlaughed heartily too. He shook Swaminathan and gave such an affectionate\ntwist to his ear that Swaminathan gave a long howl. And then he suddenly\nasked, 'Did you bring the thing that I wanted?'\n'Oh, Mani! I beg a hundred pardons of you. My mother was all the time in\nthe kitchen. I could not get it.' ('It' referred to lime pickles.)\n'You are a nasty little coward— Oh, this riverbank and the fine evening. How splendid it would have been! ...'\nSwaminathan was to act as a cord of communication between Rajam and\nMani. They were sitting in the last bench with their backs against the\nyellow wall. Swaminathan sat between Rajam and Mani. Their books were\nbefore them on the desks; but their minds were busy. Mani wrote on a piece of paper 'Are you a man?' and gave it to\nSwaminathan, who pushed it across to Rajam, putting on as offensive a look\nas possible. Rajam read it, crumpled it, and threw it away. At which Mani\nwrote another note repeating the question, with the addition 'You are the son\nof a dog if you don't answer this,' and pushed it across. Rajam hissed into\nSwaminathan's face, 'You scoundrel, don't disturb me,' and crumpled the\nletter. Further progress was stopped." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"'Swaminathan, stand up,' said the teacher. Swaminathan stood up faithfully. 'What is Lisbon famous for?' asked the teacher. Swaminathan hesitated and ventured, 'For being the capital of Spain.'\nThe teacher bit his moustache and fired a second question, 'What do you\nknow about the Indian climate?'\n'It is hot in summer and cold in winter.'\n'Stand up on the bench!' roared the teacher. And Swaminathan stood up\nwithout a protest. He was glad that he was given this supposedly degrading\npunishment instead of the cane. The teacher resumed his lessons: Africa was a land of forests., Nile was the\nmost important river there. Did they understand? What did he say? He selected someone from the first bench to answer this question. (Nile was\nthe most important river in Africa, the boy answered promptly, and the\nteacher was satisfied.) What was Nile? (The most important river in Africa,\na boy answered with alacrity and was instantly snubbed for it, for he had to\nlearn not to answer before he was asked to.) Silence. Silence. Why was\nthere such a lot of noise in the class? Let them go on making & noise and\nthey would get a clean, big zero in the examination. He would see to that. Swaminathan paid no attention to the rest of the lessons. His mind began to\nwander. Standing on the bench, he stood well over the whole class. He could see so many heads, and he classified them according to the caps:\nthere were four red caps, twenty-five Gandhi caps, ten fur caps, and so on." },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"When the work for the day was over, Swaminathan, Mani, and Rajam,\nadjourned to a secluded spot to say what was in their minds. Swaminathan\nstood between them and acted as the medium of communication. They were\nso close that they could have heard each other even if they had spoken in\nwhispers. But it was a matter of form between enemies to communicate\n\nthrough a medium. Mani faced Swaminathan steadily and asked, 'Are you a\nman?'\nSwaminathan turned to Rajam and repeated, 'Are you a man?'\nRajam flared up and shouted, 'Which dog doubts it?'\nSwaminathan turned to Mani and said ferociously, 'Which dirty dog doubts\nit?'\n'Have you the courage to prove that you are a man?' asked Mani. Swaminathan turned to Rajam and repeated it. 'How?'\n'How?' repeated Swaminathan to Mani. 'Meet me at the river, near Nallappa's Grove, to -morrow evening.'\n'Near Nallappa's Grove,' Swaminathan was pleased to echo. 'What for?' asked Rajam. To see if you can break my head.'\n'Oh, to pieces,' said Rajam. Swaminathan's services were dispensed with. They gave him no time to\nrepeat their words. Rajam shouted in one ear, and Mani in the other. 'So we may expect you at the river to-morrow,' said Swaminathan. 'Yes,' Rajam assured them. Mani wanted to know if the ether would come with guards. No, he would\nnot. And Mani voiced another doubt:\n\n'If anything happens to you, will you promise to keep it out of your father's\nknowledge?' Rajam promised, after repudiating the very suggestion that he\nmight act otherwise. Nallappa's Grove stood a few yards before them. It was past six and the\ntraffic for the day between the banks was over." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"The usual evening crowd\nwas far behind them. Swaminathan and Mani were squatting on the sand. They were silent. Mani was staring at the ground, with a small wooden club\nunder his arm. He was thinking: he was going to break Rajam's head in a\nshort while and throw his body into the river. But if it should be recovered? But then how could they know that he had done it? But if Rajam should\ncome and trouble him at night as a spirit? Since his grandfather's death, he\nwas sleeping alone. What if Rajam should come and pull his hair at night? After all it would be better not to kill him. He would content himself with\nbreaking his limbs and leaving him to his fate. If he should batter his head,\nwho was going to find it out? Unless of course— He cast a sly look at\nSwaminathan, who was blinking innocently. . . . Unless of course Swaminathan informed the police. At the sound of the creaking of boots, they turned and found that Rajam had\ncome. He was dressed in khaki, and carried under his arm an air-gun that\nwas given to him a couple of months ago on his birthday." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"He stood very\nstiff and said: 'Here I am, ready.'\n'You are late.'\n'Yes.'\n'We will start.'\nRajam shouldered his gun and fired a shot in the air. Mani was startled. He\nstood still, his club down. 'You heard the shot?' asked Rajam. The next is going to be into your body,\nif you are keen upon a fight.'\n\n'But this is unfair. I have no gun while you have. ... It was to be a hand-to hand fight.'\nThen, why have you brought your club? You never said anything about it\nyesterday.'\nMani hung down his head. 'What have I done to offend you?' asked Rajam. 'You called me a sneak before someone.'\n‘That is a lie.'\nThere was an awkward pause. 'If this is all the cause of your anger, forget it. I won't mind being friends.'\n'Nor I,' said Mani. Swaminathan gasped with astonishment. In spite of his posing before Mani,\nhe admired Rajam intensely, and longed to be his friend. Now this was the\nhappiest conclusion to all the unwanted trouble. He danced with joy. Rajam lowered his gun, and Mani dropped his club. To show his goodwill,\nRajam pulled out of his pocket half a dozen biscuits. The river's mild rumble, the rustling of the peeyul leaves, the half-light of\nthe late evening, and the three friends eating, and glowing with new\nfriendship—Swaminathan felt at perfect peace with the world." },
  ],
}

export default CHAPTER_2