// Auto-generated

const CHAPTER_4 = {
  id: 4,
  title: 'What is a Tail?',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"THE Geography Master was absent, and the boys of the First A had leisure\nbetween three and three-forty-five on Wednesday.\nSomehow Swaminathan had missed his friends and found himself alone. He\nwandered along the corridor of the Infant Standards. To Swaminathan, who\ndid not really stand over four feet, the children of the Infant Standards\nseemed ridiculously tiny. He felt vastly superior and old.\nHe was filled with contempt when he saw them dabbling in wet clay, trying\nto shape models. It seemed such a meaningless thing to do at school! Why,\nthey could as well do those things resembling elephants, mangoes, and\nwhatnots, in the backyards of their houses. Why did they come all the way\nto a school to do this sort of thing? Schools were meant for more serious\nthings like Geography, Arithmetic, Bible, and English.\nIn one room he found all the children engaged in repeating simultaneously\nthe first two letters of the Tamil alphabet. He covered his ears and wondered\nhow the teacher was able to stand it. He passed on. In another room he\nfound an ill-clad, noisy crowd of children. The noise that they made, sitting\non their benches and swinging their legs, got on his nerves. He wrinkled his\nbrow and twisted his mouth in the hope of making the teacher feel his\nresentment but unfortunately the teacher was sitting with his back to\nSwaminathan.\nHe paused at the foot of the staircase leading to the senior classes the\nSecond and the Third Forms. He wanted to go up and inspect those classes\nwhich he eagerly looked for ward to joining. He took two or three steps up,\nand changed his mind. The Head Master might be up there, he always\nhandled those classes. The teachers too were formidable, not to speak of the\nboys themselves, who were snobs and bullies. He heard the creak of sandals\nfar off and recognised the footsteps of the Head Master. He did not want to\nbe caught there—that would mean a lot of unsatisfactory explanations." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"It was with pleasant surprise that he stumbled into his own set, which he\nhad thought was not at school. Except Rajam and Mani all the rest were\nthere. Under the huge tamarind tree they were playing some game. Swaminathan joined them with a low, ecstatic cry. The response\ndisappointed him. They turned their faces to him with a faint smile, and\nreturned to their game. What surprised Swaminathan most was that even the\ngenial Somu was grim. Something seemed to be wrong somewhere. Swaminathan assumed an easy tone and shouted: 'Boys, what about a little\nplace for me in the game?' Nobody answered this. Swaminathan paused and\nannounced that he was waiting for a place in the game. 'It is a pity, we can't take more,' Sankar said curtly. There are people who can be very efficient as tails,' said the Pea. The rest\nlaughed at this. ‘You said Tail, didn't you?' asked Sankar. ‘What makes ' you talk of Tail\nnow?'\n'It is just my pleasure. What do you care? It doesn't apply to you anyway,'\nsaid the Pea. 'I am glad to hear it, but does it apply to anyone here?' asked Sankar. 'It may.'\n‘What is a Tail?'\n'A long thing that attaches itself to an ass or a dog.'\nSwaminathan could comprehend very little except that the remark contained\nsome unpleasant references to himself. His cheeks grew hot. He wanted to\ncry. The bell rang and they ran to their class. Swaminathan slunk to his seat with\na red face. It was the English period presided over by Vedanayagam. He was reading\nthe story of the old man who planted trees for posterity and was paid ten\nrupees by a king. Not a word reached Swaminathan's brain, in which there\nwas only dull pain and vacuity. If he had been questioned he would have\nblundered and would have had to spend the rest of the hour standing on the\nbench." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"But his luck was good. The period was over. He was walking home alone, rather slowly, with a\ntroubled heart. Somu was going a few yards in front of him. Swaminathan\ncried out: 'Somu, Somu. . . . Somu, won't you stop?' Somu stopped till the\nother came up. After a brief silence Swaminathan quavered: 'What is the\nmatter with you fellows?'\n'Nothing very particular,' replied Somu. 'By the way, may I inform you that\nyou have earned a new name?—The Tail, Rajam's Tail, to be more precise. We aren't good enough for you, I believe. But how can everyone be a son of\na Police Superintendent?' With that he was off. This was probably Swaminathan's first shock in life. It paralysed all his\nmental processes. When his mind started working again, he faintly\nwondered if he had been dreaming. The staid Somu, the genial Somu, the\nuncle Somu, was it the same Somu that had talked to him a few minutes\nago? What was wrong in liking and going about with Rajam? Why did it\nmake them so angry? He went home, flung his coat and cap and books on the table, gulped down\nthe cold coffee that was waiting for him, and sat on the pyol, vacantly\ngazing into the dark intricacies of the gutter that adorned Vinayaka Mudali\nStreet. A dark volume of water was rushing along. Odd pieces of paper,\nleaves, and sticks, floated by. A small piece of tin was gently skimming\nalong. Swaminathan had an impulse to plunge his hand in and pick it up. But he let it go. His mind was inert. He watched the shining bit float away. It was now at the end of the compound wall; now it had passed under the\ntree." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"Swaminathan was slightly irritated when a brick obstructed the progress of\nthe tin. He said that the brick must either move along or stand aside without\ninterfering with the traffic. The piece of tin released itself and dashed along\n\nfuriously, disappeared round a bend at the end of the street. Swaminathan\nran in, got a sheet of paper, and made a boat. He saw a small ant moving\nabout aimlessly. He carefully caught it, placed it in the boat, and lowered\nthe boat into the stream. He watched in rapture its quick motion. He held\nhis breath when the boat with its cargo neared a danger zone formed by\nstuck-up bits of straw and other odds and ends. The boat made a beautiful\nswerve to the right and avoided destruction. It went on and on. It neared a\nfatal spot where the waters were swirling round and round in eddies. Swaminathan was certain that his boat was nearing its last moment. He had\nno doubt that it was going to be drawn right to the bottom of the circling\neddies. The boat whirled madly round, shaking and swaying and quivering." },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"But providentially a fresh supply of water from the kitchen in the\nneighbour's house pushed it from behind out of danger. But it rushed on at a\nfearful speed, and Swaminathan felt that it was going to turn turtle. Presently it calmed, and resumed a normal speed. But when it passed under\na tree, a thick dry leaf fell down and upset it. Swaminathan ran frantically to\nthe spot to see if he could save at least the ant. He peered long into the\nwater, but there was no sign of the ant. The boat and its cargo were wrecked\nbeyond recovery. He took a pinch of earth, uttered a prayer for the soul of\nthe ant, and dropped it into the gutter. In a few days Swaminathan got\naccustomed to his position as the enemy of Somu and company. All the same now and then he had an irresistible desire to talk to his old\nfriends. When the Scripture Master pursed his lips and scratched his nose,\nSwaminathan had a wild impulse to stamp on the Pea's leg and laugh, for\nthat was a joke that they had never failed to enjoy day after day for many\nyears past. But now Swaminathan smothered the impulse and chuckled at it\nhimself, alone. And again, when the boy with the red cap nodded in his seat\nand woke up with a start every time his head sank down, Swaminathan\nwanted to whisper into the Pea's ear: 'Look at that fellow, third on the first\nbench, red cap —Now he is falling off again—' and giggle; but he merely\nbit his lips and kept quiet. Somu was looking in his direction." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"Swaminathan thought that there was\nfriendliness in his look. He felt a momentary ecstasy as he realised that\n\nSomu was willing to be friendly again. They stared at each other for a\nwhile, and just as Swaminathan was beginning to put on a sweet friendly\nlook, Somu's expression hardened and he turned away. Swaminathan was loitering in the compound. He heard familiar voices\nbehind, turned round, and saw Somu, Sankar, and the Pea, following him. Swaminathan wondered whether to stop and join them, or wait till they had\npassed and then go in the opposite direction. For it was awkward to be\nconscious of the stare of three pairs of hostile eyes behind one's ears. He\nbelieved that every minute movement of his body was being watched and\ncommented on by the three followers. He felt that his gait was showing\nunfavourably in their eyes. He felt they were laughing at the way in which\nhe carried his books. There was a slight itching on his nape, his hand almost\nrose, but he checked it, feeling that the scratching would be studiously\nwatched by the six keen eyes. He wanted to turn to his right and enter the school hall. But that would be\nconstrued as cowardice; they would certainly think that he was doing it to\nescape from them. He wanted to run away, but that would be no better." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"He\nwanted to turn back and get away in the opposite direction, but that would\nmean meeting them square in the face. So, his only recourse was to keep on\nwalking as best as he could, not showing that he was conscious of his\nfollowers. The same fellows ten days ago, what they were! Now what\nformidable creatures they had turned out to be! Swaminathan was wonder\nstruck at the change. It was becoming unendurable. He felt that his legs were taking a circular\nmotion, and were twining round each other when he walked. It was too late\nto turn and dash into the school hall. He had passed it. Now he had only one\nway of escape. He must run. It was imperative. He tried a trick. He paused suddenly, turned this way and that, as if looking for something,\nand then cried aloud: -Oh, I have left my note-book somewhere,'\nraised his hand and was off from the spot like a stag." },
  ],
}

export default CHAPTER_4