// Auto-generated chapter file

const CHAPTER_5 = {
  id: 5,
  title: 'Father\'s Room',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"IT WAS Saturday and Rajam had promised to come in the afternoon.\nSwaminathan was greatly excited. Where was he to entertain him? Probably\nin his own 'room'; but his father often came in to dress and undress. No, he\nwould be at Court, Swaminathan reminded himself with relief. He cleaned\nhis table and arranged his books so neatly that his father was surprised and\nhad a good word to say about it.\nSwaminathan went to his grandmother. 'Granny,' he said,\n'I have talked to you about Rajam, haven't I?\n‘Yes. That boy who is very strong but never passes his examination.'\n'No. No. That is Mani.'\n'Oh, now I remember, it is a boy who is called the Gram or something, that\nwitty little boy.'\nSwaminathan made a gesture of despair. 'Look here granny, you are again\nmistaking the Pea for him. I mean Rajam, who has killed tigers, whose\nfather is the Police Superintendent, and who is great.'\n'Oh,' granny cried, 'that boy, is he coming here? I am so glad.'\n'H'm. . . . But I have got to tell you—'\n'Will you bring him to me? I want to see him.'\n'Let us see,' Swaminathan said vaguely, 'I can't promise. But I have got to\ntell you, when he is with me, you must not call me or come to my room.'\n'Why so?' asked granny." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"'The fact is—you are, well you are too old,' said Swaminathan with brutal\ncandour. Granny accepted her lot cheerfully.\nThat he must give his friend something very nice to eat, haunted his mind.\nHe went to his mother, who was squatting before a cutter with a bundle of\nplantain leaves beside her. He sat before her, nervously crushing a piece of\nleaf this way and that, and tearing it to minute bits.\n'Don't throw all those bits on the floor. I simply can't sweep the floor any\nmore,' she said.\n'Mother, what are you preparing for the afternoon tiffin?'\n'Time enough to think of it,' said mother.\n'You had better prepare something very nice, something fine and sweet.\nRajam is coming this afternoon. Don't make the sort of coffee that you\nusually give me. It must be very good and hot.' He remembered how in\nRajam's house everything was brought to the room by the cook. 'Mother,\nwould you mind if I don't come here for coffee and tiffin? Can you send it\nto my room?' He turned to the cook and said: 'Look here you can't come to\nmy room in that dhoti. You will have to wear a clean, white dhoti and shirt.'\nAfter a while he said: 'Mother, can you ask father to lend me his room for\njust an hour or two?' She said that she could not as she was very busy. Why\ncould he himself not go and ask?\n'Oh, he will give more readily if you ask,' said Swaminathan.\nHe went to his father and said: 'Father, I want to ask you something.'\nFather looked up from the papers over which he was bent.\n'Father, I want your room.'\n'What for?'\n'I have to receive a friend,' Swaminathan replied." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"'You have your own room,' father said.\n'I can't show it to Rajam.'\n‘Who is this Rajam, such a big man?'\n'He is the Police Superintendent's son. He is —he is not ordinary.'\n'I see. Oh! Yes, you can have my room, but be sure not to mess up the\nthings on the table.'\n'Oh, I will be very careful. You are a nice father, father.'\nFather guffawed and said: 'Now run in, boy, and sit at your books.'\nRajam's visit went off much more smoothly that Swaminathan had\nanticipated. Father had left his room open; mother had prepared some\nmarvel with wheat, plum, and sugar. Coffee was really good. Granny had\nkept her promise and did not show her senile self to Rajam. Swaminathan\nwas only sorry that the cook did not change his dhoti.\nSwaminathan seated Rajam in his father's revolving chair. It was nearly\nthree hours since he had come. They had talked out all subjects—\nMani, Ebenezar, trains, tiger-hunting, police, and ghosts.\nWhich is your room?' Rajam asked.\nSwaminathan replied with a grave face: This is my room,why?'\nRajam took time to swallow this. 'Do you read such books?' he asked,\neyeing the big gilt-edged law books on the table. Swaminathan was\nembarrassed.\nRajam made matters worse with another question.\n'But where are your books?' There was just a flicker of a smile on his lips." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"'The fact is,' said Swaminathan, 'this table belongs to my father. When I am\nout, he meets his clients in this room.'\n'But where do you keep your books?'\nSwaminathan made desperate attempts to change the topic: 'You have seen\nmy grandmother, Rajam?'\n'No. Will you show her to me? I should love to see her’ replied Rajam.\n'Wait a minute then,' said Swaminathan and ran out.\nHe had one last hope that his granny might be asleep. It was infinitely safer\nto show one's friends a sleeping granny.\nHe saw her sitting on her bed complacently. He was disappointed. He stood\nstaring at her, lost in thought.\n'What is it, boy?' granny asked, 'Do you want anything?'\n'No. Aren't you asleep? Granny,' he said a few minutes later, 'I have brought\nRajam to see you.'\n'Have you?' cried granny, 'Come nearer, Rajam. I can't see your face well.\nYou know I am old and blind.'\nSwaminathan was furious and muttered under his breath that his granny had\nno business to talk all this drivel to Rajam.\nRajam sat on her bed. Granny stroked his hair and said that he had fine soft\nhair, though it was really short and prickly. Granny asked what his mother's\nname was, and how many children she had. She then asked if she had many\njewels. Rajam replied that his mother had a black trunk filled with jewels,\nand a green one containing gold and silver vessels. Rajam then described to\nher Madras, its light house, its sea, its trams and buses, and its cinemas.\nEvery item made granny gasp with wonder.\nWhen Swaminathan entered the class, a giggle went round the benches. He\nwalked to his seat hoping that he might not be the cause of the giggling. But" },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"it continued. He looked about. His eyes travelled up to the black-board. His\nface burnt red. On the board was written in huge letters\n'TAIL'. Swaminathan walked to the black-board and rubbed it off with his\nhands. He turned and saw Sankar's head bent over his note-book, and the\nPea was busy, unpacking his satchel. Without a word Swaminathan\napproached the Pea and gave him a fierce slap on his cheek. The Pea burst\ninto tears and swore that he did not do it. He cast a sly look at Sankar, who\nwas absorbed in some work. Swaminathan turned to him and slapped his\nface also.\nSoon there was pandemonium, Sankar, Swaminathan, and the Pea, rolling\nover, tearing, scratching, and kicking one another. The bell rang.\nRajam, Somu, and Mani entered. The teacher came in and stood aghast. He\ncould do little more than look on and ejaculate. He was the old Tamil\nPundit, the most helpless teacher in the school.\nSomu and Mani parted the fighters. The teacher ascended the platform and\ntook his seat. The class settled down. Somu got up and said: 'Sir, please let\nus go out. We do not want to disturb the class.' The teacher demurred; but\nalready Mani had gone out, pushing Swaminathan and the Pea before him.\nSomu followed him with Sankar.\nThey came to a lonely spot in the field adjoining the school. There was\ntense silence for a while, and Mani broke it: \"What is wrong with you, you\nlittle rogues?' Three started to speak at once. Swaminathan's voice was the\nloud- protest: 'He—the Pea— wrote TAIL—Big Tail—on the Black-board\n—big—'\n'No—I didn't, you—' screamed the Pea.\nThe other two wrote it,' cried Swaminathan pointing at Sankar.\n'Rascal! Did you see me?' howled Sankar." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"Mani covered their mouths with his hands. 'What is a tail, anyway?' he\nasked, not having been told anything about it till then.\n'They call me Rajam's tail,' sobbed Swaminathan.\nA frozen expression came over Mani's face, and he asked,\n'And who dares to talk of Rajam here?'\n'Oh, dare!' repeated Somu.\n'If any of you fellows have done it—' growled Mani, looking at the\ntrembling Sankar and the Pea.\n'If they have, what can you do?' asked Somu with a contemptuous smile.\n'What do you mean, Somu, what do you mean?'\n'Look here, Mani,' Somu cried, 'for a long time I have been waiting to tell\nyou this: you think too much of yourself and your powers.' Mani swung his\nhand and brought it down on Somu's nape. Somu pushed it away with a\nheavy blow. Mani aimed a kick at Somu, which would send him rolling.\nSomu stepped aside and delivered one himself, which nearly bent the other.\nThe three youngsters could hardly believe their eyes. Somu and Mani\nfighting! They lost their heads. They thought that Somu and Mani were\nkilling each other. They looked accusingly at one another, and then ran\ntowards the school.\nThey burst in upon the Head Master, who gathered from them with\ndifficulty that in the adjacent field two murders were being committed at\nthat very moment. He was disposed to laugh at first. But the excitement and\nseriousness on the boy's faces made him check his laughter and scratch his\nchin. He called a peon and with him set off to the field.\nThe fighters, rolling and rolling, were everywhere in the field. The Head\nMaster and the peon easily picked them apart, much to the astonishment of" },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"Swaminathan, who had thought till then that the strength that Somu or Mani\npossessed was not possessed by anyone else in the world." },
  ],
}

export default CHAPTER_5