// Auto-generated chapter file

const CHAPTER_6 = {
  id: 6,
  title: 'A Friend in Need',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"ONE AFTERNOON three weeks later, Swaminathan stood before Mani's\nhouse and gave a low whistle. Mani joined him. They started for Rajam's\nhouse, speculating on the way what the surprise (which Rajam had said he\nwould give them if they saw him that afternoon) might be. 'I think,' said Swaminathan, 'Rajam is merely joking. It is merely a trick to\nget us to his house.' He was very nearly pushed into a gutter for this doubt. 'Probably he has bought a monkey or something,' Swaminathan ventured\nagain. Mani was gracious enough to admit that it might be so. They thought\nof all possible subjects that might surprise them, and gave up the attempt in\nthe end. Their thoughts turned to their enemies. 'You know what I am going to do?'\nMani asked. 'I am going to break Somu's waist. I know where he lives. He lives in Kabir Street, behind the market. I have often seen him coming\nout at nights to a shop in the market for betel leaves." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"I shall first fling a\nstone at the municipal lamp and put it out. You have no idea how dark\nKabir Street is. ... I shall wait with my club, and as soon as he appears— He\nwill sprawl in the dust with broken bones. . . .' Swaminathan shuddered at\nthe thought. 'And that is not all,' said Mani, 'I am going to get that Pea under\nby heel and press him to the earth. And Sankar is going to hang by his tuft\nover Sarayu, from a peepul branch... .'\nThey stopped talking when they reached Rajam's house. The gate was\nbolted, and they got up the wall and jumped in. A servant came running\ntowards them. He asked, 'Why, did you climb the wall?' ;\n'Is the wall your property?' Mani asked and burst into laughter. 'But if you had broken your ribs—' the servant began." },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"'What is that to you? Your ribs are safe, are they not?'\nSwaminathan asked ungraciously and laughed.\n'And just a word more,' Mani said, 'do you happen to be by any chance the\nPolice Superintendent's son?'\n'No, no,' replied the servant.\n'Very well then,' replied Mani, 'we have come to see and talk to the Police\nSuperintendent's son.' The servant beat a hasty retreat.\nThey banged their fists on Rajam's door. They heard the clicking of the\nlatch and hid themselves behind the pillar.\nRajam peeped out and shut the door again.\nThey came out, stood before the door, and wondered what to do.\nSwaminathan applied his mouth to the keyhole and mewed like a cat. Mani\npulled him away and putting his mouth to the hole barked like a dog. The\nlatch clicked again, and the door slightly opened. Mani whispered to\nSwaminathan, 'You are a blind kitten, I will be a blind puppy.'\nMani fell down on his knees and hands, shut his eyes tight, pushed the door\nwith his head, and entered Raja m's room in the role of a blind puppy.\nSwaminathan crawled behind him with shut eyes, mewing for all he was\nworth. They moved round and round the room, Rajam adding to the interest\nof the game by mewing and barking in answer every few seconds. The\nblind puppy brushed its side against a leg, and thinking that it belonged to\nRajam, softly bit the calf muscle. Imagine its confusion when it opened its\neyes and saw that it was biting its enemy, Somu! the blind kitten nestled\nclose to a leg and scratched it with its paw. Opening its eyes it found that it\nwas fondling a leg that belonged to its enemy, Sankar.\nMani remained stunned for a moment, and then scrambled to his feet." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"He looked around, his face twitching with shame and rage. He saw the Pea\nsitting in a corner, his eyes twinkling with mischief, and felt impelled to\ntake him by the throat. He turned round and saw Rajam regarding him\nsteadily, his mouth still quivering with a smothered grin.\nAs for Swaminathan he felt that the best place for himself would be the\ndarkness and obscurity under a table or a chair.\n'What do you mean by this, Rajam?' Mani asked.\n'Why are you so wild?'\n'It was your fault,' said Mani vehemently, 'I didn't know—' He looked\naround.\n'Well, well. I didn't ask you to crawl and bark, did I?'\nSomu and company laughed. Mani glared round, 'I am going away, Rajam.\nThis is not the place for me.'\nRajam replied, 'You may go away, if you don't want me to see you or speak\nto you any more.'\nMani fidgeted uneasily. Rajam took him aside and soothed him.\nRajam then turned to Swaminathan, who was lost in bottomless misery. He\ncomforted and flattered him by saying that it was the best imitation of a cat\nand dog that he had ever witnessed in his life. He admitted that for a few\nminutes he wondered whether he was watching a real cat and a dog. They\nwould get prizes if they did it in fairs. If Swaminathan and Mani would be\ngood enough to repeat the fun, he would be delighted, and even ask his\nfather to come and watch.\nThis was soothing. Swaminathan and Mani felt proud of themselves.\nAnd after the round of eating that followed, they were perfectly happy,\nexcept when they thought of the other three in the room." },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"They were in this state of mind when Rajam began a lecture on friendship. He said impressive things about friendship, quoting from his book the story\nof the dying old man and the faggots, which proved that union was strength. A friend in need was a friend indeed. He then started giving hair-raising\naccounts of what hell had in store for persons who fostered enmity. According to Rajam, it was written in the Vedas that a person who fostered\nenmity should be locked up in a small room, after his death. He would be\nmade to stand, stark naked, on a pedestal of red-hot iron, there were\nbeehives all around with bees as big as lemons. If the sinner stepped down from the pedestal, he would have to put his foot\non immense scorpions and centipedes that crawled about the room in\nhundreds—\n(A shudder went through the company.)\n—The sinner would have to stand thus for a month, without food or sleep. At the end of a month he would be transferred to another place, a very\nnarrow bridge over a lake of boiling oil. The bridge was so narrow that he\nwould be able to keep only one foot on it at a time. Even on the narrow\nbridge there were plenty of wasp nests and cactus, and he would be goaded\nfrom behind to move on. He would have to balance on one foot, and then on\nanother, for ages and ages, to keep himself from falling into the steaming\nlake below, and move on indefinitely." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:". . . The company was greatly impressed. Rajam then invited everyone to come\nforward and say that they would have no more enemies. If Sankar said it, he\nwould get a bound note-book; if Swaminathan said it, he would get a clock work engine; if Somu said it, he would get a belt; and if Mani said it, he\nwould get a nice pocket-knife; and the Pea would get a marvellous little\npen. He threw open the cupboard and displayed the prizes. There was silence for\nsome time as each sat gnawing his nails. Rajam was sweating with his\npeace-making efforts. The Pea was the first to rise. He stood before the cup board and said, 'Let me see the fountain-pen.' Rajam gave it him. The Pea turned it round and round and gave it back without any comment.\n\n'Why don't you like it?' Rajam asked. The Pea kept staring into the\ncupboard and said, 'Can I have that box?' He pointed at a tiny box with a lot\nof yellow and black designs on it and a miniature Taj Mahal on its lid.\nRajam said, 'I can't give you that. I want it.' He paused.\nHe had two more boxes like that in his trunk. He changed his mind,\n'No. I don't want it. You can take the box if you like.'\nIn a short while, Mani was sharpening a knife on his palm; Somu was trying\na belt on; Sankar was fingering a thick bound note-book; and Swaminathan\nwas jealously clasping a green engine to his bosom." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"'What is that to you? Your ribs are safe, are they not?'\nSwaminathan asked ungraciously and laughed.\n'And just a word more,' Mani said, 'do you happen to be by any chance the\nPolice Superintendent's son?'\n'No, no,' replied the servant.\n'Very well then,' replied Mani, 'we have come to see and talk to the Police\nSuperintendent's son.' The servant beat a hasty retreat.\nThey banged their fists on Rajam's door. They heard the clicking of the\nlatch and hid themselves behind the pillar.\nRajam peeped out and shut the door again.\nThey came out, stood before the door, and wondered what to do.\nSwaminathan applied his mouth to the keyhole and mewed like a cat. Mani\npulled him away and putting his mouth to the hole barked like a dog. The\nlatch clicked again, and the door slightly opened. Mani whispered to\nSwaminathan, 'You are a blind kitten, I will be a blind puppy.'\nMani fell down on his knees and hands, shut his eyes tight, pushed the door\nwith his head, and entered Raja m's room in the role of a blind puppy.\nSwaminathan crawled behind him with shut eyes, mewing for all he was\nworth. They moved round and round the room, Rajam adding to the interest\nof the game by mewing and barking in answer every few seconds. The\nblind puppy brushed its side against a leg, and thinking that it belonged to\nRajam, softly bit the calf muscle. Imagine its confusion when it opened its\neyes and saw that it was biting its enemy, Somu! the blind kitten nestled\nclose to a leg and scratched it with its paw. Opening its eyes it found that it\nwas fondling a leg that belonged to its enemy, Sankar.\nMani remained stunned for a moment, and then scrambled to his feet." },
  ],
}

export default CHAPTER_6