// Auto-generated

const CHAPTER_9 = {
  id: 9,
  title: 'School Breaks Up',
  sections: [
    { id:1, title:"Setting the Scene", minReadSeconds:120,
      content:"WITH dry lips, parched throat, and ink-stained fingers, and exhaustion on\none side and exaltation on the other, Swaminathan strode out of the\nexamination hall, on the last day. Standing in the veranda, he turned back and looked into the hall and felt\nslightly uneasy. He would have felt more comfortable if all the boys had\ngiven their papers as he had done, twenty minutes before time. With his left\nshoulder resting against the wall, Sankar was lost to the world. Rajam,\nsitting under the second ventilator, between two Third-Form boys, had\nbecome a writing machine. Mani was still gazing at the rafters, scratching\nhis chin with the pen. The Pea was leaning back in his seat, revising his\nanswers. One supervisor was drowsing in his chair; another was pacing up and down,\nwith an abstracted look in his eyes. The scratchy noise of active nibs, the\nrustle of papers, and the clearing of the throats, came through the brooding\nsilence of the hall. Swaminathan suddenly wished that he had not come out so soon. But how\ncould he have stayed in the hall longer? The Tamil paper was set to go on till five o'clock. He had found himself\nwriting the last line of the last question at four-thirty. Out of the six\nquestions set, he had answered the first question to his satisfaction, the\nsecond was doubtful, the third was satisfactory, the fourth, he knew, was\nclearly wrong (but then, he did not know the correct answer). The sixth answer was the best of the lot. It took only a minute to answer it. He had read the question at two minutes to four-thirty, started answering a\nminute later, and finished it at four-thirty." },
    { id:2, title:"Rising Action", minReadSeconds:120,
      content:"The question was:\n'What moral do you infer from the story of the Brahmin and lie Tiger?' (A\nbrahmin was passing along the edge of a pond. A tiger hailed him from the\n\nother bank and offered him a gold bangle. The brahmin at first declined the\noffer, but when the tiger protested its innocence and sincerity and insisted\nupon his taking the bangle, he waded through the water. Before he could\nhold out his hand for the bangle, he was inside the tiger.) Swaminathan had\nnever thought that this story contained a moral. But now he felt that it must\nhave one since the question paper mentioned it. He took a minute to decide\nwhether the moral was; 'We must never accept a gold bangle when it is\noffered by a tiger' or 'Love of gold bangle cost one one's life'. He saw more\nlogic in the latter and wrote it down. After writing, he had looked at the big\nhall clock. Half an hour more!" },
    { id:3, title:"The Plot Thickens", minReadSeconds:120,
      content:"What had he to do for half an hour? But he\nfelt awkward to be the first to go out. Why could not the others be as quick\nand precise as he? He had found it hard to kill time. Why wasn't the paper set for two and a\nhalf hours instead of three? He had looked wistfully at the veranda outside. If only he could pluck up enough courage to hand in the paper and go out—\nhe would have no more examinations for a long time to come—he could do\nwhat he pleased—roam about the town in the evenings and afternoons and\nmorning—throw away the books —command granny to tell endless tales. He had seen a supervisor observing him, and had at once pretended to be\nbusy with the answer paper. He thought that while he was about it, he might\nas well do a little revision." },
    { id:4, title:"Complications", minReadSeconds:120,
      content:"He read a few lines of the first question and was\nbored. He turned over the leaves and kept gazing at the last answer. He had\nto pretend that he was revising. He kept gazing at the moral of the tiger\nstory till it lost all its meaning. He set his pen to work. He went on\nimproving the little dash under the last line indicating the end, till it became\nan elaborate complicated pattern. He had looked at the clock again, thinking that it must be nearly five now. It\nwas only ten minutes past four-thirty. He saw two or three boys giving up\ntheir papers and going out, and felt happy. He briskly folded the paper and\nwrote on the flap the elaborate inscription: Tamil Tamil\nW. S. Swaminathan\n\nI st Form A section\nAlbert Mission School\nMalgudi\nSouth India\nAsia. The bell rang. In twos and threes boys came out of the hall. It was a\nthorough contrast to the preceding three hours. There was the din of excited\nchatter. 'What have you written for the last question?' Swaminathan asked a class mate. 'Which? The moral question?. . . Don't you remember what the teacher said\nin the class? . . . \"Love of gold cost the brahmin his life.\"'\n'Where was gold there?' Swaminathan .objected. \"There was only a gold\nbangle. How much have you written for the question?'\n'One page,' said the class-mate. Swaminathan did not like this answer. He had written only a line. \"What! You should not have written so much.'\nA little later he found Rajam and Sankar. 'Well, boys, how did you find the\npaper?'\n'How did you find it?' Sankar asked. 'Not bad,' Swaminathan said. 'I was afraid only of Tamil,' said Rajam, 'now I think I am safe. I think I\nmay get passing marks.'" },
    { id:5, title:"Turning Point", minReadSeconds:120,
      content:"'No. Certainly more. A class,' Sankar said. 'Look here,' Swaminathan said, 'some fools have written a page for that\nmoral question.'\n'I wrote only three-quarters of a page,' Rajam said. 'And I only a little more than half,' said Sankar, who was an authority on\nthese matters. 'I too wrote about that length, about half a page,' lied Swaminathan as a\nsalve to his conscience, and believed it for the moment. 'Boys, do you remember that we have no school from to-morrow?'\n'Oh, I forgot all about it,' Rajam said. 'Well, what are you going to do with yourselves?' somebody asked. ‘I am going to use my books as fuel in the kitchen,' Swaminathan said. 'My father has bought a lot of books for me to read during the vacation,\nSinbad the Sailor, Alibaba, and so on,' said Sankar. Mani came throwing up his arms and wailing: 'Time absolutely insufficient. I could have dashed off the last question,'\nThe Pea appeared from somewhere with a huge streak of ink on his left\ncheek. 'Hallo Sankar, first class?'\n'No. May hardly get thirty-five.'\n‘You rascal, you are lying. If you get a first class, may I cut off your tuft?'\nMani asked. The bell rang again fifteen minutes later. The whole school crowded into\nthe hall. There was joy in every face and good-fellowship in every word. Even the teachers tried to be familiar and pleasant. Ebenezar, when he saw\n\nMani, asked: 'Hallo, block-head, how are you going to waste your\nvacation?'\n'I am going to sleep, sir,' Mani said, winking at his friends. 'Are you likely to improve your head by the time you return to the school?'\n'How is it possible, sir, unless you cut off Sankar's head and present it to\nme?' A great roar of laughter followed this. There would have been roars of laughter at anything; the mood was such." },
    { id:6, title:"Falling Action", minReadSeconds:120,
      content:"In\nsheer joy the Drawing Master was bringing down his cane on a row of feet\nbecause, he said, he saw some toes growing to an abnormal length. The Head Master appeared on the platform, and after waiting for the noise\nto subside, began a short speech, in which he said that the school would\nremain closed till the nineteenth of June and open again on the twentieth. He hoped that the boys would not waste their time but read story-books and\nkeep glancing through the books prescribed for their next classes, to which,\nhe hoped, most of them were going to be promoted. And now a minute\nmore, there would be a prayer, after which the boys might disperse and go\nhome. At the end of the prayer the storm burst. With the loudest, lustiest cries, the\ngathering flooded out of the hall in one body. All through this vigorous\nconfusion and disorder,\nSwaminathan kept close to Mani. For there was a general belief in the\nschool that enemies stabbed each other on the last day. Swaminathan had no\nenemy as far as he could remember. But who could say? The school was a\nbad place." },
    { id:7, title:"Resolution", minReadSeconds:120,
      content:"Mani did some brisk work at the school gate, snatching from all sorts of\npeople ink-bottles and pens, and destroying them. Around him was a crowd\nseething with excitement and joy. Ecstatic shrieks went up as each article of\nstationery was destroyed. One or two little boys feebly protested. But Mani wrenched the ink-bottles from their hands, tore their caps, and\npoured ink over their clothes. He had a small band of assistants, among\nwhom Swaminathan was prominent, overcome by the mood of the hour, he\nhad spontaneously emptied his ink-bottle over his own head and had drawn\nfrightful dark circles under his eyes with the dripping ink. A policeman passed in the road. Mani shouted: 'Oh, policeman, policeman! Arrest these boys!' A triumphant cry from a hundred throats rent the air. A\nfew more ink-bottles exploded on the ground and a few more pens were\nbroken. In the midst of it Mani cried: 'Who will bring me Singaram's\nturban? I shall dye it for him.'\nSingaram, the school peon, was the only person who was not affected by\nthe spirit of liberty that was abroad, and as soon as the offer to dye his\nturban reached his ears, he rushed into the crowd with a big stick and\ndispersed the revellers." },
  ],
}

export default CHAPTER_9